# -*- coding: utf-8 -*-
"""Doral: copia en español."""

ZONA = {
    "key": "doral",
    "title": "Doral: remoción de abejas en naves, tejas y patios",
    "desc": "Remoción de abejas en vivo en Doral: panales en almacenes, puertas enrollables, tejas y contadores de agua. Teléfono 24/7 y reparación con contratistas propios.",
    "h1": "Abejas en Doral: fuera de naves industriales y viviendas",
    "kicker": "Doral, condado de Miami-Dade",
    "lede": "En Doral conviven parques empresariales, showrooms y urbanizaciones con asociación de propietarios. A las abejas les da igual si el hueco es de un almacén o de una vivienda: buscan un espacio seco y oscuro. Nosotros las sacamos vivas y cerramos ese hueco.",
    "quick": "Con 14 parques empresariales dentro de sus límites, en Doral un panal puede estar en el cajón de una puerta enrollable de almacén tanto como bajo una teja corrida o en la tapa del contador de agua de una casa. Un vuelo constante por un mismo punto delata una colonia adentro. Aleje a la gente y a las mascotas, no rocíe nada y llame: alguien atiende el teléfono 24/7 y garantizamos contestar su caso dentro de un plazo de 24 horas. Sacamos las abejas vivas para apicultores y nuestros contratistas con licencia reparan.",
    "alarm": "¿Alguien recibió varias picaduras, se le hincha la cara o le cuesta respirar? Llame primero al 911. Mientras llega la ayuda, lleve a todos a un lugar cerrado, sea un edificio o un carro con las ventanas subidas, y no manotee a las abejas. Cuando la persona ya esté atendida, avísenos: un caso con picaduras se adelanta a cualquier otro trabajo en la agenda.",
    "glance": [
        ("Incorporada", "2003, tras un esfuerzo de siete años"),
        ("Población (censo 2020)", "75,874 habitantes"),
        ("Superficie", "unas 15 millas cuadradas"),
        ("Parques empresariales", "14; en todo Miami-Dade pasan de 30"),
        ("Límites", "Palmetto Expressway al este; Turnpike y Everglades al oeste"),
    ],
    "opening": "El nombre de Doral sale de Doris y Alfred Kaskel, la pareja que a finales de los años cincuenta compró unos 2,400 acres de terreno pantanoso y en 1962 abrió el Doral Country Club. Alrededor de aquel club creció una ciudad que se incorporó en 2003 y que hoy reparte sus cerca de 15 millas cuadradas entre calles de almacenes, centros de distribución, showrooms y urbanizaciones de casas, townhouses y condominios de poca altura.\n\nEsa mezcla cambia la manera de atender un problema de abejas. Una colonia instalada detrás de la lámina de una nave industrial no se trabaja igual que otra metida bajo las tejas de una casa, y el riesgo para la gente también es distinto: en un caso hay montacargas, camiones y empleados entrando por la misma puerta; en el otro, niños en el patio y un perro que ladra al panal. Lo que no cambia es el método. Retiramos el panal completo con las abejas vivas, se las entregamos a apicultores, cerramos la entrada y dejamos la reparación terminada por nuestros propios contratistas con licencia.",
    "hotspots_h": "Puntos de Doral donde anidan las colonias",
    "hotspots": [
        ("Cajones de puertas enrollables", "En los almacenes, el cajón donde se recoge la puerta de acero pasa casi todo el día cerrado y a la sombra. Una exploradora lo encuentra, el enjambre entra por la ranura lateral y nadie se da cuenta hasta que el primer turno recibe picaduras al subir la puerta por la mañana."),
        ("Paletas y contenedores apilados", "Una torre de paletas de madera que lleva semanas sin moverse, o un contenedor viejo arrinconado detrás del almacén, ofrece cavidades secas y protegidas del sol. Antes de que el montacargas levante esa pila, revise si hay un vuelo constante entrando por un solo punto."),
        ("Tapas de riego y del medidor", "En los jardines de las urbanizaciones, la tapa del contador o de la caja de válvulas queda a ras del césped. Adentro hay oscuridad y resguardo, justo lo que busca un enjambre, y el jardinero puede toparse con ellas al pasar la podadora."),
        ("Tejas, aleros y plafones", "Si su casa tiene techo de teja, basta una pieza corrida o un hueco en el plafón del alero para que la colonia construya panal en el ático o debajo de la teja. Con la cámara térmica ubicamos el panal antes de levantar nada."),
        ("Letreros de locales y showrooms", "Los letreros iluminados tienen cajas huecas de metal o acrílico, y la abertura por donde pasa el cableado alcanza para que entren las abejas. El panal crece justo encima de la acera por donde caminan los clientes hacia la puerta."),
    ],
    "band": ("Un panal junto al muelle de carga no espera", "Descríbanos el caso por teléfono o con una imagen por texto: respondemos dentro de 24 horas y cotizamos gratis."),
    "streets_h": "Doral por partes: urbanizaciones, centro y zona industrial",
    "streets": [
        ("Doral Estates", "Es una urbanización desarrollada a comienzos de los años ochenta por Bill, nieto de los Kaskel. En sus casas, las colonias aparecen en paredes, áticos, aleros y cajas de riego."),
        ("Doral Park", "Llegó después, como empresa conjunta con Lennar. Si su vivienda está bajo una asociación de propietarios y la administración exige constancia de seguro (COI) antes de autorizar trabajos en áreas comunes, se la enviamos para que la aprobación no frene la remoción."),
        ("Downtown Doral", "Es el núcleo urbano más reciente de la ciudad; en junio de 2019 la biblioteca pública del condado trasladó allí su sucursal Doral. Si su edificio tiene varios pisos, el panal puede estar en una jardinera de azotea, un balcón o un ducto, y coordinamos acceso y horario con la administración."),
        ("CityPlace Doral", "Queda en el lado este de la ciudad. En áreas comerciales con mesas afuera y mucha gente caminando, un enjambre que se posa en un árbol o un letrero se nota enseguida; si sigue colgado al día siguiente, conviene retirarlo antes de que se meta en una cavidad y empiece a construir panal."),
        ("Parques empresariales", "Doral concentra 14 de los más de 30 parques empresariales de Miami-Dade, y su plan de uso de suelo industrial admite almacenes, showrooms y centros de distribución. Ahí acordonamos el área, pactamos la hora con el gerente y, si lo pide, entregamos fotos y factura detallada."),
        ("Borde oeste junto al Turnpike", "Por el oeste la ciudad termina en el Ronald Reagan Turnpike y, más allá, en los Everglades. Las propiedades con terreno abierto alrededor tienen más árboles y cercas donde un enjambre puede detenerse a descansar antes de buscar una cavidad definitiva."),
    ],
    "body": [
        ("Abejas en un almacén sin detener la operación", "En una nave industrial el problema rara vez es solo el panal. Hay turnos, camiones que llegan con hora fija y mercancía que no puede quedarse en el muelle. Por eso la visita se planifica con el encargado: definimos qué puerta queda cerrada, por dónde circula el personal y a qué hora conviene abrir la pared o el cajón de la puerta enrollable.\n\nLas paredes de lámina con aislante ocultan bien una colonia a la vista, y la cámara térmica nos dice dónde está antes de cortar. Retiramos los panales con las abejas vivas, limpiamos la miel para que no atraiga a otro enjambre y sellamos la entrada. Si el dueño del edificio o la aseguradora lo exige, mandamos la constancia de seguro (COI), y al terminar, si las pide, le dejamos fotos y una factura detallada para su contabilidad. Cuando la colonia está dentro de un muro, la página de [[es:svc-abejas-en-paredes|abejas dentro de paredes]] explica qué se abre y cómo se vuelve a cerrar."),
        ("Casas, townhouses y condominios con asociación", "En una urbanización, las abejas de una pared compartida entre dos townhouses no respetan la línea de propiedad: el panal puede ocupar el hueco de ambos lados. Antes de abrir hablamos con usted y, si hace falta, con el vecino o la asociación, para tener acceso al punto exacto donde está la colonia.\n\nEn el techo, una teja levantada sin cuidado se quiebra y abre otra entrada. Por eso el trabajo lo terminan nuestros propios techadores con licencia, y los pintores procuran dejar el estuco del mismo tono que el resto de la fachada. Así no queda un parche que la asociación le pida corregir después. La sección sobre [[es:svc-abejas-en-techos|panales bajo tejas y en el ático]] cuenta cómo se levanta y se repone cada pieza."),
        ("Lo que conviene hacer mientras tanto", "No rocíe insecticida ni tape el agujero por donde entran. Una colonia encerrada busca otra salida, y a veces la encuentra hacia adentro, por un tomacorriente o una lámpara del techo. Tampoco intente sacar el panal con una manguera: las abejas se alteran y la cera con miel se queda pudriéndose en la pared.\n\nLo útil es otra cosa. Anote por dónde entran y salen, a qué hora hay más movimiento y si hay alguien en casa o en el trabajo con alergia a las picaduras. Mantenga a niños y mascotas lejos de ese punto y avísele al jardinero que no pase la podadora junto al contador de agua. Si ya hubo picaduras, llame a la línea de [[es:svc-emergencias|emergencias con abejas]] en vez de esperar."),
        ("De qué depende el precio", "Si las abejas se alcanzan desde el piso, por ejemplo dentro de la tapa del medidor o colgando de un seto, la cuenta ronda entre $300 y $400. Cuando la colonia lleva tiempo dentro de una pared, un techo de teja o la estructura de un almacén, y hay que abrir, retirar el panal entero y reparar, el costo puede llegar a miles de dólares. Atender un sábado, un domingo o a medianoche lleva un recargo frente al horario normal de lunes a viernes. La cotización es gratis, y en la página de [[es:precios|precios de remoción]] están los factores con más calma. Para pedir la visita en línea use el [[es:solicitar|formulario de solicitud]]."),
    ],
    "visit_h": "Así se desarrolla la visita",
    "visit": [
        ("Llamada y cotización", "Por teléfono nos describe el sitio del panal, cuántos días lleva viéndolo y si hubo picaduras. Con eso sale la cotización gratis y se fija la visita según lo urgente que sea."),
        ("Ubicar la colonia", "Con la cámara térmica seguimos el calor del panal a través de paredes, plafones o lámina metálica, para abrir solo donde hace falta y no a ciegas."),
        ("Sacar el panal con las abejas", "Retiramos panal y abejas juntos, se los entregamos a apicultores que las reubican y limpiamos los restos de cera y miel que podrían atraer a una colonia nueva."),
        ("Cerrar y reparar", "Cerramos el acceso, y la pared, el plafón o las tejas quedan reparados por techadores, pintores y contratistas de nuestro propio equipo, todos con licencia. ¿Reaparecen abejas en el sitio exacto que cerramos? Nos avisa y volvemos."),
    ],
    "faqs": [
        ("¿Pueden trabajar en mi almacén mientras el negocio sigue abierto?", "Casi siempre se puede. Acordonamos el área alrededor del panal, acordamos con el encargado qué puerta o pasillo queda fuera de uso y elegimos una hora con poco movimiento. Si la colonia está en un punto de paso obligado, podemos planificar la remoción de noche o en fin de semana, sabiendo que esas salidas cuestan más que una visita entre semana."),
        ("La administración del condominio pide constancia de seguro. ¿La tienen?", "La constancia (COI) sale antes de la visita, dirigida a la asociación, al administrador o al dueño del local, porque trabajamos con licencia y con seguro. De ese modo la aprobación del trabajo en áreas comunes no retrasa la remoción y todos saben quién responde si algo pasa durante la visita."),
        ("¿Por qué no fumigarlas y listo?", "Porque nunca exterminamos abejas, y porque fumigar no resuelve el problema. Las abejas muertas, la miel y la cera se quedan dentro de la pared, fermentan, manchan el estuco y atraen hormigas, cucarachas y a otro enjambre que huele el panal viejo. Sacarlas vivas y limpiar la cavidad es lo que evita que el problema regrese."),
        ("Tengo abejas en el contador de agua. ¿Puedo levantar la tapa?", "Mejor no. Al levantar la tapa la colonia queda expuesta de golpe y defiende el panal. Ponga algo visible alrededor para que nadie la pise, avise al jardinero y llámenos. La remoción en una caja de contador es un trabajo a nivel del suelo, de los más sencillos, y se explica en [[es:svc-contador-de-agua|abejas en el contador de agua]]."),
        ("¿Contestan de noche y los fines de semana?", "Sí. Alguien contesta a cualquier hora, todos los días, y su caso recibe respuesta en 24 horas como máximo, garantizado; quien tiene picaduras pasa delante. Salir de madrugada, un sábado o un domingo encarece el servicio frente a un día laborable, y ese recargo se lo comunicamos antes de confirmar."),
    ],
    "servicios": [
        ("abejas-en-paredes", "Paredes de bloque con estuco en casas y muros de lámina con aislante en naves industriales: en los dos casos hay que ubicar el panal antes de abrir."),
        ("abejas-en-techos", "Tejas corridas, aleros y plafones de casas y townhouses, con la reparación a cargo de nuestros techadores con licencia."),
        ("contador-de-agua", "Cajas de contador y de válvulas de riego en jardines de urbanizaciones, que conviene marcar para que nadie las pise mientras tanto."),
        ("enjambres", "Racimos colgados de árboles, cercas o letreros de locales comerciales, que conviene retirar antes de que se instalen en una cavidad."),
        ("emergencias", "Picaduras en un muelle de carga, un patio o una acera concurrida: esas llamadas tienen prioridad a cualquier hora."),
    ],
    "cercanos": ["hialeah", "hialeah-gardens", "miami"],
    "close": ("Que las abejas de Doral terminen con un apicultor", "Cuéntenos qué ve y dónde. Con la cotización gratis sabrá cómo lo resolvemos antes de comprometerse a nada."),
    "card": "Doral: almacenes, showrooms y urbanizaciones con asociación. Abejas vivas fuera de puertas enrollables, tejas y contadores de agua, con reparación de contratistas propios.",
    "facts": [
        "Doral se incorporó como ciudad en 2003: los votantes aprobaron la incorporación en enero de 2003, tras un esfuerzo de siete años, y aceptaron la carta municipal en junio de 2003 (source: https://en.wikipedia.org/wiki/Doral,_Florida y https://www.cityofdoral.com/About/Doral-History)",
        "Alfred y Doris Kaskel compraron 2,400 acres de terreno pantanoso a finales de los años cincuenta; el Doral Country Club abrió en 1962 y el nombre une Doris y Alfred (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral tiene unas 15 millas cuadradas (source: https://www.cityofdoral.com/About/Doral-Facts)",
        "Población en el censo de 2020: 75,874 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Limita al oeste con el Ronald Reagan Turnpike y los Everglades, al norte con Medley, al este con la Palmetto Expressway y al sur con la Dolphin Expressway y Sweetwater (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral Estates fue desarrollada a comienzos de los años ochenta por Bill, nieto de los Kaskel; después vino Doral Park como empresa conjunta con Lennar (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Downtown Doral es el núcleo urbano más reciente; la sucursal Doral del sistema de bibliotecas públicas de Miami-Dade se mudó allí en junio de 2019 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "CityPlace Doral está en el este de la ciudad (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral contiene 14 de los más de 30 parques empresariales de Miami-Dade (source: https://www.cityofdoral.com/About/Doral-Facts)",
        "La categoría de uso de suelo industrial permite almacenes, showrooms y centros de distribución; la residencial de densidad moderada incluye casas unifamiliares, townhouses y condominios o apartamentos de poca altura (source: City of Doral Comprehensive Plan, https://www.cityofdoral.com/files/assets/city/v/1/departments/planning-and-zoning/land-use-docs/cdmp-part-i-gops-2013-update.pdf)",
        "Al norte de Doral está Medley, al noreste Hialeah y al este Miami Springs (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
    ],
}
