# -*- coding: utf-8 -*-
"""Hialeah: copia en español."""
ZONA = {
    "key": "hialeah",
    "title": "Hialeah y sus abejas: remoción en vivo cuadra a cuadra",
    "desc": "Remoción de abejas en Hialeah: panales en contadores de agua, muros de bloque, aleros y tejas, con reparación. Teléfono 24/7 y cotización gratis.",
    "h1": "Remoción de abejas en Hialeah, de Palm Avenue al canal",
    "kicker": "Hialeah, cuadra por cuadra",
    "lede": "En una ciudad tan apretada como Hialeah, un enjambre en el patio de al lado es asunto de toda la cuadra. Las abejas salen vivas y terminan en manos de apicultores.",
    "quick": "Si tiene abejas en Hialeah, toque el botón de llamada sin mirar el reloj: alguien contesta de día y de noche, su caso tiene respuesta garantizada antes de 24 horas y, si ya hubo picaduras, se adelanta. Un técnico ubica la colonia, con cámara térmica si está escondida, saca abejas y panal sin veneno y las entrega a apicultores. A nivel del suelo el trabajo ronda $300–$400; abrir y reparar una pared o un techo cuesta más.",
    "glance": [
        ("Incorporación", "10 de septiembre de 1925"),
        ("Población (2020)", "223,109 habitantes, sexta ciudad de Florida"),
        ("Densidad", "Cerca de 10,338 personas por milla cuadrada"),
        ("Calles", "Cuadrícula propia, numerada aparte del resto del condado"),
        ("Vecinos", "Miami Lakes, Hialeah Gardens, Medley, Miami Springs y Miami"),
    ],
    "opening": "Hialeah creció sobre una pradera abierta. Glenn Curtiss y James H. Bright trazaron el primer plano en 1921, y cuando la ciudad se incorporó, el 10 de septiembre de 1925, apenas tenía unos 1,500 habitantes. El censo de 2020 contó 223,109, lo que la convierte en la sexta ciudad de Florida, con alrededor de 10,338 personas por milla cuadrada.\n\nEsa densidad cambia la forma de atender abejas. Un enjambre colgado de una cerca no afecta solo a un patio: queda a pocos pasos de la puerta del vecino, de la acera por donde pasan los niños y de los carros estacionados en la entrada. Por eso, al recibir una llamada desde Hialeah, lo primero es precisar dónde está la colonia y quién comparte ese espacio. Luego se saca todo, abejas y panal, sin insecticida.\n\nUn detalle práctico: Hialeah tiene su propia cuadrícula de calles, con una numeración distinta a la del resto del condado. Al pedir el servicio, dé la dirección tal como sale en su factura del agua, con su East o su West, para que no se confunda con una calle del mismo número en otra parte.",
    "hotspots_h": "Los huecos que una colonia aprovecha en Hialeah",
    "hotspots": [
        ("Cajas del contador de agua", "La tapa del contador, al borde de la acera, cubre un hueco oscuro y seco que a una colonia le alcanza. Para la abeja africanizada, según material de extensión de la UF, un espacio de ese tamaño es suficiente. Si ve abejas entrando por la ranura de la tapa, no la levante; vea [[es:svc-contador-de-agua|abejas en el contador de agua]]."),
        ("Muros de bloque", "Las casas de posguerra del condado se reconocen por sus ventanas de celosía y, a veces, por un muro de bloque calado en el portal. En cualquier pared de bloque de concreto, las celdas huecas dejan espacio para que una colonia crezca, mientras desde afuera solo se nota una fila de abejas entrando por una grieta."),
        ("Aleros, plafones y tejas", "Entre el plafón del alero y la viga, o debajo de una teja floja, el panal queda a la sombra y protegido de los aguaceros. Desde la calle se ve un ir y venir constante en el mismo punto. Lo que implica abrir un plafón o levantar tejas está explicado en [[es:svc-abejas-en-techos|abejas en techos y tejas]]."),
        ("Llantas viejas, parrillas y tanques", "En patios traseros y en terrenos de almacenes, una llanta abandonada, una parrilla que nadie usa o un tanque vacío son una cavidad lista para ocupar. La misma fuente universitaria menciona llantas y parrillas entre los sitios que eligen las abejas africanizadas."),
    ],
    "band": ("Una cuadra llena de gente, un enjambre a la vez", "Las abejas se van vivas con un apicultor y el hueco queda cerrado para que otra colonia no lo ocupe."),
    "streets_h": "Hialeah por sectores",
    "streets": [
        ("Palm Avenue y el centro original", "Palm Avenue viene de los primeros años de la ciudad: su esquina con la antigua County Road, hoy la U.S. 27, ya aparece en una foto de 1921. En el 501 de Palm Avenue está hoy la División de Planificación y Zonificación. En las casas más antiguas conviene revisar primero aleros de madera y celosías."),
        ("Alrededores de Hialeah Park", "El hipódromo abarca 40 cuadras entre Palm Avenue y East 4th Avenue, de East 22nd a East 32nd Street, con jardines y un lago interior. La Sociedad Audubon lo declaró santuario del flamenco americano. Con tanto verde cerca, vale la pena mirar árboles y cercas de los patios que dan al parque."),
        ("Westland Mall y West 49th Street", "Westland Mall abrió en el verano de 1969 en el 1675 de West 49th Street y reúne más de cien tiendas. En los locales de ese corredor hay letreros huecos, cajas eléctricas y techos planos; para la administración de una plaza entregamos el comprobante de seguro (COI) que pidan."),
        ("El borde del Miami Canal", "Hacia el oeste, el Miami Canal marca el límite entre Medley y el par formado por Hialeah y [[es:zona-hialeah-gardens|Hialeah Gardens]]. La base fiscal de Medley es sobre todo industrial, y la propia Hialeah se volvió ciudad fabril con la manufactura y la industria textil de los años setenta y ochenta. Donde hay talleres, almacenes y patios de carga, una paleta apilada o un tanque viejo puede acabar convertido en colmena."),
        ("La U.S. 27 junto a Miami Springs", "La U.S. 27 corre paralela a la frontera con Miami Springs. A lo largo de ese corredor, en una casa o en un negocio, las abejas buscan los mismos escondites: cajas de válvulas, rejillas de ventilación y aleros."),
        ("El norte, frente a Amelia Earhart Park", "Justo al norte de la ciudad está Amelia Earhart Park, un parque del condado de 515 acres con lagos, senderos para bicicleta y la granja Bill Graham Farm Village. Un enjambre en busca de casa puede detenerse unas horas en una rama o una cerca de las cuadras vecinas antes de seguir viaje."),
    ],
    "body": [
        ("Casas de bloque y celosías: por qué la entrada es tan pequeña", "Las casas de posguerra del condado, de una planta, tipo ranch o de estilo tradicional sencillo, se caracterizan por las ventanas de celosía y, en algunos casos, por muros de bloque calado. En una pared de bloque de concreto, cada celda hueca es una cámara oscura que comunica con la de arriba o la de abajo. La entrada puede ser una grieta en la junta o el hueco de un tornillo, y el panal crece varios bloques más allá, donde nadie lo ve.\n\nRociar la grieta no resuelve nada: las abejas que quedan dentro mueren junto al panal, la cera se ablanda con el calor y la miel se escurre por la pared, atrayendo hormigas, cucarachas y otras abejas. Lo correcto es localizar la colonia, abrir solo lo necesario y sacar el panal completo. La cámara térmica ayuda a marcar el punto exacto antes de tocar la pared, y después nuestros propios contratistas con licencia cierran el bloque y lo dejan pintado. Si el problema está en un muro de su casa, lea la página de [[es:svc-abejas-en-paredes|abejas dentro de paredes]]."),
        ("Abejas africanizadas: a simple vista cuesta distinguirlas", "Según la Universidad de Florida, la abeja africanizada está presente en el estado, anida en espacios más pequeños que la europea, como cajas de contador, bloques de cemento, aleros y llantas, y defiende su nido en un radio mayor. Además, no es fácil diferenciarla de la abeja melífera europea con solo mirarla.\n\nEn una ciudad donde las casas están pegadas y la acera queda a pocos metros de cualquier contador, esa diferencia de radio pesa. Por eso toda colonia se trata con el mismo cuidado: se mantiene a la gente lejos, se trabaja con equipo completo y se evita molestar el nido antes de tener todo listo.\n\nSi una colonia ya está atacando, la recomendación de la universidad es correr, cubrirse la cabeza y la cara con la camisa y meterse en un carro o un edificio cerrado, sin quedarse a espantar abejas con las manos. Para esos casos está la línea de [[es:svc-emergencias|emergencias con abejas]], que se atiende de día y de noche."),
        ("Precio, seguro y papeles para negocios y condominios", "Una colonia a nivel del suelo, como la de un contador de agua o una caja de válvulas, suele costar entre $300 y $400. Subir al techo, abrir bloque o cambiar tejas es otra cosa: si hay que reparar, el total sube hasta los miles de dólares. Pedir la salida un sábado o a medianoche también sube el precio frente a un martes cualquiera. Cotizar no cuesta nada. Quien necesite comprobar el trabajo ante la junta o el seguro puede pedir las fotos y la factura con cada partida desglosada.\n\nMiami Bee Rescue trabaja con licencia y seguro. Si la junta del condominio, la HOA de su urbanización o el dueño de la nave industrial exige el COI, ese papel se envía antes de mover una sola herramienta. El desglose general de [[es:precios|precios]] del condado está en su propia página, y cualquier vecino de Hialeah puede usar el formulario para [[es:solicitar|solicitar servicio]]."),
    ],
    "visit_h": "Cómo es la visita en Hialeah",
    "visit": [
        ("Nos da la dirección completa", "Con la calle exacta, su East o West incluido, y una descripción de dónde ve el movimiento de abejas, preparamos la cotización sin costo y fijamos día y hora."),
        ("Se ubica la colonia", "El técnico sigue la línea de vuelo y, si el panal está oculto en un muro o en el techo, usa la cámara térmica para marcar el calor de la cría antes de abrir."),
        ("Remoción en vivo", "Las abejas y todo el panal salen sin insecticida. Las abejas viajan en una caja ventilada hasta los apicultores que las reciben, y la cera y la miel se retiran para no dejar olor."),
        ("Sellado y reparación", "La grieta se tapa. Bloque roto, plafón abierto o teja movida quedan a cargo de gente nuestra con licencia: contratistas, techadores, pintores. ¿Aparecen abejas otra vez justo donde cerramos? Ahí volvemos."),
    ],
    "alarm": "¿Alguien recibió varias picaduras o hay abejas persiguiendo gente en la acera? Entre a la casa o a un carro con las ventanas subidas, tápese el rostro con la ropa y no se quede manoteando. Aleje a niños y mascotas. Si alguien respira con dificultad, busque ayuda médica de inmediato; después llámenos: un caso con gente picada se atiende antes que cualquier otro en la lista.",
    "faqs": [
        ("¿Por qué piden la dirección con East o West en Hialeah?", "Porque Hialeah numera sus calles con una cuadrícula propia, distinta a la del resto del condado. Una misma cifra puede existir en Hialeah y en otra ciudad, o a ambos lados de la línea East y West. Con la dirección exacta, como figura en el recibo, el técnico llega a la casa correcta sin vueltas."),
        ("¿Atienden locales en plazas, almacenes o talleres?", "Sí. Locales en corredores comerciales, almacenes cerca del canal y talleres reciben el mismo servicio que una casa. Entregamos el comprobante de seguro (COI) que pida la administración y, si hace falta trabajar de noche o en fin de semana para no cerrar el negocio, se coordina, sabiendo que ese horario cuesta más."),
        ("¿Es peligroso un panal dentro del contador de agua?", "Puede serlo. Las abejas africanizadas aceptan cavidades pequeñas como esa y defienden un área amplia, y el contador queda justo junto a la acera. No levante la tapa ni eche agua o veneno. Mantenga a niños y mascotas lejos y pida la remoción; suele ser un trabajo a nivel del suelo."),
        ("¿Las abejas se mueren cuando las sacan?", "No. La remoción es en vivo: se capturan las abejas con su panal y se llevan a apicultores que las mantienen en colmenas. Nunca se fumigan ni se exterminan, ni siquiera cuando la colonia está dentro de una pared o debajo de las tejas."),
        ("¿Qué pasa si vuelven abejas al mismo lugar?", "Al terminar se tapa el hueco por donde entraban. Cuando otra colonia intenta usar ese mismo hueco ya cerrado por nosotros, nos toca volver a atenderlo. Por eso importa sacar todo el panal y cerrar bien el bloque o el alero, y no limitarse a espantar la colonia."),
        ("¿Contestan de noche o un domingo?", "Sí. A cualquier hora hay alguien que contesta, y cada caso tiene respuesta garantizada antes de cumplirse 24 horas; con picaduras de por medio, se adelanta. Eso sí, salir un domingo o de madrugada tiene recargo frente a un día de semana. Si nadie corre peligro, quizás le convenga dejarlo para el lunes."),
    ],
    "servicios": [
        ("contador-de-agua", "La tapa del contador junto a la acera ofrece justo el hueco pequeño que la abeja africanizada acepta para anidar."),
        ("abejas-en-paredes", "Los muros de bloque y bloque calado de las casas de posguerra esconden colonias que solo se ven por una grieta."),
        ("abejas-en-techos", "Aleros con plafón y tejas flojas en casas de una planta dan sombra y refugio a un panal."),
        ("enjambres", "Un enjambre posado en una cerca o un árbol cerca de Hialeah Park o Amelia Earhart Park conviene recogerlo antes de que se meta en una pared."),
        ("emergencias", "Cuando hay picaduras en una cuadra con niños y vecinos cerca, la llamada pasa primero."),
    ],
    "cercanos": ["hialeah-gardens", "miami", "doral"],
    "close": ("¿Abejas en su cuadra de Hialeah?", "Mándenos la dirección con su East o West y le preparamos una cotización gratis para sacar las abejas vivas."),
    "card": "Hialeah: abejas en contadores de agua, muros de bloque calado y aleros de casas de posguerra. Remoción en vivo, reparación con contratistas propios y respuesta garantizada en 24 horas.",
    "facts": [
        "Hialeah se incorporó el 10 de septiembre de 1925 y está sobre una pradera amplia (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Glenn Curtiss y James H. Bright desarrollaron Hialeah en 1921; primer plano en 1921; 1,500 habitantes en 1925 (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Censo 2020: 223,109 habitantes; sexta ciudad de Florida; densidad cerca de 10,338 por milla cuadrada; vecinos Miami Lakes, Hialeah Gardens, Medley, Miami Springs y Miami (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Hialeah tiene su propia cuadrícula de calles, numerada aparte del resto del condado (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Foto de 1921 de la intersección de Palm Avenue y County Road (hoy U.S. 27) (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "La División de Planificación y Zonificación está en 501 Palm Avenue (source: https://www.hialeahfl.gov/182/Planning-Zoning)",
        "Hialeah Park ocupa 40 cuadras de Palm Avenue a East 4th Avenue y de East 22nd a East 32nd Street; santuario Audubon del flamenco americano; jardines y lago interior (source: https://en.wikipedia.org/wiki/Hialeah_Park_Race_Track)",
        "El Miami Canal forma el límite entre Medley y Hialeah/Hialeah Gardens; la base fiscal de Medley es mayormente industrial (source: https://en.wikipedia.org/wiki/Medley,_Florida)",
        "La manufactura y la industria textil hicieron de Hialeah una ciudad industrial en los años setenta y ochenta (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "La U.S. 27 corre paralela a la frontera entre Miami Springs y Hialeah (source: https://en.wikipedia.org/wiki/Miami_Springs,_Florida)",
        "Westland Mall: 1675 West 49th Street, abrió en el verano de 1969, más de 100 tiendas (source: https://en.wikipedia.org/wiki/Westland_Mall_(Florida))",
        "Amelia Earhart Park: parque del condado de 515 acres justo al norte de Hialeah, con lagos, senderos para bicicleta y Bill Graham Farm Village (source: https://en.wikipedia.org/wiki/Amelia_Earhart_Park)",
        "Casas de posguerra en Miami-Dade con ventanas de celosía y muros de bloque calado (source: https://www.miamidade.gov/global/economy/historic-preservation/county-architectural-history.page)",
        "Abejas africanizadas: anidan en cavidades pequeñas (contadores de agua, bloques, llantas, aleros, parrillas), defienden un radio mayor, presentes en Florida, difíciles de distinguir; correr, cubrirse la cabeza, refugiarse y no manotear (source: https://ask.ifas.ufl.edu/publication/IN790)",
    ],
}
