# -*- coding: utf-8 -*-
"""Hialeah Gardens: copia en español."""

ZONA = {
    "key": "hialeah-gardens",
    "title": "Abejas en aleros y bloques de Hialeah Gardens",
    "desc": "¿Colonia en un sofito, un galpón o una tapa de contador de Hialeah Gardens? Un apicultor la saca viva, se cierra la junta y se repara. Cotización gratis.",
    "h1": "Remoción de abejas en Hialeah Gardens",
    "kicker": "Casas de un piso, galpones y canal",
    "lede": "En Hialeah Gardens casi todo se construyó a un solo nivel, y eso deja las colonias de abejas a la altura de la mano: aleros bajos, bloques huecos, cajas de contador y patios de almacén. Salen vivas y el hueco queda cerrado.",
    "quick": "Si ve abejas entrando y saliendo por una grieta de su casa, su galpón o la tapa del contador en Hialeah Gardens, no rocíe veneno ni tape el agujero: la colonia quedaría encerrada o moriría dentro del muro. Llame o use el botón de foto por texto. Su llamada tiene respuesta garantizada antes de que pasen 24 horas, a cualquier hora que marque, y quien ya lleva picaduras se pone al frente de la lista. Un apicultor se lleva la colonia viva y la entrada se sella.",
    "alarm": "¿Alguien recibió varias picaduras, hay un racimo de abejas sobre un niño o una mascota, o entraron a la casa? Aléjese, cierre puertas y ventanas y llame ahora mismo: los casos con picaduras van primero. Si la persona es alérgica, tiene la cara hinchada o le cuesta respirar, marque 911 antes que cualquier otra cosa.",
    "glance": [
        ("Tipo de lugar", "Ciudad de Miami-Dade, incorporada el 1 de diciembre de 1948"),
        ("Población", "23,068 habitantes en el censo de 2020"),
        ("Superficie", "3.67 millas cuadradas, de ellas 0.45 de agua"),
        ("Colindancias", "Hialeah al norte y al este; Medley al suroeste"),
        ("Vías clave", "US 27 por el oeste y NW 103rd Street en el sur"),
    ],
    "opening": "Hialeah Gardens nació en diciembre de 1948, cuando 26 votos unánimes convirtieron en pueblo lo que había comenzado como el campamento turístico de Walter C. Ohlerts. Hasta 1968 la cría de caballos fue una de sus actividades principales; ese año un plan maestro de uso del suelo y zonificación cambió el rumbo, y la cercanía a la US 27 y al Palmetto Expressway la convirtió en uno de los municipios de crecimiento más rápido del condado. Hoy es una ciudad casi entera de un solo piso, donde los barrios residenciales conviven con talleres, depósitos y patios de camiones.\n\nPara una colonia de abejas, esa mezcla ofrece refugio por todas partes: sofitos de casas bajas, celdas de bloque de concreto, naves de lámina, tarimas apiladas y cajas de contador junto a la acera. Un enjambre que elige uno de esos huecos empieza a levantar panal enseguida. Lo sensato es dejar la entrada abierta, no fumigar y pedir una [[es:svc-remocion-sin-matarlas|remoción sin matarlas]], para que las abejas terminen en manos de un apicultor y no podridas detrás del estuco.",
    "hotspots_h": "Dónde anidan las abejas en Hialeah Gardens",
    "hotspots": [
        ("Aleros de casas de un piso", "Con viviendas de un solo nivel, el alero queda bajo y la entrada de la colonia casi siempre se ve desde el patio: una rendija entre el sofito y la fascia o un respiradero sin malla. Detrás, el panal puede avanzar hacia el ático durante semanas sin que nadie lo sospeche."),
        ("Galpones y depósitos del noroeste", "La zona industrial tiene naves de lámina, empresas de techado y patios con materiales de construcción. Las abejas aprovechan paneles mal ajustados, cajas eléctricas en desuso, tarimas amontonadas y rollos de material guardados a la intemperie, así que hay que coordinar con el encargado del lote."),
        ("Remolques y camiones parados", "Un remolque que lleva semanas sin moverse en un lote de venta o un patio de mudanzas es una cavidad seca y oscura. Antes de engancharlo, revise compartimentos laterales, cajas de herramientas y el espacio bajo el chasis para no salir a la carretera con una colonia a bordo."),
        ("Tapas de contador y válvulas", "La tapa plástica a ras del suelo protege un espacio fresco que a las abejas les resulta perfecto. Quien lee el contador o pasa la cortadora de grama es el que recibe las picaduras. Ese hueco se vacía, se limpia y la tapa vuelve a quedar ajustada."),
        ("Muros de bloque hueco", "Las construcciones de bloque de concreto tienen celdas verticales por dentro. Si las abejas entran por una fisura del estuco, el panal puede bajar por esas celdas. La cámara térmica muestra hasta dónde llega el nido antes de picar la pared."),
    ],
    "band": ("¿Zumbido en el alero o en el contador?", "Un rincón que zumba junto al canal o dentro del galpón merece una llamada hoy, con respuesta garantizada en 24 horas."),
    "streets_h": "Norte, noroeste, centro y sur: cómo varía el trabajo",
    "streets": [
        ("Distrito norte", "Casas unifamiliares de densidad baja a moderada y terrenos de tipo finca. Con más árboles, cercas y cobertizos en el fondo, la colonia puede estar en un depósito de herramientas, un tronco hueco o bajo una losa, y no necesariamente en la vivienda."),
        ("Zona industrial del noroeste", "Empresas de envío y mudanza, cementeras, techadores, constructoras, venta de camiones y remolques y algo de manufactura de alimentos. Si hay empleados y clientes alrededor, se acordona el área de trabajo y se entrega el comprobante de seguro que pida la administración."),
        ("Centro de la ciudad", "Vivienda de densidad moderada y media mezclada con negocios. Donde dos unidades comparten un muro, una colonia en esa pared afecta a ambas, y conviene que los dos vecinos o los dos locales estén enterados antes de abrir."),
        ("Distrito sur y NW 103rd Street", "El sur combina residencial de alta densidad, comercio e industria, y la NW 103rd Street lo atraviesa de este a oeste. En propiedades con asociación o administradora, la visita se programa con ellos y se deja el COI que soliciten."),
        ("Corredor de la US 27", "La US 27 forma casi todo el borde oeste y tiene una vía de servicio paralela; la mayor parte del comercio queda del lado este. Letreros iluminados, techos planos y equipos de aire acondicionado en azoteas son puntos que merecen una mirada."),
        ("Orilla del Canal de Miami", "El canal marca la frontera con Medley. Con agua tan a mano, las abejas no necesitan volar lejos para beber, y las propiedades cercanas pueden ver enjambres de paso durante la temporada de primavera."),
    ],
    "body": [
        ("Por qué fumigar o tapar el hueco empeora el problema", "El impulso natural es rociar insecticida o sellar la grieta con espuma. Las dos cosas salen caras. Si la colonia muere dentro del muro, quedan kilos de panal, cría muerta y miel sin nadie que la ventile. En pleno verano miamense el panal abandonado se reblandece y su miel se filtra entre las celdas del bloque, deja cercos en el yeso y llama a hormigas, cucarachas y a la polilla que se alimenta de panal abandonado. El olor dura semanas.\n\nTapar la entrada con las abejas adentro tampoco funciona: buscan otra salida y a veces la encuentran por un tomacorriente, una lámpara o el marco de una ventana, ya dentro de la casa. Por eso el trabajo es sacar la colonia completa, viva, junto con todo el panal y la miel, y solo entonces cerrar. Aquí no se mata ninguna colonia; todas se reubican con apicultores dispuestos a criarlas. Si quiere entender el método antes de llamar, la página de [[es:svc-abejas-en-paredes|abejas dentro de paredes]] lo explica paso a paso."),
        ("Casas bajas: escalera corta, pero hay que abrir", "Que la casa sea de un piso facilita el acceso, pero no evita abrir. El panal no se queda en la boca del hueco; crece hacia dentro, entre vigas, dentro del sofito o a lo largo de las celdas del bloque. Antes de cortar se recorre la zona con cámara térmica, porque la colonia mantiene su nido más caliente que el resto de la pared y la imagen marca dónde termina.\n\nCon eso se abre una sola sección, se recogen las abejas, se saca el panal en piezas y se limpia la miel que quedó en la cavidad. Después, techadores, pintores y contratistas con licencia que forman parte de la propia empresa cierran la entrada y rehacen el sofito, el estuco o las tejas que hubo que mover. Quien lo solicite recibe imágenes de cada etapa y una factura con cada partida desglosada, algo práctico para el seguro de la vivienda o para el propietario si usted alquila."),
        ("Almacenes, locales y asociaciones", "Buena parte de los edificios que no son viviendas en Hialeah Gardens son almacenes y talleres. Ahí el reto es trabajar sin parar la operación: se acuerda un horario, se aparta al personal del área y se mueve lo mínimo. El trabajo lo hace un equipo con licencia y asegurado, y para HOAs, condominios y negocios se entrega el comprobante de seguro (COI) que pidan antes de empezar.\n\nSi la colonia está en una nave de lámina o en una azotea, hace falta equipo para llegar y luego rehacer el panel o la cubierta, y eso pesa en la cuenta. Conviene avisar al encargado de mantenimiento con tiempo, para que despeje el acceso y nadie mueva tarimas ni encienda maquinaria junto al nido mientras se trabaja. En la [[es:precios|página de precios]] se explica qué hace subir o bajar una cotización."),
    ],
    "visit_h": "Así transcurre la visita, de la llamada al sellado",
    "visit": [
        ("Llamada o foto por texto", "Explique si el movimiento sale del alero, del bloque o del suelo, cuánto tiempo lleva así y si hubo picaduras. Con eso se arma la cotización gratis y se fija la cita; los casos con picaduras se adelantan."),
        ("Ubicar la colonia", "La cámara térmica busca el calor del nido detrás del estuco, el sofito o la lámina, para abrir justo donde está el panal y no a ciegas por media pared."),
        ("Sacar abejas y panal", "Se abre el punto exacto, se recogen las abejas vivas, se retira todo el panal con su miel y la colonia sale rumbo a un apicultor que la recibe."),
        ("Sellar y reparar", "Se cierra la junta por donde entraban y el equipo de reparación deja pared, alero o techo en orden. Ese cierre queda respaldado: si una colonia intenta colarse otra vez justo por ahí, el equipo vuelve."),
    ],
    "faqs": [
        ("Tengo un racimo de abejas en la cerca: ¿se marchará sin ayuda?", "Depende de lo que vea. Un racimo colgado de una rama, una cerca o un remolque está descansando mientras las exploradoras buscan casa, y a veces se marcha solo al cabo de uno o dos días. Pero si las abejas entran y salen de un hueco con orden, ya se instalaron y no van a irse: cada día suman panal. En ese caso conviene llamar; la página de [[es:svc-enjambres|enjambres de abejas]] explica la diferencia."),
        ("Mi casa es de un piso; ¿eso abarata el trabajo?", "Ayuda, porque casi todo se alcanza con escalera corta, pero lo que manda es cuánto hay que abrir y rehacer. Cuando el nido se saca desde el piso, sin romper nada, la cuenta suele moverse entre $300 y $400. Si el panal lleva meses ganando terreno dentro del bloque o bajo las tejas y toca reconstruir, el total puede sumar miles de dólares. Pedir la visita un sábado o de madrugada encarece la factura frente a la misma salida un martes por la mañana. La cotización es gratis."),
        ("¿Qué hacen con las abejas una vez que las sacan?", "Se trasladan vivas a apicultores que las reciben en cajas de colmena. No se fumigan ni se exterminan. Las abejas melíferas polinizan cultivos y jardines, y una colonia sana tiene valor para quien la cuida. El proceso completo está descrito en [[es:svc-remocion-sin-matarlas|remoción de abejas sin matarlas]]."),
        ("¿Y si otro enjambre vuelve al mismo hueco después?", "La cera vieja deja un aroma que atrae a enjambres nuevos, y por eso no queda ni un trozo de panal y la entrada se cierra. Cuando una colonia insiste justo en esa junta que ya cerramos, nos toca regresar a Hialeah Gardens para resolverlo. Por eso también vale la pena revisar que no queden respiraderos sin malla ni rendijas abiertas en otros aleros de la casa."),
        ("Mi negocio está en la zona industrial; ¿pueden trabajar sin cerrar?", "En la mayoría de los casos, sí, coordinando el horario con el encargado y apartando al personal del área. Trabajamos con licencia y póliza vigente, y si su administración o asociación exige el COI, se lo enviamos antes de la cita. Puede adelantar los datos en el [[es:solicitar|formulario de solicitud]]."),
    ],
    "servicios": [
        ("abejas-en-paredes", "Muros de bloque y estuco en casas de un piso, donde el panal baja por las celdas del bloque."),
        ("abejas-en-techos", "Aleros, sofitos y tejas a poca altura, más los techos de lámina de los galpones del noroeste."),
        ("contador-de-agua", "Tapas de contador y cajas de válvulas a ras de la grama frente a las casas y los locales."),
        ("enjambres", "Racimos colgados de cercas, árboles y remolques estacionados, sobre todo durante la primavera."),
        ("emergencias", "Varias picaduras o abejas dentro de la vivienda: se atienden primero, a cualquier hora del día o de la noche."),
    ],
    "cercanos": ["hialeah", "doral", "miami"],
    "close": ("Hialeah Gardens, sin abejas en la pared", "Pida su cotización gratis con el formulario o por teléfono, y deje el hueco tal como está hasta la visita."),
    "card": "Hialeah Gardens: casas de un piso, almacenes del noroeste y la orilla del Canal de Miami. Las abejas salen vivas, la entrada se sella y la reparación la hacen contratistas propios.",
    "facts": [
        "Hialeah Gardens es una ciudad del condado Miami-Dade; 23,068 habitantes en el censo de 2020 (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
        "Se incorporó el 1 de diciembre de 1948 con 26 votos unánimes; empezó en el Walter C. Ohlerts Tourist Camp (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
        "La cría de caballos fue una industria principal hasta el plan maestro de uso del suelo y zonificación de 1968; luego creció rápido, con la US 27 y el Palmetto Expressway cerca (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
        "Superficie total 3.67 millas cuadradas, 0.45 de agua; desarrollo mayormente de un piso (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
        "Colinda con Hialeah al norte y al este y con Medley al suroeste (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
        "El Canal de Miami forma la frontera entre Medley y Hialeah Gardens y Hialeah (source: https://en.wikipedia.org/wiki/Medley,_Florida)",
        "Distritos norte, noroeste, centro y sur; el noroeste es mayormente industrial (envío y mudanza, cemento, techado, construcción, venta de camiones y remolques, algo de manufactura de alimentos) (source: https://giscloud.fiu.edu/wp_etap_new/wp-content/uploads/2024/09/City-of-Hialeah-Gardens-CBR-TPO-Reviewed.pdf)",
        "La US 27 forma la mayor parte del límite oeste con una vía de servicio paralela; la mayoría del comercio está del lado este; la NW 103rd Street cruza el distrito sur de este a oeste (source: https://giscloud.fiu.edu/wp_etap_new/wp-content/uploads/2024/09/City-of-Hialeah-Gardens-CBR-TPO-Reviewed.pdf)",
    ],
}
