# -*- coding: utf-8 -*-
"""Homestead: copia en español."""

ZONA = {
    "key": "homestead",
    "title": "Abejas en Homestead: frutales, muros de oolita y aleros",
    "desc": "¿Abejas en un muro de roca coralina, el alero o el contador de agua en Homestead? Salen vivas, el hueco queda reparado y cotizar no le cuesta nada.",
    "h1": "Abejas en Homestead: de los mangos de Redland a su alero",
    "kicker": "Homestead y su borde agrícola",
    "lede": "En Homestead las abejas tienen de todo a mano: frutales, viveros, muros de piedra y casas levantadas después de 1992. Sacamos la colonia viva, la entregamos a un apicultor y dejamos el hueco cerrado.",
    "quick": "Con los huertos de mango y aguacate de Redland justo al noroeste, Homestead recibe enjambres cada vez que hay floración. Cuando las abejas entran y salen siempre por el mismo punto de su casa, casi seguro ya hay panal adentro. No lo selle ni lo rocíe: con la salida tapada, la colonia busca otra ruta, a veces hacia la sala. El teléfono se atiende 24/7 con respuesta garantizada en 24 horas. Un apicultor adopta las abejas, que nunca se exterminan, y nuestros propios contratistas cierran la abertura.",
    "glance": [
        ("Incorporada", "8 de febrero de 1913"),
        ("Población (censo 2020)", "80,737 habitantes"),
        ("Altura", "Unos 3 pies sobre el nivel del mar"),
        ("Distancia", "Unas 26 millas desde el centro de Miami, rumbo suroeste"),
        ("Entre dos parques", "Biscayne al este, Everglades al oeste"),
    ],
    "opening": "Homestead es la ciudad grande del extremo sur del condado: queda a unas 26 millas al suroeste del centro de Miami, con el Parque Nacional Biscayne hacia el este y el Parque Nacional Everglades hacia el oeste. Esa ubicación tiene mucho que ver con las abejas. Al noroeste empieza Redland, una zona agrícola no incorporada con aguacates, mangos, lichis y viveros de plantas ornamentales. Cuando hay floración, la comida sobra; una colonia bien alimentada crece, se divide y manda un enjambre a buscar casa nueva, que a veces termina a pocas cuadras, dentro de un barrio residencial.\n\nLa otra mitad de la historia está en las viviendas. El huracán Andrew tocó tierra por segunda vez justo al noreste de Homestead el 24 de agosto de 1992 y destruyó casi todas las casas móviles de la ciudad. Lo que se reparó o se levantó después, junto con todo lo construido en los años siguientes, ofrece aleros, plafones ventilados, tejas y cámaras huecas donde un enjambre puede instalarse sin que nadie lo note por semanas.",
    "hotspots_h": "Huecos que atraen colonias en Homestead",
    "hotspots": [
        ("Muros de roca coralina",
         "Redland, justo al noroeste de la ciudad, es tierra de muros de roca coralina (oolita). Entre piedra y piedra quedan grietas y cavidades profundas, y a un enjambre le basta una rendija estrecha para entrar. Antes de mover una sola piedra, la cámara térmica marca dónde se concentra el calor del racimo, así el muro no se desarma a ciegas."),
        ("Aleros y plafones ventilados",
         "El plafón bajo el alero es una puerta abierta: las abejas pasan por la rejilla o por una junta suelta y arman el panal entre las vigas del techo. Desde el patio solo se ve un ir y venir constante cerca del borde, pero arriba puede haber varios pies de cera cargada de miel."),
        ("Tapas del medidor y del riego",
         "En los patios de Homestead, las cajas del contador y de las válvulas quedan a ras del césped, oscuras, secas y protegidas de la lluvia. Una colonia ahí adentro sorprende a quien levanta la tapa o pasa la cortadora cerca. Mantenga a niños y mascotas lejos de esa caja hasta que las abejas salgan."),
        ("Ramas de mango y aguacate",
         "Un enjambre de primavera puede descansar horas o un par de días colgado de una rama de frutal, de una cerca o de una planta en maceta mientras las exploradoras eligen un hueco definitivo. Todavía no tiene panal que defender, así que ese es el momento ideal para recogerlo antes de que entre a una pared."),
        ("Fachadas del centro histórico",
         "Sobre Krome Avenue, el distrito histórico reúne edificios de otra época, entre ellos el teatro abierto en 1921 y rediseñado en estilo Streamline Moderne tras un incendio en 1940. Cornisas, parapetos y ductos de ventilación en construcciones antiguas dan buen refugio a una colonia, y desde la acera rara vez se ve dónde empieza el panal."),
    ],
    "band": ("¿Zumbido dentro de la pared? No la rocíe",
             "El veneno deja el panal adentro, la miel se derrite con el calor del verano y aparece una mancha pegajosa. Llame antes de tocar nada."),
    "streets_h": "Sectores de Homestead donde trabajamos",
    "streets": [
        ("Centro histórico y Krome Avenue",
         "Krome Avenue (State Road 997) atraviesa el centro histórico, designado distrito histórico el 19 de noviembre de 2007. Cuando dos locales contiguos comparten una pared y una colonia ocupa el hueco entre ambos, confirmamos con la cámara térmica de qué lado está antes de abrir."),
        ("Waterstone (Distrito 5)",
         "El Distrito 5 del concejo municipal lleva el nombre de Waterstone, y Waterstone Blvd pasa por dentro de él. En calles residenciales como estas, las abejas buscan aleros con rejilla, techos de tejas y cajas de válvulas en el jardín."),
        ("Villages (Distrito 3)",
         "Si su comunidad en el Distrito 3, conocido como Villages, tiene asociación de propietarios o administración, le enviamos el comprobante de seguro (COI) que pidan y acordamos el acceso a áreas comunes antes de empezar."),
        ("Sector suroeste y SW 6th Street",
         "En el vecindario del suroeste, la iniciativa New H.O.M.E. de la agencia de redesarrollo (CRA) de la ciudad respalda casas asequibles nuevas sobre SW 6th Street. Una casa recién estrenada también puede recibir un enjambre: alcanza con una rejilla sin malla o una junta abierta."),
        ("Borde con Redland",
         "Al noroeste, Redland queda casi por completo fuera del límite de desarrollo urbano, donde la zonificación exige al menos 5 acres por casa. En terrenos así hay cobertizos, cercas, frutales y muros de piedra, y encontrar la colonia puede significar recorrer la finca con la cámara térmica."),
        ("Límite con Florida City",
         "Florida City colinda con Homestead por el sur y el oeste, y en la calle casi no se nota dónde termina una y empieza la otra. Atendemos ambos lados por igual; más al sur está la línea del condado, y allí ya no trabajamos."),
    ],
    "body": [
        ("Por qué una colonia no se va sola de su casa",
         "Un enjambre recién llegado todavía puede seguir de largo, pero cuando las abejas ya construyeron panal, se quedan. Detrás del panel de yeso o bajo las tejas, la colonia guarda miel, cría y polen, y cada semana suma cera. Envenenarla mata a las obreras pero no saca nada: en pleno agosto la cera cede, la miel se cuela entre el yeso, llegan hormigas y polillas, y ese aroma invita a un enjambre nuevo a ocupar la cavidad vacía.\n\nPor eso trabajamos con [[es:svc-remocion-sin-matarlas|remoción sin matarlas]] y sacando todo el panal. La colonia viaja viva en una caja de colmena hasta un apicultor que la adopta; después raspamos cada resto de cera, lavamos el hueco y lo clausuramos. ¿Aparecen abejas otra vez justo en el parche que tapamos? Ese regreso corre por nuestra cuenta."),
        ("Techos bajo las reglas de huracanes",
         "Para el Código de Construcción de Florida, Miami-Dade entera cae en la zona de vientos huracanados más estricta del estado (High-Velocity Hurricane Zone), y en Homestead, después de Andrew, buena parte de las casas dañadas se repararon o se reconstruyeron. Cuando una colonia vive bajo las tejas o dentro del plafón, abrir y cerrar el techo no es un detalle menor.\n\nLevantamos solo las tejas o el tramo de plafón necesario, sacamos el panal entero y la reparación la hacen nuestros propios techadores con licencia; si hay que retocar la pintura del alero, se encargan nuestros pintores. Así usted no tiene que buscar un segundo contratista cuando las abejas ya se fueron. Si quiere conocer el procedimiento completo para cubiertas, abra [[es:svc-abejas-en-techos|nuestra guía de techos y tejas]]."),
        ("Lo que mueve el precio en una propiedad de Homestead",
         "Para darle una idea: si la colonia se alcanza parado en el piso, por ejemplo dentro del medidor o posada en un mango joven, la cuenta ronda $300 a $400. Desmontar tejas, abrir panel de yeso o rearmar un muro de oolita cambia la escala, y sumando la reparación la factura puede llegar a miles de dólares.\n\nInfluye además la hora: atender un llamado nocturno o en sábado o domingo sale más caro que agendar para un martes cualquiera. Cotizar no le cuesta nada, y para el expediente de su seguro o de la junta de su comunidad le pasamos fotos y una factura con cada partida. Consulte la [[es:precios|página de precios]] o pida la visita desde [[es:solicitar|solicitar servicio]]."),
    ],
    "visit_h": "Cómo transcurre la visita en su casa o finca",
    "visit": [
        ("Llamada y primeras preguntas",
         "Por teléfono le preguntamos si las abejas salen de la tierra, de una pared o del techo, y qué tan cerca quedan de una entrada. Con picaduras de por medio, su caso se adelanta."),
        ("Búsqueda con cámara térmica",
         "Antes de cortar nada, ubicamos el calor del racimo detrás de la pared, del plafón o del muro de roca, para abrir únicamente donde está el panal y no dañar de más."),
        ("Remoción en vivo y limpieza",
         "Pasamos las abejas vivas a una caja de colmena junto con el panal de cría, retiramos toda la cera y la miel y limpiamos la cavidad para que el olor no llame a otra colonia."),
        ("Cierre y reparación final",
         "El hueco queda tapado y, según el caso, un techador, contratista o pintor de nuestro equipo, todos con licencia, termina el acabado. Si el zumbido reaparece ahí mismo, lo atendemos otra vez."),
    ],
    "alarm": "Hinchazón en la cara, falta de aire o mareo después de varias picaduras: eso se resuelve con el 911, de inmediato. Mientras llega la ayuda, camine rápido y en línea recta hasta un lugar cerrado, sin manotear, y meta a niños y mascotas en la casa, ya sea en un patio de Homestead o entre los frutales de una finca. Cuando una llamada trae picaduras, pasa al frente de nuestra fila a cualquier hora.",
    "faqs": [
        ("¿Puedo acercarme a un enjambre que cuelga del mango del patio?",
         "Un enjambre en una rama suele estar tranquilo porque todavía no tiene panal ni cría que proteger. Aun así, no le tire agua, piedras ni insecticida, y mantenga a la gente a varios pasos. Conviene recogerlo antes de que se mude a una pared o al techo; vea nuestra página de [[es:svc-enjambres|enjambres de abejas]]."),
        ("¿Pueden vivir abejas dentro de un muro de roca coralina?",
         "Sí. La roca coralina es porosa e irregular, y las juntas entre piedras pueden dejar espacios donde cabe un panal completo. Con la cámara térmica ubicamos la colonia, retiramos solo las piedras necesarias y nuestros propios contratistas con licencia vuelven a cerrar el muro."),
        ("¿Atienden las fincas de Redland y las casas de Florida City?",
         "Sí, las dos zonas están dentro de Miami-Dade y las cubrimos igual que el resto de Homestead. Hacia el norte también trabajamos en [[es:zona-kendall|Kendall]] y en todo el condado. Lo único que queda fuera es lo que está más allá de la línea del condado."),
        ("¿Le echo veneno a la caja del contador antes de que ustedes vengan?",
         "Deje la tapa cerrada y el aerosol guardado. Un insecticida solo alcanza a parte de las abejas, pone a la defensiva a las que quedan y deja cera y miel descomponiéndose bajo el césped, un olor que llama a hormigas y a un enjambre nuevo. Los detalles de ese caso están en [[es:svc-contador-de-agua|el servicio para medidores y cajas de válvulas]]."),
        ("¿Adónde van a parar las abejas de mi finca o mi patio?",
         "Nunca se exterminan. Salen vivas en una caja de colmena, cría incluida, y se reubican con apicultores que las reciben y las cuidan. Una colonia sana sigue polinizando allí donde el apicultor la instale, lejos de su casa."),
        ("¿Qué documentos necesita mi asociación para autorizar el trabajo?",
         "Trabajamos con licencia y póliza vigente. La administración puede pedirnos el COI, o comprobante de seguro, antes de autorizar la entrada a áreas comunes, y si quieren documentar el caso les entregamos imágenes de cada etapa y una factura desglosada por partidas."),
    ],
    "servicios": [
        ("enjambres", "Con huertos y viveros a un paso, los enjambres de primavera se posan en ramas y cercas; conviene recogerlos antes de que entren a una casa."),
        ("contador-de-agua", "Bajo una tapa de plástico en el césped, el medidor ofrece sombra, poca humedad y una sola entrada: justo lo que una colonia busca."),
        ("abejas-en-techos", "Tejas, aleros y plafones de casas reparadas o levantadas después de 1992; el cierre lo hacen nuestros techadores con licencia."),
        ("abejas-en-paredes", "Paredes huecas y muros de roca coralina: la cámara térmica indica dónde está el panal para abrir lo mínimo."),
        ("emergencias", "Si hubo picaduras, si entraron abejas a la sala o el panal está pegado a la puerta, su llamada se adelanta, a cualquier hora."),
    ],
    "cercanos": ["kendall", "west-kendall", "miami"],
    "close": ("Abejas en Homestead: llame antes de rociar",
              "Teléfono atendido 24/7, respuesta garantizada en 24 horas y cotización gratis para su casa, su finca o su negocio."),
    "card": "Homestead, entre los huertos de Redland y las casas reconstruidas tras Andrew: enjambres en frutales, colonias en muros de roca coralina, contadores de agua y aleros.",
    "facts": [
        "Homestead se incorporó el 8 de febrero de 1913 (source: https://en.wikipedia.org/wiki/Homestead,_Florida)",
        "Censo 2020: 80,737 habitantes; altura de unos 3 pies; unas 26 millas al suroeste del centro de Miami; entre el Parque Nacional Biscayne al este y el Parque Nacional Everglades al oeste (source: https://en.wikipedia.org/wiki/Homestead,_Florida)",
        "Krome Avenue (State Road 997) atraviesa el centro histórico de Homestead (source: https://en.wikipedia.org/wiki/Homestead,_Florida)",
        "El huracán Andrew tocó tierra por segunda vez justo al noreste de Homestead el 24 de agosto de 1992 y destruyó el 99 por ciento de las casas móviles de la ciudad; casi dos años después, cerca del 70 por ciento de las casas dañadas o destruidas se habían reparado o reconstruido (source: https://en.wikipedia.org/wiki/Hurricane_Andrew)",
        "El distrito histórico del centro de Homestead fue designado el 19 de noviembre de 2007; su teatro abrió en 1921 y se rediseñó en estilo Streamline Moderne tras un incendio en 1940 (source: https://en.wikipedia.org/wiki/Homestead_Historic_Downtown_District)",
        "Florida City queda al sur y al oeste de Homestead y colinda con ella (source: https://en.wikipedia.org/wiki/Florida_City,_Florida)",
        "Redland, zona agrícola no incorporada al noroeste de Homestead, cultiva aguacates, mangos, lichis y plantas ornamentales; tiene muros de roca coralina (oolita); casi toda queda fuera del límite de desarrollo urbano, con lotes mínimos de 5 acres por casa (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Distritos del concejo: Distrito 3 Villages, Distrito 4 Southwest Area, Distrito 5 Waterstone; Waterstone Blvd cruza el Distrito 5 (source: https://www.homesteadfl.gov/DocumentCenter/View/4272/Council-Seat-Districts-Map-2023)",
        "La iniciativa New H.O.M.E. del CRA de Homestead para el vecindario del suroeste respalda casas asequibles nuevas sobre SW 6th Street (source: https://www.homesteadfl.gov/m/newsflash/Archive/Item/4012?arcId=5070)",
        "Miami-Dade está dentro de la Zona de Huracanes de Alta Velocidad del Código de Construcción de Florida (source: https://en.wikipedia.org/wiki/Florida_Building_Code)",
    ],
}
