# -*- coding: utf-8 -*-
"""Kendall: copia en español."""

ZONA = {
    "key": "kendall",
    "title": "Kendall: remoción de abejas vivas, panal y reparación",
    "desc": "Kendall, de la US 1 al Turnpike: colonias fuera de techos, paredes y contadores, vivas y rumbo a apicultores. Cotización gratis y línea abierta 24/7.",
    "h1": "Abejas en Kendall: remoción en vivo, de Dadeland al Turnpike",
    "kicker": "Zona no incorporada de Miami-Dade",
    "lede": "Entre la US 1 y el Turnpike viven más de ochenta mil personas, y cualquier alero, pared o contador puede convertirse en casa de un enjambre. Sacamos las abejas vivas, las llevamos con apicultores y cerramos la entrada.",
    "quick": "Sí, en Kendall se pueden sacar las abejas sin matarlas. Ubicamos la colonia con cámara térmica, retiramos el panal completo y las abejas pasan a manos de apicultores. Luego se cierra el hueco de entrada y, donde hubo que abrir, el arreglo lo termina nuestra propia gente: contratistas, techadores y pintores con licencia. Llame a la hora que sea; alguien contesta de día y de noche, le respondemos con garantía dentro de las 24 horas, y una casa donde ya hubo picaduras se atiende antes.",
    "glance": [
        ("Tipo de lugar", "Zona no incorporada y lugar designado por el censo"),
        ("Población 2020", "80,241 habitantes"),
        ("Superficie", "16.6 millas cuadradas"),
        ("Límites", "US 1 al este, Turnpike al oeste"),
        ("Origen del nombre", "Henry J. B. Kendall, directivo de una compañía de tierras"),
    ],
    "opening": "Kendall no es una ciudad. Es una zona no incorporada que el censo trata como lugar designado (CDP), así que no tiene alcaldía propia y la administra directamente el Condado Miami-Dade. El nombre viene de Henry John Broughton Kendall, directivo de la Florida Land and Mortgage Company, la empresa que compró estas tierras al estado en 1883. Hasta los años cincuenta casi todo era pinar de roca (pine rockland) con campos y arboledas; las urbanizaciones llegaron en esa década, y cuando el crecimiento se desplazó hacia el oeste en los setenta, ochenta y noventa, el nombre se fue con él. Por eso hoy mucha gente dice «Kendall» para hablar de lugares que quedan bastante más allá.\n\nEsta página trata del Kendall del censo, entre la US 1 y el Turnpike, con Pinecrest al este y Palmetto Bay al sureste. Si usted vive más al oeste, le conviene la página de [[es:zona-west-kendall|West Kendall]]. En cualquiera de los dos casos el trato a las abejas es idéntico: salen vivas y terminan con apicultores.",
    "hotspots_h": "Escondites frecuentes de las colonias en Kendall",
    "hotspots": [
        ("Aleros y techos de casas de un piso", "Muchas viviendas de Kendall se levantaron a partir de los años cincuenta, y otras se repararon o rehicieron tras el huracán Andrew. Donde una teja quedó floja o un alero tiene una rendija, un enjambre encuentra un hueco seco y oscuro para armar su panal."),
        ("Tapas de contador en el jardín delantero", "Una caja enterrada cerca de la acera, con una tapa que tiene ranura o grieta, es justo el tipo de cavidad que busca un enjambre. Alguien la levanta para leer el contador y se topa con el panal. Si le pasa, vuelva a dejar la tapa en su sitio, aleje a los niños y llámenos."),
        ("Locales y oficinas cerca de Dadeland", "Alrededor de Dadeland Mall y The Falls hay plazas comerciales, oficinas y edificios de condominios. Las abejas se meten en letreros, columnas huecas y techos planos, y la administración normalmente exige ver la póliza en forma de COI antes de dejar pasar a nadie; la mandamos a nombre del edificio."),
        ("Patios con árboles grandes y canales", "El Snapper Creek y su canal atraviesan Kendall, y los patios con árboles grandes ofrecen ramas y troncos donde un enjambre se posa a descansar. Mientras solo cuelga, puede seguir su camino; si empieza a construir panal, conviene actuar antes de que crezca."),
    ],
    "band": ("¿Oye un zumbido dentro de la pared?", "Una foto por texto nos ayuda a preparar la visita; la cotización no cuesta nada y la línea contesta a toda hora."),
    "streets_h": "Sectores de Kendall donde trabajamos",
    "streets": [
        ("Dadeland y Kendall Drive", "Kendall Drive es la SW 88th Street, la ruta estatal 94, y pasa frente a Dadeland Mall, que abrió en 1962 entre la US 1 y el Palmetto Expressway. Aquí se mezclan casas, apartamentos y comercios, y coordinamos la entrada con cada administración o asociación."),
        ("Alrededores de Baptist Hospital", "Al sur de Kendall Drive queda Baptist Hospital of Miami, rodeado de consultorios y calles residenciales. Si hay pacientes, niños pequeños o personas alérgicas cerca del panal, díganoslo al llamar para tomar precauciones adicionales durante la remoción."),
        ("Estaciones Dadeland North y Dadeland South", "Las dos estaciones de Metrorail quedan junto al centro comercial; Dadeland South, abierta en 1984 al lado de la US 1, es la última parada del sur. Los edificios cercanos tienen cuartos eléctricos y cajas de servicio donde puede instalarse una colonia."),
        ("Zona de Killian", "Alrededor de Miami Killian Senior High, en la SW 97th Avenue, hay calles de casas con patio, cercas y cobertizos. Si las abejas aparecen cerca de una parada de autobús escolar o de un área de juegos, avísenos; con picaduras de por medio, su caso va primero."),
        ("Kendall Indian Hammocks Park y sus vecinos", "Este parque del condado guarda una reserva natural de 32 acres. Las abejas del bosque se quedan donde están; lo que atendemos es cuando una colonia se muda a una casa vecina, a un muro o al techo de un cobertizo."),
    ],
    "body": [
        ("Techos reconstruidos después de Andrew y las abejas", "En agosto de 1992 el huracán Andrew golpeó con fuerza a Kendall y al resto del sur del condado; muchas casas y negocios quedaron destruidos. Lo que se reconstruyó después convive hoy con techos, aleros y ampliaciones de distintas épocas. Para una colonia de abejas, cada unión entre materiales es una posible entrada: una teja que no asentó bien, un sofito con una junta abierta, un tubo de ventilación sin malla. Las abejas exploradoras revisan esos huecos en busca de un espacio seco y protegido, y cuando lo encuentran, el enjambre entero se muda detrás de ellas.\n\nPor eso no basta con sacar el panal que se ve. Con la cámara térmica medimos hasta dónde llega la colonia sin abrir más de lo necesario, retiramos todo el panal y la miel, limpiamos la cavidad y cerramos la entrada. Las tejas, el sofito o el drywall que haya que reponer quedan a cargo de techadores y pintores de nuestro propio equipo, todos con licencia. Cómo se abre y se vuelve a cerrar una cubierta lo contamos en [[es:svc-abejas-en-techos|abejas en techos y tejas]]."),
        ("Por qué no conviene fumigar ni tapar el hueco", "Tapar la entrada con espuma o rociar insecticida parece rápido, pero deja el problema adentro. Las abejas encerradas pueden abrirse paso por un enchufe o una lámpara hacia la sala, y el panal abandonado se ablanda con el calor, chorrea miel por la pared y atrae hormigas, cucarachas y nuevas abejas que detectan el olor de la cera. Además, matar una colonia de abejas melíferas que se puede reubicar no tiene sentido cuando hay apicultores dispuestos a recibirla.\n\nEn Kendall seguimos siempre el mismo orden: localizar, sacar vivas a las abejas, retirar el panal completo, limpiar, sellar y reparar. Y ese sellado no queda a la suerte: un punto cerrado por nosotros que vuelve a llenarse de abejas nos trae de vuelta a su casa. Y si le preocupa la cuenta, en la página de [[es:precios|precios]] verá que un trabajo a nivel del suelo ronda entre $300 y $400, mientras que los casos complejos con reparaciones pueden llegar a miles de dólares."),
        ("Edificios, HOAs y negocios en la zona", "Kendall tiene mucho más que casas: alrededor de Dadeland y a lo largo de Kendall Drive hay edificios de condominios, plazas comerciales, consultorios y oficinas. Las asociaciones de propietarios y los administradores normalmente piden papeles antes de dejar entrar a cualquier contratista. Trabajamos con licencia y póliza vigente; el COI sale con el nombre exacto que el administrador indique.\n\nSi la junta directiva quiere documentar el caso, le pasamos imágenes de cómo quedó cada etapa junto con una factura que desglosa cada partida. Un detalle sobre horarios: atender un llamado a medianoche o un domingo sale más caro que hacerlo un martes por la mañana, así que si el panal no molesta a nadie, esperar al horario normal le ahorra dinero."),
    ],
    "visit_h": "Así es la visita en Kendall",
    "visit": [
        ("Primero, una conversación", "Por teléfono o con una foto por texto, describa en qué parte de la propiedad entran y salen las abejas. Con eso preparamos el equipo; el precio final se confirma al ver el sitio."),
        ("Búsqueda con cámara térmica", "En el lugar revisamos la pared, el techo o la caja con la cámara térmica para ubicar el calor de la colonia y decidir por dónde abrir con el menor daño posible."),
        ("Remoción en vivo", "Primero salen las abejas, vivas; después cortamos cada lámina de cera, sacamos la miel y dejamos la cavidad limpia. La colonia no se fumiga; se traslada a un colmenar."),
        ("Sellado y reparación", "El hueco de entrada se cierra para que otro enjambre no lo aproveche, y gente de la propia empresa, con licencia de contratista, techador o pintor, deja la superficie como estaba. Fotos y factura detallada, si las pide."),
    ],
    "alarm": "¿Alguien en Kendall ya recibió picaduras, o las abejas salen en masa cerca de una puerta, una piscina o un patio con niños? Aléjese, cierre puertas y ventanas, y no rocíe nada ni intente tapar el hueco. Ante hinchazón fuerte de cara o garganta, o ahogo, el 911 va antes que nosotros. Luego marque nuestro número, que contesta a cualquier hora, y su caso con picaduras tendrá prioridad.",
    "faqs": [
        ("¿Kendall es una ciudad o parte del condado?", "Es parte del condado. Kendall es una zona no incorporada y un lugar designado por el censo, sin gobierno municipal propio. Para la remoción eso no cambia nada: trabajamos igual en cualquier casa o edificio entre la US 1 y el Turnpike, y también más al oeste, en [[es:zona-west-kendall|West Kendall]]."),
        ("¿Las abejas en el contador de agua se pueden sacar sin matarlas?", "Sí. Las colonias dentro de cajas a ras del suelo se retiran vivas igual que las de una pared: sacamos las abejas, cortamos el panal, limpiamos la caja y dejamos la tapa bien cerrada. Hay más detalles en [[es:svc-contador-de-agua|abejas en el contador de agua]]. Mientras tanto, no levante la tapa ni deje que los niños jueguen cerca."),
        ("Vi un enjambre colgado de una rama en mi patio, ¿qué hago?", "Mantenga la distancia y no le tire agua ni piedras. Un enjambre posado en una rama está descansando mientras sus exploradoras buscan casa, y a veces se va solo. Si empieza a construir panal, o si está junto a una puerta o una piscina, llámenos y lo recogemos vivo. Lea más en [[es:svc-enjambres|enjambres de abejas]]."),
        ("Mi asociación de Kendall pide seguro, ¿se lo pueden enviar?", "Sí. Tenemos licencia y seguro, y mandamos la constancia de seguro (COI) a la HOA, al condominio o al negocio que la necesite antes del trabajo. Si el administrador quiere fotos o una factura detallada para la junta, también las enviamos a pedido."),
        ("Sellaron el hueco y aparecieron abejas otra vez, ¿qué hago?", "Un punto que nosotros sellamos y que vuelve a tener abejas nos hace regresar; así respaldamos el trabajo. Para reducir esa posibilidad sacamos cada pedazo de cera y miel, porque su olor atrae a nuevos enjambres. Si nota actividad en otro lugar de la casa, mande una foto o pida una [[es:solicitar|cotización gratis]]."),
    ],
    "servicios": [
        ("abejas-en-techos", "Las tejas y aleros de Kendall, muchos rehechos después de Andrew, dejan rendijas donde una colonia se instala sin que nadie lo note."),
        ("abejas-en-paredes", "Cuando el zumbido sale del drywall o de un sofito, la cámara térmica marca dónde abrir, y luego nuestro equipo cierra y pinta."),
        ("contador-de-agua", "Una tapa partida junto a la acera basta para que una colonia convierta la caja del contador en colmena, con el riesgo de picar a quien la abra."),
        ("emergencias", "Una persona picada, abejas sueltas dentro de la sala o un enjambre sobre la piscina se atienden antes que todo lo demás, a cualquier hora."),
        ("remocion-sin-matarlas", "Ninguna colonia se extermina; todas terminan en manos de apicultores que las cuidan."),
    ],
    "cercanos": ["west-kendall", "westchester", "miami"],
    "close": ("Sus abejas, vivas y fuera de su casa", "Cuéntenos qué ve y dónde; preparamos una cotización gratis para cualquier punto de Kendall, desde Dadeland hasta el Turnpike."),
    "card": "De Dadeland a Killian y Snapper Creek: colonias sacadas con vida de aleros, sofitos y cajas de contador, y el hueco cerrado y reparado.",
    "facts": [
        "Kendall es una zona no incorporada y lugar designado por el censo en el Condado Miami-Dade; población de 80,241 en el censo de 2020 (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "El CDP de Kendall mide 16.6 millas cuadradas; la US 1 es el límite este y el Homestead Extension of the Turnpike el límite oeste; vecinos: Pinecrest (este), Palmetto Bay (sureste), The Crossings (oeste), Kendale Lakes (noroeste) (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "El nombre viene de Henry John Broughton Kendall, directivo de la Florida Land and Mortgage Company, que compró la tierra al estado en 1883 (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "Antes de los años cincuenta el área era pine rockland con campos y arboledas; se urbanizó en los cincuenta y el uso del nombre se desplazó al oeste en los setenta, ochenta y noventa (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "El huracán Andrew dañó gravemente Kendall y el sur del condado en agosto de 1992; muchas casas y negocios fueron destruidos (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "Dadeland es el área comercial de Kendall; The Falls es un centro comercial al aire libre al sur de Dadeland (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "Dadeland Mall abrió el 1 de octubre de 1962 entre la US 1 y el Palmetto Expressway; la estación Dadeland North de Metrorail está al lado y Dadeland South un poco al sur (source: https://en.wikipedia.org/wiki/Dadeland_Mall)",
        "Dadeland South es la terminal sur de Metrorail, abierta el 20 de mayo de 1984, junto a la US 1 (source: https://en.wikipedia.org/wiki/Dadeland_South_station)",
        "Kendall Drive es la SW 88th Street, señalizada mayormente como SR 94; Baptist Hospital of Miami queda al sur de la vía, que pasa por Dadeland Mall (source: https://en.wikipedia.org/wiki/Florida_State_Road_94)",
        "El Snapper Creek atraviesa Kendall y Coral Gables hasta la bahía de Biscayne; el Snapper Creek Canal se extiende unas 10 millas tierra adentro (source: https://en.wikipedia.org/wiki/Snapper_Creek)",
        "Miami Killian Senior High School, 10655 SW 97th Ave, en el CDP de Kendall, abrió en septiembre de 1965 (source: https://en.wikipedia.org/wiki/Miami_Killian_Senior_High_School)",
        "Kendall Indian Hammocks Park (Miami-Dade Parks) tiene una reserva natural de 32 acres (source: https://www.miamidade.gov/parks/kendall-indian-hammocks.asp)",
    ],
}
