# -*- coding: utf-8 -*-
"""Westchester: copia en español."""

ZONA = {
    "key": "westchester",
    "title": "Remoción de abejas en Westchester, Miami-Dade",
    "desc": "Westchester tiene casas de posguerra con aleros gastados que atraen colonias. Las abejas salen vivas hacia un apicultor y nuestros contratistas reparan.",
    "h1": "Remoción de abejas en Westchester",
    "kicker": "Entre Tamiami Trail y Bird Road",
    "lede": "Westchester creció a partir de 1955, y muchas de aquellas casas ya acumulan aleros resecos, rejillas flojas y tejas movidas. Por esas rendijas entra un enjambre; nosotros lo sacamos vivo y cerramos el paso.",
    "quick": "En Westchester la remoción de abejas se hace en vivo: ubicamos la colonia con cámara térmica, sacamos el panal completo y las abejas se van con un apicultor, sin exterminarlas. Cuando la colonia está al alcance de la mano, digamos dentro de una tapa del jardín o en un seto, el costo anda por unos $300–$400; con pared o techo abiertos y reparados después, la cuenta sube hasta miles de dólares. Puede llamar a cualquier hora, 24/7, y le garantizamos una respuesta en un plazo máximo de 24 horas.",
    "glance": [
        ("Tipo de lugar", "Área no incorporada (CDP) de Miami-Dade, no es ciudad"),
        ("Población en 2020", "56,384 habitantes"),
        ("Límites", "De la calle 8 a Bird Road; de la Palmetto a la 117 Avenue"),
        ("Origen del nombre", "Una subdivisión llamada Westchester, de 1955"),
        ("Residentes de 65+", "Casi uno de cada cuatro (23.2 por ciento)"),
    ],
    "alarm": "Si a alguien lo picaron varias veces, si las abejas ya andan por la cocina o el cuarto, o si un racimo tapa la puerta, aléjese y cierre puertas y ventanas. Ante dificultad para respirar o hinchazón en la cara, llame al 911 antes que nada. Hecho eso, marque nuestro número: quien tiene picaduras se adelanta a cualquier otra llamada, a la hora que sea.",
    "opening": "Antes de que los canales la secaran en los años veinte, esta tierra se inundaba con cada temporada de lluvias, y por eso ni siquiera calificaba para la Ley de Homestead de 1862. Todavía en 1950 la zona estaba casi vacía. La subdivisión que le dio nombre apareció en 1955, y durante los años sesenta se sumaron Miracle Manor, Mirador, Westchester Park, Town Park y Coral Park. Así nació un área no incorporada, que depende directamente del condado y no de un municipio, con muchas viviendas de una misma generación que ya superan el medio siglo.\n\nEsa edad importa cuando hablamos de abejas. Una colonia no necesita un agujero grande: le basta la separación entre dos maderas del alero, una rejilla de ventilación suelta o una teja que ya no asienta. Si las ve entrando y saliendo por un mismo punto del techo, lea nuestra página sobre [[es:svc-abejas-en-techos|abejas en techos y tejas]].\n\nHay otro dato del censo de 2020 que tenemos presente: casi una de cada cuatro personas en Westchester tiene 65 años o más. Para un adulto mayor que vive solo, un enjambre junto a la entrada no es una curiosidad, es un riesgo real. Por eso trabajamos sin veneno y las abejas terminan vivas en manos de un apicultor.",
    "hotspots_h": "Los rincones de Westchester que una colonia elige",
    "hotspots": [
        ("Aleros y rejillas del ático", "En casas de los años cincuenta y sesenta, la madera del alero se reseca y se abre en las uniones. Una rendija del ancho de un lápiz es suficiente para que un enjambre entero se instale en el ático y empiece a construir panal."),
        ("Tapas de servicio en el césped", "Las tapas enterradas en el césped del frente forman una cavidad oscura y fresca que a las abejas les encanta. Quien levanta la tapa sin saberlo recibe una defensa inmediata, así que es preferible no tocarla y avisarnos."),
        ("Árboles maduros del patio", "Los árboles que crecieron junto con el barrio desarrollan ramas huecas y cavidades en el tronco. Dentro de un hueco así, una colmena puede crecer durante mucho tiempo antes de que alguien en la casa se dé cuenta."),
        ("Locales comerciales de Bird Road", "Bird Road atraviesa Westchester como avenida comercial de seis carriles. Letreros huecos, techos planos con equipos de aire acondicionado y cajas eléctricas exteriores atraen colonias, y el dueño necesita resolverlo sin cerrar el negocio ni asustar a la clientela."),
        ("Cerca de parques y lagos", "Tropical Park tiene cuatro lagos y un centro ecuestre, y Tamiami Park ocupa parte del antiguo aeropuerto. Las abejas necesitan agua todos los días, y las casas cercanas a estos espacios quedan dentro de su radio de búsqueda."),
    ],
    "band": ("¿Ve abejas entrando por el alero?", "Llame o mande una foto por texto para empezar; la cotización es gratis y le decimos con claridad qué incluye el trabajo."),
    "streets_h": "Barrios y sectores de Westchester que atendemos",
    "streets": [
        ("Miracle Manor y Mirador", "Forman parte de la ola de urbanizaciones que siguió a la de 1955. En viviendas de esa época revisamos con calma la línea del techo, los aleros y las rejillas, que es donde la madera vieja deja pasar a las exploradoras."),
        ("Westchester Park y Town Park", "Subdivisiones de los años sesenta. Además de las paredes, en un patio conviene mirar troncos huecos, casetas de herramientas y las cajas de servicio ocultas entre las plantas."),
        ("Coral Park", "Aquí están Miami Coral Park High School, Coral Park Elementary y la Coral Park Baptist Church. Cerca de escuelas e iglesias una colonia activa preocupa más, y es lógico que la dirección quiera tener nuestro certificado de seguro (COI) en sus manos antes de dar luz verde."),
        ("University Park", "Antes era un CDP aparte; hoy ocupa la mitad oeste de Westchester, y FIU queda en su parte noroeste. Donde a diario pasan tantas personas, un enjambre en un árbol junto a la acera merece atención rápida."),
        ("Corredor de la SW 16 Street", "En la esquina con la 87 Avenue se estableció el templo Or Olom, en un edificio moderno de mediados de siglo que hoy se conoce como la iglesia de la ballena. Un techo de diseño poco común tiene recovecos y uniones que una colonia puede aprovechar."),
    ],
    "body": [
        ("Casas de medio siglo: por qué las abejas encuentran entrada", "Una vivienda de los años cincuenta o sesenta lleva muchos años soportando sol, humedad y huracanes. Los clavos se aflojan, el sellador se cuartea y las piezas de madera se contraen. Ninguna de esas fallas se ve desde la acera, pero una abeja exploradora las encuentra enseguida, porque busca justo eso: una cavidad seca, protegida y con una sola entrada.\n\nCuando la colonia ya está adentro, la pregunta es cuánto hay que abrir. Con la cámara térmica vemos el calor que genera la colmena detrás del panel o bajo las tejas, y así cortamos solo donde está el panal, no a ciegas. Después de sacar las abejas y el panal completo, la miel no puede quedarse ahí: atrae hormigas y otras plagas y puede manchar el yeso. Por eso limpiamos la cavidad antes de cerrar.\n\nCerrar y dejar bonito le toca a gente nuestra, con licencia: contratistas, techadores y pintores, así que no hace falta contratar a un tercero después. Si quiere ver el detalle de lo que cuesta cada parte, revise la página de [[es:precios|precios]]."),
        ("Iglesias, colegios y negocios: seguro y orden", "Westchester tiene una presencia institucional notable para un área residencial. Además de la iglesia de la ballena y de la Coral Park Baptist Church, aquí se encuentra el St. John Vianney College Seminary, y en la zona están los colegios católicos St. Brendan High School y Christopher Columbus High School. Sobre Coral Way funciona la Westchester Regional Library.\n\nPara quien administra un edificio con alumnos, feligreses o público, una colmena es también un asunto de responsabilidad. Trabajamos con licencia y seguro, y el COI que exige una junta de HOA, un condominio o un comercio se lo hacemos llegar a quien lo solicite. Para el expediente de la junta o del seguro, a pedido le entregamos fotos del trabajo y una factura desglosada.\n\nEn los locales de Bird Road, si las abejas están dentro de un muro del local, la página sobre [[es:svc-abejas-en-paredes|abejas dentro de paredes]] explica qué implica sacarlas."),
        ("Si usted cuida de sus padres desde otra parte", "Con tantos residentes mayores, puede que quien busca ayuda no viva en la casa: el hijo que trabaja en otro lado del condado o la nieta que llama desde otro estado. Usted nos llama, nos da la dirección y nos dice quién estará presente; la cotización es gratis y todo se puede hablar por teléfono.\n\nAl terminar, si lo pide, le mandamos fotos del trabajo y la factura con cada concepto por separado, para que sepa exactamente qué se hizo en la casa de sus padres. Y en caso de que la colonia intente instalarse otra vez justo donde cerramos, el regreso corre por nuestra cuenta. Para dejar los datos por escrito, use nuestro formulario de [[es:solicitar|solicitud de servicio]]."),
    ],
    "visit_h": "Así se desarrolla la visita",
    "visit": [
        ("Llamada y preguntas iniciales", "Le preguntamos dónde están las abejas, desde cuándo las ve, si alguien ha sido picado y si hay personas mayores, niños o mascotas cerca. Con eso decidimos qué equipo llevar."),
        ("Búsqueda con cámara térmica", "Recorremos el exterior y, si hace falta, el interior con la cámara térmica para ubicar la colonia exacta. Así sabemos dónde abrir y evitamos romper de más."),
        ("Extracción en vivo del panal", "Aspiramos con cuidado a las obreras y a la reina, cortamos cada lámina de cera con su miel y la colonia entera queda en manos de un apicultor."),
        ("Limpieza, sellado y reparación", "Limpiamos la cavidad, sellamos la entrada y nuestros contratistas reparan techo, pared o pintura. Ese cierre lo respaldamos: un nuevo intento en el mismo hueco nos trae de vuelta."),
    ],
    "faqs": [
        ("Westchester no tiene alcaldía propia; ¿igual vienen hasta aquí?", "Claro que sí. Westchester es un área no incorporada, registrada por el censo como CDP, y los servicios municipales los presta directamente el condado. Para sacar abejas eso no cambia nada: atendemos cualquier dirección dentro de Miami-Dade, sea una ciudad, un pueblo o un área no incorporada como esta o [[es:zona-kendall|Kendall]]."),
        ("¿Puedo rociar insecticida antes de que ustedes vengan?", "Le pedimos que no lo haga. El veneno no alcanza a la reina dentro de la pared, las abejas se ponen más agresivas y las que mueren dejan un panal que se pudre y atrae otras plagas. Además, sus vecinos y su familia quedan expuestos a abejas alteradas. Lo más seguro es mantener distancia y esperar la remoción en vivo."),
        ("Apareció una bola de abejas en la mata de mango. ¿Qué hago?", "Un enjambre colgado en forma de racimo suele estar tranquilo, porque las abejas no tienen panal ni crías que defender todavía; están esperando que las exploradoras elijan un hogar. Aun así, no lo moleste ni lo moje. Si se queda o empieza a entrar en una pared o en el ático, llámenos para recogerlo vivo antes de que construya panal."),
        ("Mi madre vive sola en Westchester. ¿Puedo organizar todo desde lejos?", "Sí. Usted puede coordinar la visita por teléfono y, si las pide, recibir las fotos del trabajo y la factura detallada. Díganos quién estará en la casa ese día y con quién debemos hablar, y la cotización gratis se la explicamos a usted directamente."),
        ("¿Van a tener que romper la pared o el techo?", "A veces sí, porque el panal tiene que salir completo. La cámara térmica nos indica dónde está la colonia y eso reduce la abertura al mínimo. Luego el mismo equipo de reparación, con licencia, cierra la abertura y deja el acabado listo."),
        ("Son las once de la noche y hay abejas en la sala. ¿Contestan?", "Sí, alguien contesta el teléfono a cualquier hora y cualquier día del año, y si hubo picaduras, su llamada salta por delante de las demás. Mientras tanto, cierre la puerta de esa habitación y apague las luces cercanas. Sepa que salir de madrugada o un domingo tiene un costo mayor que una cita ordinaria de lunes a viernes."),
    ],
    "servicios": [
        ("abejas-en-techos", "Las tejas y aleros de las casas de los años cincuenta y sesenta de Westchester son el punto de entrada más típico para una colonia en el ático."),
        ("contador-de-agua", "Las tapas de contadores y cajas de válvulas en el césped del frente esconden colonias que atacan al primero que las levanta."),
        ("abejas-en-paredes", "Paredes de viviendas y locales de Bird Road donde la colmena crece oculta y hay que abrir con precisión guiados por la cámara térmica."),
        ("enjambres", "Racimos de abejas en árboles maduros del patio o en cercas, que conviene recoger vivos antes de que se muden a la casa."),
        ("emergencias", "Un abuelo picado en el portal o un racimo que bloquea el garaje no espera turno: la línea contesta de madrugada y esos casos encabezan la lista."),
    ],
    "cercanos": ["kendall", "miami", "doral", "west-kendall"],
    "close": ("Abejas fuera, casa cerrada en Westchester", "Díganos dónde están las abejas y le preparamos una cotización gratis para sacarlas vivas, reparar y sellar la entrada."),
    "card": "Westchester, entre Tamiami Trail y Bird Road: casas de posguerra con aleros y tejas que dejan pasar colonias, abejas reubicadas vivas y arreglos hechos por nuestra gente.",
    "facts": [
        "Westchester es un CDP de Miami-Dade; el CDP de University Park se fusionó con él antes del censo de 2020; población de 2020: 56,384 (source: https://en.wikipedia.org/wiki/Westchester,_Florida)",
        "Límites del CDP: SW 8th Street/Tamiami Trail al norte, SW 40th Street/Bird Road al sur, Palmetto Expressway al este y SW 117th Avenue al oeste (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "La tierra no calificaba para la Ley de Homestead de 1862 por las inundaciones; los canales la secaron hacia los años veinte; la zona seguía casi sin desarrollar en 1950 (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "Una subdivisión de 1955 llamada Westchester dio nombre al área; Miracle Manor, Mirador, Westchester Park, Town Park y Coral Park siguieron durante los años sesenta (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "FIU se construyó sobre el antiguo Tamiami Airport; Tamiami Park ocupa otra parte de esos terrenos (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "Tropical Park, parque del condado en el antiguo hipódromo, abierto en 1979, con cuatro lagos y un centro ecuestre (source: https://en.wikipedia.org/wiki/Tropical_Park)",
        "Temple Or Olom se estableció en SW 16 Street y 87 Avenue, en un edificio moderno de mediados de siglo hoy conocido como la iglesia de la ballena; St. Brendan High School y Christopher Columbus High School son colegios católicos de la zona (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "St. John Vianney College Seminary está en Westchester (source: https://en.wikipedia.org/wiki/Westchester,_Florida)",
        "Censo 2020: 18,362 viviendas; edad mediana 45.3; 23.2 % de residentes de 65 años o más (source: https://en.wikipedia.org/wiki/Westchester,_Florida)",
        "Westchester Regional Library en 9445 Coral Way; Miami Coral Park High School, Coral Park Elementary y Coral Park Baptist Church están en Westchester (source: https://en.wikipedia.org/wiki/Westchester,_Florida)",
        "Bird Road cruza Westchester como avenida comercial de seis carriles dividida (source: https://en.wikipedia.org/wiki/Bird_Road)",
        "El antiguo CDP de University Park ocupa la mitad oeste del CDP actual; FIU está en su parte noroeste (source: https://en.wikipedia.org/wiki/Westchester,_Florida)",
    ],
}
