# -*- coding: utf-8 -*-
"""Aventura page copy."""

CITY = {
    "key": "aventura",
    "title": "Aventura Condo Bees: Towers, Docks and the Golf Ring",
    "desc": "Bee removal Aventura condo boards can approve: COIs on request, live relocation, and work planned around towers, gatehouses and the Intracoastal.",
    "h1": "Aventura Bees in Condo Towers, Garages and Docks",
    "kicker": "North Dade, at the county line",
    "lede": "Aventura is mostly vertical, so a colony here is usually a building problem before it is a yard problem. You need someone who can get past the gatehouse, satisfy the board and reach the spot.",
    "quick": "High rises set around the Turnberry course make up most of Aventura, so the opening moves of a removal here are paperwork and access rather than tools: a COI sent to management, a service elevator or roof key booked, and a ruling on whether the comb sits in a unit or a common element. After that, the colony is lifted out alive and handed to a beekeeper. A planter or valve box reachable from the pavement tends to fall near $300 to $400; comb thirty floors up or sealed behind stucco and drywall can climb into the thousands.",
    "glance": [
        ("Incorporated", "November 7, 1995"),
        ("Land and water", "2.65 square miles of land, with water adding 0.87 more"),
        ("Eastern edge", "Intracoastal Waterway and Dumfoundling Bay"),
        ("City center", "Turnberry Golf Course, ringed by Country Club Drive"),
        ("2020 census", "40,242 residents"),
    ],
    "opening": "Before the city existed, this stretch went by the name Turnberry, and building started in the early 1970s. Aventura did not become a city until November 1995. Today it is largely residential high rises set around a golf course, with the Intracoastal on one side and Biscayne Boulevard on the other.\n\nThat shape decides how bees show up. A scout bee hunting for a cavity does not care whether a gap sits on the ground floor or the thirtieth. Rooftop mechanical housings, garage expansion joints, planter boxes on pool decks and the hollow bases of light poles all read as shelter. What changes in Aventura is the response: the colony usually sits on shared property, several people have to sign off, and the work has to fit a building's rules about contractors, hours and elevators.",
    "hotspots_h": "Where colonies tuck into Aventura buildings",
    "hotspots": [
        ("Rooftop mechanical areas", "Equipment enclosures, chiller housings and the voids beside them stay dry and sheltered on a tower roof. Bees flying in and out up there can go unnoticed for weeks, until a maintenance tech opens a panel and finds comb."),
        ("Garage expansion joints", "Parking structures under and beside condo towers have joints, conduit chases and cracked block that open into dark cavities. A steady line of bees along one wall of a garage level is worth a call before residents start parking under it."),
        ("Pool deck planters and palms", "Raised planters, hollow palm boots and the irrigation boxes feeding them sit beside the one place everyone walks barefoot. Bees also drink from pool edges, so foragers on the deck do not always mean a hive is close."),
        ("Docks and seawall gaps", "Along the Intracoastal and the bay, dock boxes, utility pedestals and gaps in seawall caps give a colony a dry pocket right where owners load boats. Those spots are tight and slow to open safely."),
        ("Golf-course-side landscaping", "The course at the center of the city sits among lakes and landscaped grounds, where irrigation valve and meter boxes are buried in the beds. A colony low in one of those boxes is usually simpler and less costly to reach than one high on a tower."),
    ],
    "streets_h": "Notes on Aventura communities",
    "streets": [
        ("Williams Island", "Williams Island is a section of Aventura, and a visit there starts at your building's front desk and whatever entry check your association runs. Give us the building name and who holds the contractor list, and the visit can be cleared before anyone drives over."),
        ("Point East", "Point East buildings go by letter, and the city's Founders Day shuttle schedule lists them that way, from A through T. When you call, the letter matters as much as the street address: it tells us which manager receives our COI and which entrance the crew should use."),
        ("Mystic Pointe", "Mystic Pointe towers carry numbers, 100 through 600. Bees reported on a balcony in one tower and a planter in another are two separate colonies until proven otherwise, so note the tower and floor for each sighting."),
        ("Turnberry Isle and the Yacht Club", "Turnberry Isle North and South, the Turnberry Gatehouse and the Yacht Club each appear by name on the city's Founders Day shuttle schedule. If your building has a gatehouse, expect a check-in there, and if the colony is near a slip, we will ask which dock and whether a boat needs moving."),
        ("Country Club Drive and the golf ring", "Country Club Drive circles the Turnberry course, and its paved promenade looks out over lakes and residential high rises. Swarms resting in course-side trees can move on alone; bees entering a wall or box will not."),
        ("Biscayne Lakes Gardens", "Biscayne Lakes Gardens is another name on that shuttle schedule. If your building there has a management office, start with them so the insurance paperwork and access plan are settled before the visit."),
    ],
    "body": [
        ("Who calls, and who signs off", "In a single-family house, the owner decides. In an Aventura condo, the decision often runs through a property manager, a board and sometimes a building engineer, and the bees do not wait for the next meeting. It helps to know where the colony sits. Bees inside your own enclosed balcony planter may be a unit issue; bees behind the exterior stucco or under the roof membrane are usually a common element that the association handles. Your declaration is the final word on that, not us.\n\nWhat we can do is make the approval easy. Management can have our COI on request, the scope is spelled out before anything is opened, and photos plus an itemized invoice can follow for the board file. If the colony has to come out of a wall or roof, the patch is done by our own crew of licensed contractors, roofers and painters, which spares the association from hiring and scheduling a second trade. Our [[svc:condos-high-rises|high-rise removal page]] and [[svc:hoa-commercial|association and property manager page]] go deeper on how that paperwork moves."),
        ("Water at the edges and in the middle", "The Intracoastal and Dumfoundling Bay run along Aventura's east side, the southern boundary lies in Maule Lake, and lakes line the golf course at the center. Honey bees need water every day, especially in summer heat, so pools, fountains, irrigation drips and boat decks all draw foragers.\n\nThat creates a common mix-up. Dozens of bees sipping at the edge of a pool are usually just drinking and will fly off to a hive that may be blocks away. A cluster of bees hanging in a ball on a railing is a swarm in transit, which you can read more about on our [[svc:swarms|swarm pickup page]]. Bees streaming steadily into one slot in a wall, a dock box or a seawall cap are the ones that have moved in. For waterfront spots, see [[svc:waterfront-boats|docks, seawalls and boats]]."),
        ("When the unit sits empty", "Some Aventura units stay closed for long stretches while owners are away. A quiet balcony with planters, vents and gaps nobody checks is just the kind of undisturbed spot scouts look for, and nobody is there to notice them. Owners who leave for a season can ask the front desk or engineer to glance at balconies and roof hatches now and then; [[guide:second-home|our seasonal-home guide]] lists the signs worth reporting. When a colony is hidden behind finished surfaces, [[guide:thermal-imaging|thermal imaging]] helps pinpoint it so only the right section is opened."),
    ],
    "band": ("A colony twenty floors up?", "Text us a photo with your building name and floor, and the COI and access plan can start on that first call."),
    "visit_h": "How an Aventura visit runs",
    "visit": [
        ("Clear the front desk", "We confirm the building, unit or common area, and what the gatehouse or lobby needs from a contractor. Your manager has our COI in hand before the date is set."),
        ("Book the access", "Service elevator, roof hatch key, garage level or dock: whatever the colony needs is reserved in advance, so residents are not held up and the crew is not waiting downstairs."),
        ("Remove the colony alive", "The whole colony, wax included, is lifted out intact and driven to a beekeeper who keeps it. Nearby residents are asked to keep balcony doors shut while the area is open, which keeps everyone calm."),
        ("Seal, repair, report", "The entry is closed, any opened surface is repaired by our own crews, and photos with an itemized invoice go to whoever needs them for the board."),
    ],
    "alarm": "Stings happening now? Move inside, into a lobby, stairwell or unit, and let the door close behind you. Anyone wheezing, with a swollen tongue or lips, or stung many times needs 911 first. Ask the front desk to keep residents off that balcony, deck or garage level. Then phone us at any hour; a person under attack is handled ahead of everything else.",
    "faqs": [
        ("Our management office wants insurance paperwork before you arrive. Is that a problem?", "Not at all. A COI can be sent to the association or management company before the visit. Ask your manager where it should go and pass that along when you call, so it is in hand by the time the date is booked."),
        ("I live on a high floor. Can bees really be up here?", "Yes. Honey bees forage and scout well above ground level, and a tower offers plenty of sheltered gaps around balconies, planters and rooftop equipment. A handful of bees on a railing may just be passing through. Bees going in and out of one opening for several days point to a colony that needs attention."),
        ("Who pays: me or the association?", "Your condominium documents settle it, along with the exact location of the comb. Bees inside something you own and maintain may be your cost; bees in the building envelope are usually a common element. Check with your manager first. We can quote either party, and the quote is free."),
        ("What will this cost for a planter or a valve box at ground level?", "Ground-level jobs like a planter, an irrigation box or a low wall typically land around $300 to $400. Colonies high on a building, under roofing, or inside a wall that must be opened and patched can run into the thousands. Calling us out after dark or over a weekend is priced higher than booking a regular weekday slot. See our [[page:cost|cost page]] for what drives the number."),
        ("If you seal the spot and bees come back, then what?", "Our sealing work carries a warranty: a fresh colony in that same closed-up gap gets another visit from us. Leftover wax and scent are what pull new scouts to an old cavity, as [[guide:why-bees-come-back|this field guide article]] describes, so the space is emptied and cleaned rather than simply plugged."),
    ],
    "services": [
        ("condos-high-rises", "Towers, balconies, roof equipment and the board approvals that come with them."),
        ("hoa-commercial", "Managers and associations who need a COI, a written scope and an itemized invoice."),
        ("waterfront-boats", "Dock boxes, pedestals and seawall caps along the Intracoastal and the bay."),
        ("pool-enclosures", "Pool decks, equipment rooms and the planters and palms beside them."),
        ("utility-boxes", "Irrigation valves and meter boxes in landscaping around the golf ring."),
    ],
    "nearby": ["north-miami-beach", "sunny-isles-beach", "golden-beach"],
    "close": ("Tell us the building and the floor", "Name the tower, the floor and the spot in the quote form, and your manager hears from us about insurance and access first."),
    "card": "Condo towers, a central golf course and water along the east; live removal with COIs and access plans for Aventura buildings and associations.",
    "facts": [
        "Aventura was incorporated on November 7, 1995 (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "Total area 3.52 sq mi: 2.65 sq mi land and 0.87 sq mi water; 2020 census population 40,242 (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "The area was initially referred to as Turnberry and began to be developed in the early 1970s (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "The Atlantic Intracoastal Waterway and Dumfoundling Bay form the eastern border; the southern border is within Maule Lake (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "Turnberry Golf Course is at the geographical center, encircled by Country Club Drive, with a three-mile paved walking/jogging promenade overlooking lakes and residential high rises (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "U.S. Route 1 (Biscayne Boulevard) runs along the western edge; the golf course promenade overlooks lakes and residential high rises (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
        "Williams Island (Florida) is a section of Aventura (source: https://en.wikipedia.org/wiki/Williams_Island)",
        "The city's Founders Day Aventura Express shuttle schedule lists stops including Williams Island, Point East buildings by letter (A through T), Mystic Pointe 100 through 600, Turnberry Isle North and South, Turnberry Gatehouse, Yacht Club and Biscayne Lakes Gardens (source: https://www.cityofaventura.com/DocumentCenter/View/4440/Founders-Day-Bus-Routes-2023)",
        "Borders: North Miami Beach to the south, Golden Beach and Sunny Isles Beach to the east, unincorporated Ojus to the west, the county line to the north (source: https://en.wikipedia.org/wiki/Aventura,_Florida)",
    ],
}
