# -*- coding: utf-8 -*-
"""Cutler Bay page copy."""

CITY = {
    "key": "cutler-bay",
    "title": "Cutler Bay Bees: Block Walls, Lakes and Tile Roofs",
    "desc": "Cutler Bay homes rebuilt in block after Andrew can hide a colony in the wall. Bees go to a beekeeper alive, the stucco gets patched, and the quote is free.",
    "h1": "Bees Inside a Cutler Bay Wall, Roof or Valve Box, Removed Alive",
    "kicker": "Town of Cutler Bay, South Dade",
    "lede": "Cutler Bay is a young town laid over old subdivisions, lakes and canals on the edge of Biscayne Bay. When a colony moves into your block wall, roof or yard, the bees can leave alive and the gap can be closed for good.",
    "quick": "A Cutler Bay colony need not be poisoned; it can leave your property living and end up in a beekeeper's boxes. Ground-level jobs, like a sprinkler valve box or a hedge by the driveway, generally fall near $300 to $400. A hive behind stucco or roof tile, where opening and rebuilding are part of the work, can run into the thousands. Pricing it out costs you nothing, the phone is picked up at any hour, and a response comes inside the 24-hour guarantee. Each cut in stucco or lifted tile is then repaired by licensed tradespeople from our own crew.",
    "glance": [
        ("Incorporated", "November 9, 2005, when voters approved the town charter"),
        ("Name vote", "Cutler Bay beat Cutler Ridge, 1,920 to 1,403"),
        ("Population", "45,425 in the 2020 census"),
        ("East edge", "Biscayne Bay"),
        ("Underfoot", "An ancient coral ridge, about 14 feet above sea level here"),
    ],
    "opening": "The Town of Cutler Bay has only existed since November 9, 2005, when residents approved a charter and chose the new name over Cutler Ridge by 1,920 votes to 1,403. The land under it is much older. The Cutler Ridge, an ancient coral formation, passes through town about 14 feet above sea level, and Biscayne Bay forms the eastern boundary. Between the two sit subdivision sections platted mostly from 1948 onward, threaded with canals, channels and lakes that are frequently full of water.\n\nThat combination is why bees do well here. Hurricane Andrew left the area in near-total destruction in 1992, and in Lakes by the Bay the rebuilt homes went up with concrete walls instead of wood frame. Hollow block, barrel tile, soffit vents and in-ground utility boxes all give a swarm a dry, dark room, and the lakes and canals keep water within reach of many yards. A colony that slips through a pencil-sized gap in spring can have a wall cavity lined with comb before anyone connects the steady traffic at one small hole to a hive.",
    "hotspots_h": "Where colonies move in on Cutler Bay properties",
    "hotspots": [
        ("Hollow concrete block walls", "Block walls have open cells inside them, and those cells connect along a course. Bees get in at a cracked stucco joint, a gap around a hose bib or a pipe sleeve, and build comb out of sight. All you notice is a line of bees using one spot on the wall."),
        ("Barrel tile and flat roof edges", "Every course of barrel tile leaves a channel underneath, and a flat roof can lift at the membrane edge or parapet cap. Either can lead into the dry space above a ceiling. A thermal camera maps the heat of the brood nest from below, which tells the crew which tiles to lift first."),
        ("Meter, valve and irrigation boxes", "Boxes for water meters, sprinkler valves and electric service sit low, stay dark and lie right in a mower's path. The bees inside are rarely the danger; the danger is a lid lifted without warning. Ground-level jobs like these are the ones priced around $300 to $400."),
        ("Lots on lakes and canals", "When your yard backs onto one of the town's lakes or canals, foragers have water a few seconds away. Bees collecting it may line a pool coping or a fountain lip, and a passing swarm may settle in your eave because the water is so close."),
        ("Storefronts along South Dixie Highway", "Southland Mall, the former Cutler Ridge Mall, and the retail strips along South Dixie Highway carry parapets, sign cabinets and rooftop equipment. A colony over a busy entrance calls for a planned, quiet removal and a certificate of insurance for the property manager."),
    ],
    "streets_h": "Neighborhood notes, section by section",
    "streets": [
        ("Cutler Ridge sections", "Section One of Cutler Ridge was platted in 1954, and Sections Three through Seven followed by 1958. On these early streets, look closely at where a later addition or enclosed carport meets the original house; that seam is a frequent entry point for scouts."),
        ("Bel Aire", "The first Bel Aire section was created in 1957, and 23 more were added through 1978. A neighborhood built in that many phases is not one uniform product, so where bees enter one house says little about the house next door."),
        ("Whispering Pines and Holiday House", "Both subdivisions date to 1956 and 1957. If you live here, walk the roofline where a porch or room was added, and check sheds and wooden fence posts along the back of the lot, where a small swarm can go unnoticed for weeks."),
        ("Saga Bay", "Saga Bay came from a 1972 re-platting of part of the Tenalla Ocean Farms subdivision, first laid out in 1924. A steady stream of bees at your pool or birdbath here can mean a colony is living within a short flight, though not always on your lot."),
        ("Lakes by the Bay", "Section One was developed in 1983. Andrew destroyed most homes and businesses in the neighborhood, and the rebuilding used concrete walls in place of wood frame. Bees in those walls are reached by opening stucco from outside, then patched and painted to match."),
        ("Lincoln City", "Lincoln City Section A was created in 1948, one of the first post-war plats in today's town. If your lot holds an older shade tree with a hollow limb, that cavity is as attractive to a colony as any wall, and it is handled as a tree job."),
    ],
    "body": [
        ("Built twice, and what that means for bees", "Much of Cutler Bay has been built twice: once in the subdivision building that took off after 1948, and again after Andrew in 1992. That second round explains a lot about where colonies end up. Concrete block replaced wood frame in places like Lakes by the Bay, so the cavity a swarm finds is often a column of hollow block cells rather than a stud bay. Bees work along those cells, which is why a colony can show up a few feet from the hole they use.\n\nThe fix is the same in principle as anywhere, but the details are local. The colony has to be found, opened from the side that does the least damage, and removed with all its comb, since leftover honey draws new scouts back to the same smell. Read [[guide:why-bees-come-back|why bees return to a spot]] if you have dealt with this before. After that, licensed hands from our own crew refill the block, float new stucco and repaint. That work carries a warranty, so a colony reappearing at a sealed opening means another trip out at our end. The [[svc:walls|block wall service]] explains how the colony is reached, and [[svc:repairs|the repair page]] covers the patching and paint."),
        ("Lakes, canals and the rainy season", "The town is prone to flooding, and its canals, channels and lakes are frequently full. For a honey bee colony, standing water is a resource; foragers carry it home to cool the brood nest on hot days. That is why a line of bees at your pool edge is worth a second look, even when you see no hive.\n\nSwarms travel mostly in spring and early summer. While scouts inspect possible homes, the queen and workers hang together in a clump on a branch or railing, fairly gentle because they have no nest to guard yet. Collecting one is a [[svc:swarms|swarm pickup]] and usually takes no demolition at all. Once it moves into a wall, roof or meter box, it is a colony, and the job changes. Hurricane season adds one more wrinkle: wind that peels a soffit or snaps a palm can leave comb hanging in the open, which is the subject of [[guide:after-a-storm|this field guide piece on storms]]."),
        ("Associations, storefronts and the marina", "If your home sits inside a homeowners association, or your storefront along South Dixie Highway answers to a landlord, expect them to want a certificate of insurance before anyone works on common ground or a roof, and possibly photos and an itemized invoice afterward. All of that is available on request; ask for it when you call so it is ready before the visit. Board-managed and retail jobs are outlined under [[svc:hoa-commercial|association and commercial work]].\n\nJust past the town's southern edge at SW 232nd Street, Black Point Park and Marina has a jetty running 1.5 miles into Biscayne Bay and a boat ramp open around the clock. If bees have moved into a dock box, a stored boat or a cuddy cabin, see [[svc:waterfront-boats|docks, seawalls and boats]]."),
    ],
    "band": ("A steady line of bees at your stucco?", "Phone or send a picture day or night; pricing is free, and every bee leaves alive for a beekeeper's yard."),
    "visit_h": "How a Cutler Bay visit runs",
    "visit": [
        ("Picture before the trip", "A phone shot of where the bees enter, taken from a safe distance, gives the crew an early read on whether they face a hedge swarm or a settled colony in block, tile or a valve box."),
        ("Scan before cutting", "On site, thermal imaging traces the warm comb inside the wall or roof, so the opening is made over the hive itself instead of in several guessing spots."),
        ("Out alive, then closed up", "Bees and comb come out together and go to a beekeeper. Honey residue is cleaned out so it stops attracting scouts, and the entry is sealed before the repair crew finishes."),
        ("Paperwork if your board needs it", "If your association or landlord needs a certificate of insurance before work on common areas, say so on the call. For the manager's records, the wall opening and seal can also be documented in images, with each charge broken out separately, on request."),
    ],
    "alarm": "Bees chasing or stinging someone this minute? Get indoors quickly and close the doors behind you; bring pets in too. Leave the hose and the bug spray alone, since both make a colony angrier. A swollen tongue, tight throat or wheezing means 911 first, then our line, where stings jump the queue.",
    "faqs": [
        ("My Lakes by the Bay house has concrete walls. Can bees really be living inside them?", "Yes. Concrete block is hollow, and the cells inside give a colony a dark, dry space protected from weather. Bees get in through small cracks in stucco or gaps around pipes and wiring. Thermal imaging shows where the comb sits, so the wall is opened in one place, the hive is taken out alive, and the block and stucco are patched and painted."),
        ("Bees line up at the edge of my pool every afternoon. Does that point to a colony on my lot?", "Maybe, though not for certain. Workers haul water home to cool the nest and keep returning to whatever source proved reliable, so the colony could be a neighbor's tree. Watch your own eaves, shed and roof for a single gap with traffic in both directions. If you find one, send a picture of it and of the pool."),
        ("The association wants proof of insurance before a crew sets foot on common ground. Is that a problem?", "Not at all. The company carries a license and insurance, and the certificate can be made out to the board or the management firm ahead of the appointment. Afterward, the manager can ask for pictures from the job and a line-by-line bill to keep on file."),
        ("Does taking a hive out of barrel tile mean a hole in my roof?", "Some tiles above the nest come off, and now and then underlayment or decking is opened to reach the deepest comb. The roofers who put it back work for us and hold their own licenses. Should a colony show up again at that patched section, a return visit is part of the warranty."),
        ("A cluster of bees is hanging from my palm frond. Can I just let it leave by itself?", "It may well move on once the scouts agree on a cavity. Trouble starts if that cavity turns out to be your soffit or attic. When the clump hangs over a walkway, a pool deck or a child's play set, a pickup while it is still exposed is the simpler, cheaper job."),
    ],
    "services": [
        ("walls", "Post-Andrew concrete block homes hold colonies inside hollow cells behind stucco."),
        ("roofs", "Barrel tile channels and flat roof edges lead bees into dry attic space."),
        ("utility-boxes", "In-ground boxes by the curb or the hedge line hide colonies right where a foot or mower lands."),
        ("pool-enclosures", "Lake and canal lots mean bees around pools, screens and equipment pads."),
        ("swarms", "Clusters hanging off fronds or chain link in spring, caught before they move into the house."),
        ("hoa-commercial", "Associations and South Dixie Highway landlords often require a certificate of insurance first."),
    ],
    "nearby": ["palmetto-bay", "pinecrest", "kendall", "homestead"],
    "close": ("Steady bee traffic at one gap in your block wall?", "Send a photo or the quote form, and the live removal and matching repair can be planned for your Cutler Bay address."),
    "card": "A 2005 town over 1950s subdivisions and post-Andrew block homes, where colonies turn up in walls, tile roofs, valve boxes and lakeside eaves.",
    "facts": [
        "Town of Cutler Bay voters approved the charter on November 9, 2005, choosing the name Cutler Bay over Cutler Ridge, 1,920 to 1,403 (source: https://en.wikipedia.org/wiki/Cutler_Bay,_Florida)",
        "2020 census population 45,425; the town runs east to the coast on Biscayne Bay; bordered north by the Village of Palmetto Bay, west by unincorporated South Miami Heights and southwest by unincorporated Goulds; southern border SW 232nd Street, north of Black Point Marina (source: https://en.wikipedia.org/wiki/Cutler_Bay,_Florida)",
        "Cutler Ridge, an ancient coral formation, runs through the Cutler Bay area at a height of about 14 feet; the area is prone to flooding and its canals, channels and lakes are frequently full (source: https://en.wikipedia.org/wiki/Cutler_Bay,_Florida)",
        "Hurricane Andrew made landfall near Cutler Ridge in 1992, leaving the area in almost total destruction (source: https://en.wikipedia.org/wiki/Cutler_Bay,_Florida)",
        "Lakes by the Bay is a neighborhood and former CDP that became part of Cutler Bay in 2005; most homes and businesses there were destroyed by Hurricane Andrew in August 1992, and the destroyed wood-frame homes were rebuilt with concrete walls (source: https://en.wikipedia.org/wiki/Lakes_by_the_Bay,_Florida)",
        "Subdivisions: Lincoln City Section A 1948; Cutler Ridge Section One 1954, Section Three 1955, Sections Four and Five 1956, Section Six 1957, Section Seven 1958; Holiday House and Whispering Pines 1956-1957; Bel Aire first section 1957 plus 23 more sections to 1978; Tenalla Ocean Farms 1924, part re-platted as Saga Bay in 1972; Lakes by the Bay Section One 1983 (source: https://www.cutlerbay-fl.gov/community/page/development-cutler-bay)",
        "Southland Mall, formerly Cutler Ridge Mall, is at 20505 South Dixie Highway in Cutler Bay, was renamed in November 2003 and was nearly destroyed by Hurricane Andrew (source: https://en.wikipedia.org/wiki/Southland_Mall_(Miami))",
        "Black Point Park and Marina is close to Biscayne National Park, has a jetty extending 1.5 miles into Biscayne Bay, and its boat ramp is open 24 hours (source: https://www.miamidade.gov/global/recreation/park/black-point-park-and-marina.page)",
    ],
}
