# -*- coding: utf-8 -*-
"""Doral page copy."""

CITY = {
    "key": "doral",
    "title": "Bees in Doral Warehouses, Townhomes and Homes",
    "desc": "Honey bees in a Doral warehouse parapet, townhouse soffit or backyard palm? Live removal, sealing and repair, with COIs ready for property managers.",
    "h1": "Warehouse parapets to townhouse soffits: Doral bee removal",
    "kicker": "Doral, west Miami-Dade",
    "lede": "Doral mixes business parks and family neighborhoods inside fifteen square miles. Honey bees use both, and the fix looks different in a distribution center than in a two-story townhouse.",
    "quick": "With 14 of the county's business parks inside city limits, a Doral bee call often lands on leased commercial property, where the owner rather than the tenant who spotted the bees approves the work and may want a COI first. Townhouse calls bring a shared wall instead. Either way, keep people back, do not spray or tape the hole, and text a photo of the entry point. The colony is vacuumed up alive for a beekeeper, every piece of comb is pulled, and the gap gets closed. Ground-level jobs run about $300 to $400; wall or roof repairs push that higher.",
    "glance": [
        ("Incorporated", "2003, after a seven-year push by residents"),
        ("Name", "Doris and Alfred Kaskel, who opened Doral Country Club in 1962"),
        ("Area", "About 15 square miles"),
        ("Population", "75,874 in the 2020 census"),
        ("West edge", "Ronald Reagan Turnpike and the Everglades"),
    ],
    "opening": "In the late 1950s the Kaskels bought 2,400 acres of swampland here for a golf club, and the city still runs out to the Everglades on its western side. Honey bee colonies multiply by swarming, most heavily in spring, and a scout looking for a dry, shaded cavity finds plenty of them in Doral: warehouse parapets, the hollow ends of townhouse rows, stucco walls on newer single-family streets.\n\nThe city's land use plan has a full industrial category for warehouses, showrooms and distribution centers, and 14 of the county's business parks sit inside city limits, so plenty of bee problems here turn up on commercial property. Those calls come with tenants, insurance paperwork and business hours to work around. Residential calls come with neighbors who share a wall. This page covers both, so you can tell what you are looking at and what the visit will involve.",
    "hotspots_h": "Where colonies settle on Doral buildings",
    "hotspots": [
        ("Warehouse parapets", "The low wall around a flat warehouse roof often hides a gap where flashing has pulled loose. Bees enter from above, out of sight from the parking lot, and the first sign is usually a line of them crossing the dock apron."),
        ("Dock and signage boxes", "Sign cabinets, light housings and hollow canopy framing over loading docks are enclosed and rarely opened. A colony can fill one with comb before anyone on the floor notices more than a few bees near the door."),
        ("Townhouse soffits", "Attached townhomes share long eave lines, and a vent screen that fails on one unit gives bees a path into the soffit that can run past the next owner's ceiling. Opening it may involve two households."),
        ("Stucco block walls", "On detached homes, bees slip through weep gaps, pipe penetrations and cracked stucco into the hollow cells of concrete block. Thermal imaging shows how far the comb reaches before anything gets cut."),
        ("Golf course trees", "Mature trees and palms along fairways and backyard edges have cavities and dense frond skirts. Swarms rest on branches here, and some stay long enough to start building comb in the open."),
    ],
    "streets_h": "Doral neighborhoods and what changes on the visit",
    "streets": [
        ("Doral Estates", "One of the first residential communities, built in the early 1980s by a Kaskel grandson. Houses here belong to the city's first residential wave, so aging roof edges and the attic line deserve the first look."),
        ("Doral Park", "Developed as a joint venture with Lennar after Doral Estates. Any shade tree or palm in a yard or common area can hold a resting swarm, and an association may ask for our COI before work on shared ground."),
        ("Downtown Doral", "The newer urban core, where the county library's Doral branch moved in 2019. Mixed-use and multi-story buildings mean bee work often runs through a property manager, a loading area and a set window of hours."),
        ("CityPlace Doral", "A development on the east side of the city. Where a site draws foot traffic, timing matters, so a removal can be planned for early morning when few people are around."),
        ("The business parks", "The city counts 14 of the county's business parks within its limits. Warehouses, showrooms and offices often have flat roofs and long service corridors where a colony can sit unnoticed for months."),
    ],
    "body": [
        ("Warehouses, showrooms and leased space", "In a warehouse or showroom, the person who notices the bees is rarely the person who can approve the work. Send a photo to whoever manages the building, and ask them to call us or send the quote form. Building owners usually want insurance on file first. The crew is licensed and insured, and the COI can list whichever company manages the property.\n\nWorkers should stay away from the opening and avoid running forklifts or pressure washers right beside it, because vibration and noise set guard bees off. Do not tape over the hole. Bees sealed inside look for another way out, and that can be an outlet or light fixture on the office side of the wall. A thermal camera lets the crew map the colony first, and repairs to parapets, flashing or panels are handled by our own licensed roofers and contractors. For larger sites, see [[svc:hoa-commercial|work for commercial and property managers]] and [[svc:roofs|flat roof hives]]."),
        ("When the bees share a wall with your neighbor", "Townhouse colonies are trickier than detached ones because the comb may cross into the unit next door. Before we open anything, it helps to know who owns the exterior and whether the association handles soffits and stucco. Let the neighbor know about the visit so nobody opens a window on the wrong side.\n\nThe crew vacuums the bees into a ventilated box for a beekeeper, cuts out the full comb along with the stored honey, and closes the gap so new scouts are not drawn to the scent. Our painters match the patch to your trim. Photos and an itemized invoice are available, which helps when an HOA needs proof of the repair. Our workmanship carries a warranty: should a new colony move into the patched section, the crew returns to deal with it. More detail is on [[svc:soffits-eaves|soffit and eave hives]] and [[svc:walls|bees in block walls]]."),
        ("Swarms on a branch versus a colony in a wall", "A swarm is a cluster of bees hanging from a branch, a fence or a car mirror. It has built nothing yet, and it tends to lift off once its scouts agree on a new home, often by the next morning or the one after. Give it space and keep children away. When one settles over an entry, a patio or the path to the car, it can be boxed up live and driven to a beekeeper.\n\nA colony is different. Bees going steadily in and out of one hole, carrying pollen, means comb and brood are already inside. That will not leave on its own, and spraying it only leaves dead bees and melting honey in the wall. Three or four bees circling a Doral eave for an afternoon are often [[guide:scout-bees|scouts on a house hunt]]; the dangling ball of bees belongs under [[svc:swarms|swarm pickup]]."),
    ],
    "band": ("Bees at a dock door or an eave line?", "One clear picture of the hole they use is often enough to judge whether it is a swarm, a young colony or an established one."),
    "visit_h": "How a Doral visit runs",
    "visit": [
        ("Access and paperwork", "For a business, we confirm the site contact, dock access and any COI the owner needs on file. For an HOA community, we ask about gate entry and who owns the exterior."),
        ("Finding the colony", "The crew watches the entrance, then uses a thermal camera on the wall, parapet or soffit to see where the warm cluster sits and how big it is."),
        ("Removal and sealing", "Bees are vacuumed out alive and the comb is cut away. Licensed contractors close the cavity and patch stucco, flashing or trim so the spot is not reused."),
    ],
    "alarm": "Someone being stung needs distance first: walk them inside or into a vehicle and shut the doors. Dial 911 at once if their breath gets short, their mouth or eyelids swell, or the stings keep adding up. Then phone us. Calls are picked up around the clock and anyone being stung is handled before routine jobs.",
    "faqs": [
        ("Who pays for bees inside a leased warehouse in Doral?", "That depends on your lease. Some leases make roof and exterior repairs the landlord's job, while the tenant handles the interior. Send the lease section and photos to the owner. Either party can get the quote, and whoever pays can have a COI and an itemized invoice."),
        ("Can removal happen before our warehouse opens for the day?", "Yes. A commercial removal can be scheduled for early morning or after closing so staff and customers are not near the opening. After-dark and weekend emergency calls are priced higher than a weekday appointment, so a colony that is not threatening anyone is cheaper to book midweek."),
        ("Our townhouse colony seems to extend into the unit next door. Who handles that?", "Talk to your neighbor and your association before the visit. The comb can cross the party wall, and we need access from whichever side gets us to it cleanly. We remove the whole colony, not just the half on your side, and repair the opening afterward."),
        ("Will my HOA accept the repair?", "Our own licensed contractors and painters do the patch, and we can photograph each step. If the association wants a COI or proof of the work for its files, mention it when you book and it will be sent over."),
        ("Where does a colony from a Doral building end up?", "With a beekeeper. The bees are collected alive and relocated, never exterminated. The comb comes out too, so the cavity is not left full of honey that draws a new swarm."),
    ],
    "services": [
        ("hoa-commercial", "Warehouses, showrooms and managed communities that need insurance paperwork and scheduled access."),
        ("roofs", "Flat warehouse roofs, parapets and tile roofs on single-family homes."),
        ("soffits-eaves", "Long shared eave lines and vent screens on Doral townhouse rows."),
        ("walls", "Concrete block and stucco walls on newer detached homes across the city."),
        ("trees-palms", "Trees and palms along fairways, in common areas and in backyards."),
    ],
    "nearby": ["hialeah", "miami-springs", "hialeah-gardens"],
    "close": ("Start with a picture of the opening", "Add the building type and your Doral address, and the free quote can begin from there."),
    "card": "Warehouse parapets, dock canopies, townhouse soffits and golf course trees in a city where business parks sit next to family neighborhoods.",
    "facts": [
        "Doral was incorporated in 2003; voters approved incorporation in January 2003 after a seven-year effort and accepted the charter in June 2003 (source: https://en.wikipedia.org/wiki/Doral,_Florida and https://www.cityofdoral.com/About/Doral-History)",
        "Alfred and Doris Kaskel bought 2,400 acres of swampland in the late 1950s; Doral Country Club opened in 1962; the name combines Doris and Alfred (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral covers about 15 square miles (source: https://www.cityofdoral.com/About/Doral-Facts)",
        "2020 census population 75,874 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Bordered on the west by the Ronald Reagan Turnpike and the Everglades, north by Medley, east by the Palmetto Expressway, south by the Dolphin Expressway and Sweetwater (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral Estates was developed in the early 1980s by the Kaskels' grandson Bill, followed by Doral Park as a joint venture with Lennar (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Downtown Doral is the city's newer urban core; the Miami-Dade Public Library System's Doral Branch moved there in June 2019 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "CityPlace Doral is in the east of the city (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
        "Doral contains 14 of Miami-Dade's 30+ business parks (source: https://www.cityofdoral.com/About/Doral-Facts)",
        "The Industrial future land use category allows warehouses, showrooms and distribution centers; housing in the Moderate Density Residential category includes detached single-family homes, townhouses and low-rise condominiums/apartments (source: City of Doral Comprehensive Plan, https://www.cityofdoral.com/files/assets/city/v/1/departments/planning-and-zoning/land-use-docs/cdmp-part-i-gops-2013-update.pdf)",
        "Doral's surrounding areas: Medley to the north, Hialeah to the northeast, Miami Springs to the east (source: https://en.wikipedia.org/wiki/Doral,_Florida); Medley is bordered to the north by Hialeah Gardens, with Doral to the south (source: https://en.wikipedia.org/wiki/Medley,_Florida)",
    ],
}
