# -*- coding: utf-8 -*-
"""Fisher Island page copy."""

CITY = {
    "key": "fisher-island",
    "title": "Bee Removal Fisher Island, Planned Around the Ferry",
    "desc": "Honey bees in a tile roof, palm or condo balcony on Fisher Island, removed alive with crew clearance and the crossing arranged ahead of time.",
    "h1": "Fisher Island Bee Removal, Arranged Before the Crossing",
    "kicker": "Private island, Biscayne Bay",
    "lede": "No bridge reaches Fisher Island, and honey bees never needed one. When a colony moves into a tile roof, a palm or a villa wall, the job starts with security clearance and ends with the bees alive on a beekeeper's land.",
    "quick": "Because no road or causeway reaches Fisher Island, a bee crew needs the same pre-arranged security clearance as any ferry guest, so the job begins with paperwork rather than a ladder. Phone, or text a picture of the cluster, and that clearance starts at once. The line is answered day or night, the water does not change our 24-hour response guarantee, and the quote is free. The colony then comes off the island alive, bound for a beekeeper, with no spray, and the plan covers your building's rules and the tile or stucco that has to be put back.",
    "glance": [
        ("Status", "Unincorporated census-designated place in Miami-Dade County"),
        ("Area", "About 0.27 square miles in total, roughly 0.24 of it land"),
        ("2020 census", "561 residents"),
        ("Road access", "None. Private ferry or yacht, with security clearance arranged in advance"),
        ("Vanderbilt era", "Alva Base, a winter estate designed by Maurice Fatio for William K. Vanderbilt II"),
    ],
    "opening": "Fisher Island lies at the southeastern edge of Biscayne Bay. Government Cut runs between it and South Beach in [[city:miami-beach|Miami Beach]], and Norris Cut separates it from Virginia Key to the south. Early accounts describe a low tract of coconut palms and mangroves. In the late 1920s William K. Vanderbilt II acquired land here in exchange for his yacht and built a winter estate designed by Maurice Fatio. Residential development began in the early 1980s, and today palm-lined streets and tropical gardens run across the island.\n\nThat setting offers a honey bee swarm plenty of options. Roof tile, stucco trim, hollow palm trunks and buried irrigation boxes all hold the dark, dry space a colony wants. The bees arrive by air. Anyone who comes to remove them arrives by water, cleared in advance. This page covers both halves: where colonies settle on the island, and how a live removal is lined up so the crossing costs as little time as possible.",
    "hotspots_h": "Where bees move in, from roofline to dock",
    "hotspots": [
        ("Barrel tile roofs", "Where a roof is finished in curved tile, open tile ends at the eave and gaps under the ridge lead into a warm, sheltered void, and a colony can spread comb across several courses before bees are noticed at the gutter. See [[svc:roofs|tile roof hives]]."),
        ("Palm crowns and trunks", "Palms fill the island's landscaping. Hollowed trunks, rotted frond bases and thick skirts of dead fronds give a swarm cover, and bees working a palm over a pool deck or path put people underneath at risk. More on [[svc:trees-palms|palm and tree colonies]]."),
        ("Stucco walls and trim", "Stucco over masonry looks sealed, yet weep holes, gaps around light fixtures and hose bibs, and voids behind decorative trim all let bees in. Comb behind a finished wall has to be located before anything is cut, which is why we bring a thermal camera."),
        ("Balconies and terraces", "On a multistory condominium building, a swarm may land on a railing, a planter or an air conditioning chase. Work that high is planned with the building manager, usually from inside the unit, with the facade below protected. See [[svc:condos-high-rises|condo and high-rise work]]."),
        ("Irrigation and valve boxes", "Landscaped grounds depend on buried valves and in-ground boxes. Bees in a box at ankle height get disturbed by mowers and feet, and often the lid is the only giveaway. Our [[svc:utility-boxes|meter and valve box]] page explains the fix."),
        ("Docks and idle boats", "An island reached only by ferry or yacht has a working waterfront. Dock boxes, furled canvas covers and a vessel left unused for the season can each shelter a small colony, which has to come out without marking gelcoat or upholstery."),
    ],
    "streets_h": "Notes for different parts of the island",
    "streets": [
        ("The Government Cut side", "The island's northern shore faces Government Cut and South Beach across the channel. Waterfront terraces, dock storage and seawall plantings on this side are worth a look whenever bees keep turning up near the water."),
        ("The Vanderbilt-era estate", "Maurice Fatio designed the winter estate William K. Vanderbilt II built on the island. On any building of that age, entry points are opened carefully and closed with materials that match the original."),
        ("Palazzo del Mare and Palazzo Della Luna", "These are two of the island's residential buildings. Bees on an upper balcony or behind a parapet are handled with the building manager, and proof of insurance reaches the office before any common-area work begins."),
        ("Norris Cut and the south shore", "Norris Cut divides the island from Virginia Key, and mangroves grow along parts of the seawall. Thick shoreline vegetation can hide a swarm resting low, so the area around it is checked before anyone starts trimming."),
        ("Palm-lined streets and gardens", "The planting includes coconut palms, lady palms, saw palmetto, sea grape and gumbo limbo. Dense clumps of palm and shrub make a shaded spot for a resting swarm, and a hollow trunk can hold a settled colony at head height beside a path."),
        ("Fisher Island Day School", "The island's private school serves preschool through eighth grade. Bees near a playground or entrance are a priority, and the work can be timed around drop-off and outdoor periods with the school's staff."),
    ],
    "body": [
        ("Gates keep out people, not bees", "Honey bees reproduce by swarming. A crowded colony raises a new queen, and the old queen leaves with thousands of workers to look for a new home. The swarm hangs on a branch, railing or hedge for a few hours or a few days while scouts inspect cavities nearby, then the whole cluster flies to the one they choose. A channel of open water is no barrier to that flight, and the island's own palms and buildings can host colonies that later swarm themselves. A cluster in the open is the simple case: it can be boxed and taken off the island alive, as described on our [[svc:swarms|swarm pickup]] page. The harder case is a colony that has already moved into a roof or wall and begun building comb. If a few dozen bees keep inspecting the same crack in your tile for several days, those are probably [[guide:scout-bees|scouts sizing up a home]], and calling then can save a wall."),
        ("Clearance comes before the crossing", "No road or causeway reaches Fisher Island, and visitors arriving by ferry need security clearance arranged ahead of time. A bee crew is no exception, and that changes the order of the job. Our 24-hour response guarantee runs from your call, which is picked up at any hour, and the clearance gets started right away. A photo or a short description lets us load the right equipment for the first trip, because a missing ladder or vacuum means another crossing. If you live on the island, tell your security desk or manager that a bee crew is expected. If you manage property here, we send whatever paperwork your office or the community association asks for."),
        ("Tile, stucco and a repair that matches", "Removing a colony that has lived inside a roof or wall means opening the space, cutting out every comb and sealing what remains so returning scouts find nothing to reuse. Every cut into a Fisher Island facade has to be closed so well that nobody can find it later. [[guide:thermal-imaging|Thermal imaging]] shows the warm mass of a colony behind stucco or under tile, so the opening goes in the right place and stays small. Our own licensed roofers reset or replace barrel tile, and our own painters patch and color-match stucco, so you are not clearing a second company to come across. Honey and wax left behind draw ants, rodents and new swarms, so [[svc:honeycomb-cleanup|comb and honey cleanup]] is part of the work. Should bees ever work their way back into an opening we closed, the warranty on our workmanship sends the crew across the bay again. Lingering wax scent is a big part of [[guide:why-bees-come-back|why a sealed site attracts new bees]]."),
        ("Paperwork for boards, managers and absent owners", "If your home on the island sits empty for part of the year, a colony can grow for months in a closed villa before anyone notices. A short checklist for [[guide:second-home|keeping watch on an empty house]] helps an estate manager between owner visits, and the notes on [[guide:after-a-storm|hives torn open by high wind]] say what to look for after hurricane season weather. Condominium boards and the association get a COI from us, made out to whatever names the office specifies, since we carry both a license and insurance. Ask and you will receive pictures at each stage along with an invoice that breaks out every line item. Pricing tracks the difficulty. Bees that can be reached from the ground, like a cluster hanging from a shrub, tend to fall around $300 to $400. When the colony sits inside tile or behind stucco and our trades must open and rebuild the spot, the total climbs into the thousands. A callout after dark or on a weekend carries a higher rate than a Tuesday morning appointment. The [[page:cost|cost page]] explains the rest."),
    ],
    "band": ("Bees on the island right now?", "A quick call, or a snapshot of the cluster sent from your phone, gets the island clearance moving while the crew packs for the crossing."),
    "visit_h": "How a Fisher Island visit runs",
    "visit": [
        ("Photo and a plan", "Send a picture from your phone showing the cluster or the gap they use. From that we judge the type of job, give a likely price and pick a date that works for you."),
        ("Clearance before the trip", "We arrange security clearance for the crew ahead of the crossing and confirm with your security desk or manager, so arrival and the gate check go smoothly."),
        ("Removal and relocation", "On the island the crew locates the colony, with a thermal camera if it is hidden, takes out bees and comb alive and boxes them for a beekeeper on the mainland."),
        ("Seal, repair, document", "Openings are sealed and tile or stucco is repaired by our own trades. Ask for pictures and a line-by-line invoice if your office files them, and the warranty stands behind each closed opening."),
    ],
    "alarm": "Stings come first. Lead the person inside or into a closed car and scrape the stingers off the skin with a card edge. If breathing gets hard, the lips or tongue puff up, or the stings are many, dial 911 and let island security know as well. Next, call us for [[svc:emergency|emergency bee removal]] and keep everyone, pets included, far from the bees.",
    "faqs": [
        ("Can a crew reach Fisher Island quickly if bees are swarming near my unit?", "Our line is staffed day and night, and an island address gets the identical 24-hour response guarantee a mainland street does. Clearance is the part that can stretch things, since every visitor is cleared before crossing. Letting your security desk or manager know early helps. If anyone is being stung, call 911 first."),
        ("Do I have to arrange the ferry for your crew?", "No. We handle our own clearance and crossing. What helps most is telling your security desk that a bee removal crew is expected and confirming who will meet us at the unit, villa or common area."),
        ("Are the bees killed, or do they leave the island alive?", "They leave alive. The colony is gently vacuumed or cut out along with its comb, boxed, and carried off the island to a beekeeper who will keep it. Nothing is sprayed. Our [[svc:relocation|colony relocation]] page follows the bees from your roof to their new hive."),
        ("Can you match the barrel tile and stucco on my building?", "Repairs are done by our own licensed roofers and painters rather than handed to another company. They reset original tile wherever it can be saved, fit replacement tile where it cannot, and patch and color-match stucco. Photos of the finished work are available on request for your association or owner."),
        ("Will a COI request from the community association hold up the ferry crossing?", "No. The COI goes to the association or building manager before the job, worded the way that office asks. That paperwork goes out with the clearance request, so both are finished before anyone boards. Start with the [[page:quote|removal request form]]."),
    ],
    "services": [
        ("roofs", "Open tile ends and ridge gaps on a barrel tile roof lead bees into the void below."),
        ("trees-palms", "Palm crowns and hollow trunks in the island's planting hold swarms and settled colonies alike."),
        ("condos-high-rises", "Balconies, parapets and chases on condominium buildings need planning with the building manager."),
        ("hoa-commercial", "Association common areas and landscaped grounds, with a COI delivered before the crew arrives."),
        ("waterfront-boats", "Dock boxes, boat covers and idle vessels on an island reached only by water."),
        ("repairs", "Tile and stucco put back by our own roofers and painters once the colony is out."),
    ],
    "nearby": ["miami-beach", "miami", "key-biscayne"],
    "close": ("Put the bee crew on the list", "Fill in the quote form or send a picture, and we will handle the island clearance, the crossing and the bees. Other islands and neighborhoods are on our [[page:county|Miami-Dade service map]]."),
    "card": "A private island reached only by ferry or yacht. Live removal from tile roofs, palms and condo balconies, with crew clearance arranged before the crossing.",
    "facts": [
        "Fisher Island is an unincorporated census-designated place in Miami-Dade County on an island of the same name; incorporation was considered in 2000 and 2005 but did not happen (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "Total area 0.267 square miles, of which 0.241 is land; 2020 census population 561 (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "No road or causeway connection; accessible only by yacht or private ferry, and ferry guests need pre-arranged security clearance (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "Lies at the southeastern edge of Biscayne Bay; Government Cut separates it from South Beach and Norris Cut from Virginia Key to the south (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida ; https://en.wikipedia.org/wiki/Government_Cut)",
        "Early landscape described as a low-lying tract of coconut palms and mangroves; mangroves grow along portions of the seawall; palm-lined streets and gardens include coconut palm, lady palm, saw palmetto, sea grape and gumbo limbo (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "In the late 1920s William K. Vanderbilt II acquired island land in exchange for his yacht Eagle and built a winter estate, Alva Base, designed by Maurice Fatio (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida ; https://en.wikipedia.org/wiki/William_Kissam_Vanderbilt_II ; https://en.wikipedia.org/wiki/Maurice_Fatio)",
        "Residential development began in the early 1980s (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "Palazzo del Mare and Palazzo Della Luna are residential buildings on the island (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida image caption and references)",
        "Fisher Island Day School is a private school, preschool through eighth grade (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
        "The Fisher Island Community Association is the island's community association (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
    ],
}
