# -*- coding: utf-8 -*-
"""Golden Beach page copy."""

CITY = {
    "key": "golden-beach",
    "title": "Golden Beach Bees: Estates, Seawalls and One Way In",
    "desc": "One guarded road, a private beach, tile roofs and docks: live honey bee removal for Golden Beach estates, repaired by our own crew. Free quote.",
    "h1": "Honey bees on a Golden Beach estate, taken out alive",
    "kicker": "North Dade oceanfront town",
    "lede": "A mile of single-family homes between the Atlantic and the Intracoastal, one guarded way in, and big houses with plenty of quiet cavities. This page walks through getting a colony out alive and the wall put back.",
    "quick": "Bee removal in Golden Beach starts with a close-up picture of the entry hole, sent by text, or a phone call. Every colony leaves alive, boxed for a beekeeper's yard, and no poison is used. A swarm or hive you can reach from the ground typically runs $300 to $400. Comb sealed behind stucco or under roof tile pushes the price higher, since the opening is rebuilt afterward by licensed tradespeople on our payroll. Even at 3 a.m. a person takes your call, and a 24-hour response guarantee covers Golden Beach as fully as [[page:county|anywhere in the county]].",
    "glance": [
        ("Incorporated", "May 23, 1929, by special act of the Florida Legislature"),
        ("Size", "About one mile north to south and four blocks across"),
        ("Housing", "Single-family homes only; the charter bars commercial use and high-rise condos"),
        ("Beach", "A mile and one-eighth of private beach for residents and their guests"),
        ("Getting in", "One road in from State Road A1A, past a police guardhouse"),
    ],
    "opening": "Golden Beach is small enough to walk end to end in twenty minutes and private enough that every visitor is noticed. The town has a single road in from State Road A1A, a police guardhouse at that entrance, and a charter that keeps out shops, hotels and condo towers. What fills the mile between the county line and its southern edge is houses, most of them on the ocean, the Intracoastal or one of the canals. Its only Miami-Dade neighbors are [[city:sunny-isles-beach|Sunny Isles Beach]] to the south and [[city:aventura|Aventura]] across the Intracoastal to the west.\n\nFor a honey bee scout, that is a lot of good real estate. Large homes have long rooflines, deep soffits, hollow columns and equipment rooms, and a house left closed for a few weeks gives a colony time to settle in. Waterfront lots add dock boxes, seawall gaps and pump housings. Salt air and sun break down caulk and screen faster here than they do inland, so small openings appear on their own. A swarm needs only a gap about the width of a pencil to move in. Once comb goes up behind a wall, the colony will not leave without help, and the job turns from a pickup into a careful opening, removal and rebuild.",
    "hotspots_h": "The cavities a scout picks on an estate lot",
    "hotspots": [
        ("Roof tile and the eave line", "Barrel and flat tile leave hollow channels at the ridge and along the eaves. A colony can build comb in that space for months before anyone notices more than a steady line of bees at one corner of the roof. Our [[svc:roofs|tile roof hive]] page covers the lift-and-reset work."),
        ("Soffits on two-story houses", "Tall eaves with vented soffit panels are hard to inspect from the ground. A loose panel or a gap where the soffit meets the wall gives bees a dry, shaded cavity well above the pool deck, the classic case for [[svc:soffits-eaves|soffit and eave removal]]."),
        ("Docks, lifts and seawall gaps", "On the Intracoastal and canal lots, bees move into dock storage boxes, boat lift housings and voids where a seawall cap has cracked. These need a calm approach because people walk right past them to reach the boat; see [[svc:waterfront-boats|docks and seawalls]]."),
        ("Palms and landscaped beds", "Mature palms with hollow trunks or heavy boot growth, plus irrigation valve boxes buried in the beds, are natural cavities. The person most likely to stumble on one is whoever trims the hedge, so warn your landscaper. [[svc:trees-palms|Palm colonies]] come out with the tree left standing."),
    ],
    "streets_h": "Notes on the parts of town",
    "streets": [
        ("Oceanfront lots", "Houses set directly on the Atlantic take the full force of wind and salt spray. Expect worn sealant around windows, roof flashing and stucco joints, and keep an eye on the ocean side of the house, which is the hardest to see from the drive."),
        ("Ocean Boulevard", "Town Hall sits at 100 Ocean Boulevard, and the early land sales priced Ocean Boulevard plots apart from the oceanfront ones. Before arriving we settle where the van parks, so it does not block a neighbor's gate."),
        ("The west-side islands", "The town's history describes three islands on the Intracoastal side of town, each with its own bridge. Water on several sides means seawalls, docks and lifts, and a colony on one lot can be a short flight from the next house."),
        ("The Italian-named avenues", "Terracina, Verona, Ravenna, Palermo, Navona and Massini Avenues carry the Italian names the town gave its streets in its early years. Older homes along them are worth a look at the roofline and any decorative trim."),
        ("The Beach Pavilion and parks", "The Mediterranean Revival pavilion, the chickee huts and the town's nine parks belong to the town, and its Public Works crews look after the trees there. Report bees in those spots to Town Hall."),
    ],
    "body": [
        ("Why big, quiet houses suit honey bees", "Scouts rate a site on darkness, dryness, volume and a narrow doorway they can defend, and they favor spots that stay undisturbed. Large houses on streets that see little outside traffic tick every box. There are more square feet of soffit, more roof valleys, more hollow decorative trim and more mechanical spaces, and fewer people walking past each one.\n\nThat is why a hive here can grow large before anyone reports it. If the home sits empty for part of the year, read our note on [[guide:second-home|bees at a seasonal home]], and ask a house manager to watch for a few [[guide:scout-bees|scout bees]] circling one spot in spring. Catching a swarm before it builds comb keeps the bill near the low end. The same logic applies to other quiet enclaves such as [[city:key-biscayne|Key Biscayne]] and [[city:fisher-island|Fisher Island]]. Once comb is in a wall or a roof, it has to come out completely, or the leftover wax and honey draw new bees back to the same spot. The scent of old comb is the main reason, as [[guide:why-bees-come-back|this field guide note]] lays out."),
        ("Finding the hive without opening the wrong wall", "On a house finished in custom stucco, stone or painted millwork, you do not want anyone guessing. A brood nest runs warmer than the framing around it, and a thermal camera shows that heat as a bright shape behind finished stucco or a ceiling. That lets the cut go exactly where the comb sits, and keep it small. Our page on [[guide:thermal-imaging|what thermal imaging shows]] covers how that works.\n\nThe removal itself is done by hand. Comb is cut out, the bees are drawn by a low-suction vacuum into a ventilated box, and a beekeeper takes them in to start over somewhere useful. Closing up is not handed to strangers: the stucco patch, tile reset and touch-up paint are done by licensed people who work for us, matched to what was there, which is the whole point of our [[svc:repairs|repairs after removal]]. If an owner abroad or a family office wants proof, we can send before-and-after pictures plus a line-by-line invoice."),
        ("Storm season, salt air and repeat visits", "Hurricanes and tropical storms can peel back roof tile, crack stucco and expose a hive that was hidden for years, here and down the barrier coast through [[city:bal-harbour|Bal Harbour]] and [[city:miami-beach|Miami Beach]]. If storm damage turns up comb, keep people back and read [[guide:after-a-storm|bee colonies exposed after a storm]] before anyone starts pulling debris.\n\nSalt air also wears down sealant faster near the water, so the gaps bees use can reopen on their own. Our workmanship carries a warranty, so should a colony ever reoccupy a repair we made, we return and deal with it. For a full breakdown of what drives the price, see [[page:cost|what removal costs]]."),
    ],
    "band": ("Bees near the pool deck right now?", "Get the kids and guests indoors, then call. A live voice answers at any hour, and anyone already stung is handled before the hive."),
    "visit_h": "How a visit runs in Golden Beach",
    "visit": [
        ("Clear us at the gate", "Every vehicle comes in past the police guardhouse at the town entrance. Let the guardhouse or your house manager know to expect us, with the date and our company name, so the van gets through without a wait."),
        ("Look before cutting", "We walk the property with you or your manager, trace the flight line, and scan the wall or roof with a thermal camera to estimate the hive's size and position."),
        ("Remove and relocate", "The colony and all comb come out by hand. The bees go to a beekeeper. Every scrap of comb leaves in sealed buckets with us, because a sweet residue would call in the next swarm."),
        ("Rebuild and sign off", "Stucco, tile or trim goes back up, done by tradespeople we employ. If the repair needs a town permit, it goes through the Building Department, which currently works by appointment and is closed on weekends."),
    ],
    "alarm": "Bees chasing and stinging? Walk fast to the nearest house or vehicle, shut yourself in, and pull stingers out by scraping. Do not jump into the pool or the Intracoastal to escape; bees wait at the surface. Call 911 for trouble breathing or many stings, then call us; [[svc:emergency|emergency removal]] puts you at the front of the line.",
    "faqs": [
        ("Should we tell the guardhouse you are coming?", "It helps. All traffic passes the police guardhouse at the town entrance, so let the guards know we are on the way, or ask your house manager to. A name and a time save a wait at the gate, and it matters most for a night or weekend emergency call."),
        ("We are away for months. Can you handle it without us there?", "Usually, as long as someone can let us onto the property and clear us at the guardhouse. A house manager, contractor or neighbor can meet us. We send photos of the hive and the repair, and an itemized invoice on request, so you can see the work from wherever you are."),
        ("There are bees in a palm at the Beach Pavilion. Who handles that?", "The beach, the pavilion and the town parks are town property, and Public Works maintains the trees there. Tell Town Hall or the beach attendants first. If a colony is on your own lot next to the beach, that one is yours, and we can take it out alive."),
        ("Will removing a hive from our roof damage the tile?", "Some tiles have to be lifted to reach the comb. Our own licensed roofers reset or replace them and seal the gap so bees cannot reuse it. If the same spot ever draws bees again after our repair, the warranty on our workmanship means a return trip."),
        ("Is it more expensive to call on a weekend?", "Yes. A Sunday-morning or midnight emergency is priced above the same job booked for a Tuesday. When nobody is in danger, waiting for a weekday keeps the price down. The quote is free either way, and you can read about [[page:cost|what moves the price]] before you call."),
    ],
    "services": [
        ("roofs", "Tile roofs on large homes leave long hollow runs along ridges and eaves where comb hides."),
        ("soffits-eaves", "Two-story houses have tall soffits that are hard to check from the ground."),
        ("waterfront-boats", "Most lots back onto the ocean, the Intracoastal or a canal, with docks, lifts and seawalls."),
        ("pool-enclosures", "Where a house has a pool, the pump room and enclosure make warm, quiet cavities."),
        ("repairs", "Custom stucco, tile and painted trim need a matched repair after the comb comes out."),
        ("trees-palms", "Mature palms in landscaped yards hold colonies in hollow trunks and dense boots."),
    ],
    "nearby": ["sunny-isles-beach", "aventura", "north-miami-beach"],
    "close": ("Show us the hole they use", "Text a photo or send the [[page:quote|quote form]] with your address and the gate details, and we will plan the visit around your property."),
    "card": "A mile-long, single-family oceanfront town with one guarded entrance, tile roofs, docks and seawalls where honey bees move in quietly.",
    "facts": [
        "Golden Beach was incorporated by a special act of the Florida Legislature and became a legal community on May 23, 1929 (source: https://goldenbeach.us/history-of-golden-beach/)",
        "The town is about one mile north to south and four blocks east to west, on a barrier island between the Intracoastal Waterway and the Atlantic Ocean (source: https://en.wikipedia.org/wiki/Golden_Beach,_Florida)",
        "Golden Beach borders Sunny Isles Beach to the south and Aventura to the west; its northern boundary is the county line (source: https://en.wikipedia.org/wiki/Golden_Beach,_Florida)",
        "A1A is the only road into town, and a police guardhouse stands at the community entrance (source: https://en.wikipedia.org/wiki/Golden_Beach,_Florida)",
        "The town is single-family homes; the Town Charter protects it from commercial activity of any kind and forbids high-rise condominiums (source: https://goldenbeach.us/about/)",
        "Golden Beach has a mile and one-eighth of private beach, a historic Beach Pavilion and 9 parks; its homes are mostly on the Intracoastal and its waterways or directly on the Atlantic (source: https://goldenbeach.us/about/)",
        "Beach Park users must be town residents with ID, a maximum of eight guests are allowed per household, the beach has chickee huts, and Beach Attendants work the beach and pavilion (source: https://goldenbeach.us/wp-content/uploads/2025/06/BEACH-AREA-Rules-and-Regulations-v6-26-2024.pdf)",
        "The Beach Pavilion, built in 1924 and first called the Florentine Loggia, is in an Italian-influenced Mediterranean Revival style (source: https://goldenbeach.us/history-of-golden-beach/)",
        "Avenues were given Italian names, including Terracina, Verona, Ravenna, Palermo, Navona and Massini Avenues; the west side of town on the Intracoastal encompassed three islands, each with a separate bridge (source: https://goldenbeach.us/history-of-golden-beach/)",
        "Original oceanfront plots and Ocean Boulevard plots were sold at different prices (source: https://goldenbeach.us/history-of-golden-beach/)",
        "Town Hall is at 100 Ocean Boulevard (source: https://goldenbeach.us/police-department/)",
        "Public Works Department employees maintain all trees and landscaping on Town property and public parks (source: https://goldenbeach.us/public-works/)",
        "The Building Department serves customers by appointment only until further notice and is closed on weekends (source: https://goldenbeach.us/building-and-zoning/)",
    ],
}
