# -*- coding: utf-8 -*-
"""Hialeah page copy."""

CITY = {
    "key": "hialeah",
    "title": "Bee Removal Hialeah: Block Walls, Meter Boxes, Tight Lots",
    "desc": "Hialeah colony inside hollow block, under a curbside meter lid or behind a shop door? Live removal to beekeepers, 24/7 phones, free quote.",
    "h1": "Live Bee Removal for Hialeah's Close-Set Blocks",
    "kicker": "Hialeah, the west side",
    "lede": "In a city packed at roughly 10,300 people per square mile, one colony in one wall quickly becomes the whole block's concern. Here is how a live removal goes in Hialeah, from your first photo to the patched opening.",
    "quick": "Yes. Honey bees nesting in a Hialeah home, storefront or yard can be lifted out alive and given to a beekeeper. The comb is located first, by thermal scan if it sits inside block, then cut out along with the bees. Afterward the gap gets closed and rebuilt by our own licensed contractors, so no new swarm finds it. Expect about $300 to $400 for easy ground-level work, and far more, sometimes thousands, when a wall or roof needs rebuilding. Ring at 3 a.m. or noon and a person answers; a crew is promised to you under our 24-hour response guarantee.",
    "glance": [
        ("Incorporated", "September 10, 1925"),
        ("Population", "223,109 counted in 2020; ranks sixth statewide"),
        ("Density", "About 10,300 people per square mile"),
        ("Western edge", "The Miami Canal, with Medley on the far bank"),
        ("Street grid", "Numbered on its own East and West system, separate from the county's"),
    ],
    "opening": "Hialeah began as open prairie. Glenn Curtiss and James H. Bright drew up the first plat in 1921, the city incorporated in 1925, and the population climbed from about 1,500 that year to 223,109 at the 2020 census. That growth filled the prairie with houses, shops and factory floors, and it left very little space between them.\n\nFor honey bees, that crowding cuts two ways. A swarm looking for a home finds endless choices within a short flight: hollow block, curbside meter boxes, eaves, stacked pallets behind a shop. For you, it means a colony rarely stays a private problem. Forager traffic crosses fences, lands in the next yard's pool and circles the neighbor's car. Taking the bees out alive, and closing the gap so another swarm does not move in, protects the street as much as your own wall. The notes below follow the city's own layout, from the racetrack grounds on the east side to the canal on the west.",
    "hotspots_h": "Where colonies settle on Hialeah property",
    "hotspots": [
        ("Hollow block walls", "Cement blocks appear on a UF extension list of the small spaces African honey bees will occupy. A crack in stucco, a missing mortar joint or an old pipe hole opens into a hollow core, and the comb can run along the wall well past the hole you can see."),
        ("Decorative screen walls", "Miami-Dade's preservation office notes concrete block screen walls on postwar houses across the county. The open patterns give scouts plenty of ways in, and the hollow block framing them can hold comb, so a front porch wall or a carport divider can hide a colony in plain view."),
        ("Curbside meter boxes", "Water meter boxes are named by the same university source as a nesting site. On a crowded block the box sits beside a sidewalk, a driveway and a mailbox, so the lid is easy to step on or bump before anyone notices the bees under it."),
        ("Eaves and window frames", "Soffit vents, loose fascia and the gaps around older jalousie windows, another postwar feature the county describes, give bees a dry space above head height. Flight in and out of one spot at the roofline is the sign to look for."),
        ("Shop and warehouse yards", "Commercial and industrial lots hold stacked pallets, old tires, idle equipment and roll-up door housings. The UF list of nest sites includes old tires and barbecue grills, and any sheltered cavity left alone can take a swarm."),
    ],
    "streets_h": "Notes from around the city",
    "streets": [
        ("Around Hialeah Park", "The old racetrack covers about 40 square blocks between Palm Avenue and East 4th Avenue, from East 22nd to East 32nd Street. Its flamingo flock made it famous enough for the Audubon Society to name it a sanctuary for the American Flamingo. Landscaped grounds that size give foragers plenty to work, so a few bees at your flowers do not always mean a nest in your wall."),
        ("Palm Avenue and the old core", "A 1921 photo already shows Palm Avenue meeting County Road, today U.S. 27, and the city's planning and zoning office sits on Palm Avenue now. Older buildings near that first crossroads are worth checking for worn stucco and gaps scouts can test."),
        ("The U.S. 27 side", "U.S. 27 runs parallel to the border with [[city:miami-springs|Miami Springs]], where a canal marks that city's edge. Expect traffic and limited curb space, so tell us where a truck can stop without blocking a lane."),
        ("The Miami Canal edge", "The Miami Canal forms Hialeah's line with Medley and [[city:hialeah-gardens|Hialeah Gardens]]. Medley's tax base is mostly industrial, so the far bank is yards and plants rather than houses. Water and open banks are a draw for foraging bees."),
        ("West 49th Street and Westland Mall", "Westland Mall, at 1675 West 49th Street, opened in 1969 and has more than 100 stores. Big commercial roofs, rooftop units and planted islands in surface lots give bees spots that a store manager may never walk past."),
        ("The north edge by Amelia Earhart Park", "Just north of the city, in unincorporated county land, Amelia Earhart Park covers 515 acres of lakes, trails and the Bill Graham Farm Village. Homes along that edge sit beside a large stretch of green space."),
    ],
    "body": [
        ("Why one colony is everyone's problem here", "In 2010 Hialeah ranked tenth in population among U.S. cities with more than 10,000 people to the square mile. On blocks like that, the bees living in your wall forage well past your fence and across the yards around you. They drink from the neighbor's pool and fly past the car parked by the fence. That is why we suggest a quick word with the people next door before the visit, especially if a child or anyone with a sting allergy lives there.\n\nIt also explains why sealing matters as much as removal. Comb and the scent it leaves behind tell the next swarm that a cavity is worth moving into, and with so many houses close together, a new colony does not have far to come. Our [[guide:why-bees-come-back|guide to repeat colonies]] explains the cycle. Every job ends with the entry closed off, and that seal carries a workmanship warranty: should a colony show up again at the same patch, the crew returns. Tenants and owners sorting out responsibility can start with [[guide:renters-and-landlords|our renting page]]."),
        ("Block, stucco and the small-cavity problem", "UF's extension guide on African honey bees makes two points that fit this city closely. Those bees nest in much smaller spaces than European honey bees, including cement blocks and water meter boxes, and they guard a bigger zone around their comb. Since nobody can tell from looking which kind is in your wall, every colony gets treated as if it might be defensive.\n\nInside hollow block, the comb follows the cores sideways and up, so the hole you see is a poor guide to where the colony actually sits. A thermal camera picks up the warm spot the cluster makes on the wall surface, which lets the crew open the smallest section that reaches all of it; [[guide:thermal-imaging|the infrared article]] walks through a sample image. Once the cavity is empty, the block is filled, restuccoed and painted by our in-house licensed trades, and the [[svc:walls|block wall removal page]] goes through that repair in detail. For a curb box, see [[svc:utility-boxes|meter and valve boxes]]."),
        ("Shops, warehouses and industrial lots", "Manufacturing and cloth industries made Hialeah an industrial city in the 1970s and 1980s, and its shops, warehouses and work yards still give bees plenty of places to settle. On those lots the colony is often in a pallet stack, a dead piece of equipment, a sign cabinet or the box over a roll-up door. Removal has to fit around deliveries, forklifts and staff who cannot simply stay indoors all afternoon.\n\nTell us the hours the yard is quiet and who holds the keys. Property managers and landlords can get a certificate of insurance before the crew arrives, and the job file can include photos of the work and an invoice broken out by task, whenever you ask. If nobody on site is at risk, booking Monday through Friday daytime saves money, because a Saturday or late-night emergency run is priced higher. The [[svc:hoa-commercial|commercial and property manager page]] covers paperwork, and the [[svc:sheds-garages|outbuildings page]] covers storage sheds and detached garages."),
    ],
    "band": ("Bees in a block wall on your street?", "Snap the hole where the traffic goes in, from wherever you can stand safely, and send it over for a straight read on scope."),
    "visit_h": "How a Hialeah visit runs",
    "visit": [
        ("Give the East or West address", "Hialeah numbers its streets on its own grid, so East 4th Avenue and West 4th Avenue are two different streets. Include the direction and the cross street so nobody ends up at the wrong side of town."),
        ("Plan the curb", "Tell us whether the truck can use your driveway or must park on the street, and whether the block gets heavy traffic. On tight lots that decides where gear and the bee box go."),
        ("Warn the neighbors", "Bees get stirred up while the comb comes out. A heads-up lets the people next door keep children, pets and laundry inside for that stretch."),
        ("Paperwork and the patch", "Businesses and associations get the certificate of insurance first. Once the colony is out, our crew rebuilds the block or eaves, and pictures and a detailed bill go to whoever needs them."),
    ],
    "alarm": "When a person is under attack at this moment, get away from the nest in a straight line, cover your face with your shirt and get inside a car or building. Do not stand and swat. Call 911 for many stings or any allergic reaction, then call us; people being stung come first.",
    "faqs": [
        ("The bees are in my neighbor's wall but fly into my yard. What can I do?", "Talk to the owner first, since the work happens on their property. If they agree, either of you can call and get a free quote. Renters should bring in the landlord. If someone is being stung, call right away and we will sort out ownership afterward."),
        ("Does it matter that Hialeah has its own street numbering?", "Yes. The city's grid runs separately from the rest of the county, with East and West avenues and streets. Give the full address with the direction and a nearby cross street, or send a map pin with your photo, so the crew reaches the right block."),
        ("Can bees come out of a concrete block wall without tearing it down?", "Usually only a small section is opened. A thermal scan shows where the comb sits inside the hollow cores, the crew cuts the least block and stucco needed to reach it, and our own contractors rebuild and paint the patch. Larger repairs can push the cost into the thousands."),
        ("Are the bees around Hialeah Africanized?", "University of Florida entomologists report African honey bees in Florida, and they cannot be told apart from other honey bees easily by sight. That is why every colony is approached carefully and why you should keep people and pets away from the nest until it is gone."),
        ("Can you remove a colony at a warehouse without shutting us down?", "Often, yes. Tell us when the yard is quietest, and the crew works around deliveries and staff. Your property manager can have our insurance certificate on file before day one. After-hours and weekend calls cost more, so plan a weekday if the bees are not near people."),
    ],
    "services": [
        ("walls", "Hollow block and stucco walls let comb spread out of sight, and a thermal scan finds it before anything is cut."),
        ("utility-boxes", "Curbside water meter boxes sit beside sidewalks and driveways on crowded blocks, where lids get stepped on."),
        ("soffits-eaves", "Bees working one spot at the roofline usually mean comb behind a soffit vent or loose fascia."),
        ("hoa-commercial", "Shops, warehouses and rental owners need insurance certificates, invoices and a schedule around business hours."),
        ("swarms", "A cluster hanging on a fence or palm is a swarm resting before it picks a cavity, so call before it moves in."),
    ],
    "nearby": ["miami-lakes", "hialeah-gardens", "miami-springs", "miami", "doral"],
    "close": ("Tell us what is flying around your block", "Send the quote form or call, and include the East or West address so we can route the crew."),
    "card": "A crowded city of block walls, curb meter boxes and industrial yards, where one colony affects a whole street and sealing the opening matters.",
    "facts": [
        "Hialeah was incorporated on September 10, 1925; the city sits on a large prairie (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Glenn Curtiss and James H. Bright developed Hialeah in 1921; the first plat was drawn up in 1921; population 1,500 in 1925 (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "2020 census population 223,109; sixth-largest city in Florida; density about 10,338 per square mile; in 2010, tenth-largest US city among cities above 10,000 per square mile; surrounding areas include Miami Lakes (north), Hialeah Gardens, Medley and Miami Springs (west) and Miami (south) (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Hialeah has its own street grid numbered separately from the rest of the county (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Manufacturing and cloth industries made Hialeah an industrial city in the 1970s-1980s (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Palm Avenue and County Road (now U.S. 27) intersection pictured in 1921 (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "City Planning and Zoning Division is at 501 Palm Avenue (source: https://www.hialeahfl.gov/182/Planning-Zoning)",
        "Hialeah Park covers 40 square blocks from Palm Avenue east to East 4th Avenue and East 22nd to East 32nd Street; designated by the Audubon Society a sanctuary for the American Flamingo because of its flamingo flocks; landscaped grounds and infield lake (source: https://en.wikipedia.org/wiki/Hialeah_Park_Race_Track)",
        "The Miami Canal forms the border between Medley and Hialeah and Hialeah Gardens; Medley's tax base is mainly industrial (source: https://en.wikipedia.org/wiki/Medley,_Florida)",
        "U.S. Route 27 runs parallel to the Miami Springs/Hialeah border; the Miami River canal forms Miami Springs' northern/eastern boundary (source: https://en.wikipedia.org/wiki/Miami_Springs,_Florida)",
        "Westland Mall is at 1675 West 49th Street, Hialeah, opened summer 1969, over 100 stores (source: https://en.wikipedia.org/wiki/Westland_Mall_(Florida))",
        "Amelia Earhart Park is a 515-acre county park in unincorporated Miami-Dade just north of Hialeah, with lakes, bike trails and Bill Graham Farm Village (source: https://en.wikipedia.org/wiki/Amelia_Earhart_Park)",
        "Postwar minimal traditional and ranch houses in Miami-Dade featured jalousie windows and concrete block screen walls (source: https://www.miamidade.gov/global/economy/historic-preservation/county-architectural-history.page)",
        "African honey bees nest in smaller volumes than European bees, including water meter boxes, cement blocks, old tires, house eaves and grills; they defend a larger radius; present in Florida; not easily distinguished from European honey bees; victims should run, cover head and airways with shirt, seek a bee-proof vehicle or structure and not stand and swat (source: https://ask.ifas.ufl.edu/publication/IN790)",
    ],
}
