# -*- coding: utf-8 -*-
"""Key Biscayne page copy."""

CITY = {
    "key": "key-biscayne",
    "title": "Key Biscayne Bees: Towers, Seawalls and One Causeway",
    "desc": "Honey bees in a Key Biscayne condo, raised house or bayfront seawall? Live removal, COIs for boards, and a crew that plans around the causeway.",
    "h1": "Honey bees on Key Biscayne, from beach towers to bayfront lots",
    "kicker": "Village of Key Biscayne, island calls",
    "lede": "An island village with one road to the mainland, a wall of oceanfront condominiums and a grid of raised houses behind them. Here is how a live bee removal works on that ground.",
    "quick": "Bees settling into a balcony planter, a pool equipment pad or the gap under a raised slab on Key Biscayne can come out alive and go to a beekeeper's yard. Call or text us a photo and you get a free quote. A crew crosses the Rickenbacker Causeway under a 24-hour response guarantee, finds the comb (with thermal imaging if it is hidden), removes it, and has our own contractors seal and repair the opening so the spot stops drawing new swarms.",
    "glance": [
        ("Incorporated", "June 18, 1991, as a village"),
        ("Homes", "About 7,207 units: 1,296 single-family, 5,911 multi-family"),
        ("Road to the mainland", "Rickenbacker Causeway, the only route, opened in 1947"),
        ("Park at each end", "Crandon Park to the north, Bill Baggs Cape Florida to the south"),
        ("Residents", "14,809 at the 2020 census"),
    ],
    "opening": (
        "Key Biscayne is a barrier island that hangs off the mainland by a single causeway, and the village sits in the middle of it, about 1.25 square miles squeezed between two large parks. "
        "Crandon Park fills the north end and Bill Baggs Cape Florida State Park takes roughly the southern third, so open land with old trees, hammock and mangrove edges lies on both sides of every street in town.\n\n"
        "Inside the village limits, the housing splits cleanly. More than 5,900 of the roughly 7,200 homes are in multi-family buildings, most of the tall ones lined up along the beach. "
        "West of Crandon Boulevard the island turns into a grid of single-family lots, where small houses from the 1950s have been giving way to larger ones built up above flood elevation. "
        "A colony of honey bees has plenty of choices here: a hollow in a tower's mechanical space, a void in a new stem wall, a dock box on the bay. The rest of this page walks through those choices and what getting a crew onto the island involves."
    ),
    "hotspots_h": "Where a colony sets up on this island",
    "hotspots": [
        ("Oceanfront tower balconies",
         "High-rise units on the beach side have planter boxes, louvered air-handler closets and hollow railings. A swarm that lands on the 14th floor is still a job you can hand over, and the building may need a lift or roof access plan before anyone opens a wall."),
        ("Raised slabs and stem walls",
         "The whole village sits inside the 100-year floodplain, so new houses are built with the first floor at or above base flood elevation. The stem walls, vents and voids that make that height possible are dry, dark and protected, which is exactly what a scouting party wants."),
        ("Bayfront seawalls and docks",
         "Almost every lot on the Biscayne Bay side has a seawall. Bees move into dock boxes, boat lifts, the cap where a wall meets the yard and the cabinets on a covered dock. A colony on a boat that leaves the slip has to be handled before the next trip out."),
        ("Pool pads and equipment rooms",
         "Filter housings, heater cabinets and the slatted enclosures that hide them stay shaded and close to water. On big lots behind Harbor Drive those pads sit far from the house, so a colony can grow for weeks before anyone opens the gate."),
        ("Palms and old yard trees",
         "The island was a coconut plantation for much of the last century. Where a palm grows in a yard or swale today, bees can build in boot gaps under old fronds, in hollow trunks and in the crowns of trees that have taken storm damage."),
        ("Meter and irrigation boxes",
         "Ground-level boxes for water meters, valves and irrigation controllers line the swales on the single-family streets. A lid with a broken corner is all a small swarm needs, and the first person to find it may be a lawn crew or a meter reader."),
    ],
    "streets_h": "Notes by part of the village",
    "streets": [
        ("The beach condominium row",
         "Most of the higher-density buildings stand on the ocean side, and many hold 50 or more units each. Work here goes through management, so a COI and a scheduled window come before anyone touches the facade or the roof."),
        ("Ocean Drive to Crandon Boulevard",
         "Between Ocean Drive and the boulevard is a belt of medium-density apartments and condominiums. Shared walls and roofs mean one colony can affect several units, as on the condo blocks of [[city:miami-beach|Miami Beach]] and [[city:bal-harbour|Bal Harbour]], and the association decides who signs off on the opening and the repair."),
        ("The Crandon Boulevard corridor",
         "The boulevard runs the full length of the village and carries every car on and off the island. Retail sits mostly on its west side. Shops and offices here get bees in signage, rooftop units and planters, and a visit is timed around traffic and parking."),
        ("Village Green and McIntyre Street",
         "Village Hall sits on West McIntyre Street, and the village also runs the 9.5-acre Village Green with its fields and jogging path. Bees in a tree or fixture on public land should be reported to the village; a colony on your side of the property line is something you can book."),
        ("West of Fernwood Road",
         "Fernwood Road parallels Crandon Boulevard and marks the edge of the main single-family area. Original 1950s houses sit beside new raised ones, so a colony can be in an old wall cavity on one lot and under a fresh stem wall next door."),
        ("Harbor Drive and Hurricane Harbor",
         "Harbor Drive is the main collector street for the west side, and waterfront house lots around Hurricane Harbor tend to run past 15,000 square feet, most with a seawall and dock. Long yards mean a colony can hide far from the front door."),
    ],
    "body": [
        ("One causeway, and why it matters",
         "Every truck that reaches Key Biscayne comes over the Rickenbacker Causeway, across Virginia Key, which belongs to the City of [[city:miami|Miami]], over Bear Cut, then down Crandon Boulevard through Crandon Park. There is no back road. For you that means two things. First, a crew bringing a lift, a bee vacuum and repair materials has to load everything before it leaves the mainland, so a good photo or a clear description up front saves a second crossing. Second, beach traffic on a warm weekend can slow the boulevard, which is why a booked weekday slot is the calmest choice for a colony that is not hurting anyone.\n\n"
         "None of that changes the 24-hour response guarantee. If someone is being stung, that call goes to the front of the line, causeway or not, and our [[svc:emergency|emergency bee service]] covers the island the same as the mainland. Emergency trips at night or over the weekend are billed above the weekday rate, and the quote tells you which one you are paying for before anyone heads south."),
        ("Condominium buildings and their boards",
         "With most island homes in multi-family buildings, a large share of bee problems here start on a balcony or a roof that belongs to an association. If you live in one of those units, the useful first step is to tell the manager or front desk, then send us a photo. A COI, the insurance document most boards ask a vendor for, can go straight to the building so it is on file before the crew arrives.\n\n"
         "In a high-rise, the colony is rarely where the bees are flying. They may enter through a gap at a slab edge and build inside a chase or a ceiling that serves several units. Thermal imaging lets the crew trace the warm cluster before a single panel comes off, which keeps the opening small. Patching the slab edge, drywall or stucco falls to our own licensed tradespeople, and an itemized invoice with photos can go to the association for its records. Our [[svc:condos-high-rises|high-rise and condo service page]] goes deeper on building work."),
        ("Raised houses, old houses and the space between",
         "Most of the village sits 4 to 6.5 feet above sea level, while base flood elevations on the FEMA map run from 7 to 11 feet. New houses therefore go up on raised floors, and the gap between grade and the first floor becomes a new kind of cavity. Honey bees like a dry, enclosed space with one small entrance, and a vent or a cracked stucco joint at the base of a stem wall fits that well.\n\n"
         "The older 1950s houses that remain bring the opposite problem: seventy-odd years of small openings in soffits, roof edges and additions. In both cases, the comb has to come out, not just the bees. Honey and wax left in a wall draw the next swarm to the same spot, which is the whole subject of [[guide:why-bees-come-back|this field guide piece on return swarms]]. Our workmanship is warrantied, so a new colony in a cavity we closed means another trip over the bridge at our end."),
        ("Parks on both ends of the village",
         "Crandon Park covers 808 acres on the north end, with beach, a nature center, a marina and mangroves around Calusa Park. Bill Baggs Cape Florida State Park, home of the Cape Florida Light first built in 1825, was restored with native hammock after Hurricane Andrew knocked down its invasive Australian pines in 1992. That is a lot of wooded land next to houses, and any wooded land can hold wild colonies in hollow trees.\n\n"
         "In spring, colonies split and send out swarms, and a swarm that leaves the trees may stop on the nearest fence, mailbox or car. A clump hanging in the open may lift off by the next day, as soon as its scouts agree on a cavity; our [[svc:swarms|swarm pickup page]] and the guide to [[guide:scout-bees|scout bees]] explain the difference. If it is still there the next morning, or the bees start going into a wall, that is the time to call. Colonies inside park land are for the park to handle; anything on your property is ours to take out alive and pass to a beekeeper through our [[svc:relocation|colony relocation]] work."),
        ("When the house sits empty part of the year",
         "Plenty of island units and houses are lived in only part of the year. A home that stays closed through the summer gives scouts weeks of quiet to settle into a shutter box or an attic vent. If you are away, a property manager or neighbor can meet the crew, and we can send photos of the colony, the removal and the repair so you see the work without flying in. The field guide note on [[guide:second-home|colonies at a part-time residence]] has a short list of things to check before you leave and when you return. Pricing runs about $300 to $400 for a ground-level job, and up into the thousands when a tower facade or a raised slab needs opening and rebuilding; the [[page:cost|cost page]] breaks that down."),
    ],
    "band": ("A colony in a tower or a raised house?",
             "One clear picture of where the bees fly in lets us size the crew and the gear before the drive over."),
    "visit_h": "How a removal visit runs on Key Biscayne",
    "visit": [
        ("Photo and paperwork",
         "It starts with a picture of the entry point and the street address. For a condominium or association property, our COI goes to the manager and we agree on a time window the building accepts."),
        ("Over the causeway",
         "Before leaving the mainland, the crew loads the vacuum, protective gear, thermal camera and repair supplies, pays the southbound toll and drives the length of Crandon Boulevard to you."),
        ("Find, open and remove",
         "The thermal camera locates the comb behind stucco, a ceiling or a stem wall. The crew opens the smallest workable section, vacuums the bees, cuts out every piece of comb and cleans up the honey."),
        ("Seal, repair and hand off",
         "Our own contractors, roofers or painters close and refinish whatever was cut. The colony leaves the island with the crew and goes to a beekeeper, and you get photos and an itemized invoice on request."),
    ],
    "alarm": "Stings happening as you read this? Move people inside, close doors and windows, and call us. Do not spray the bees or block the hole, because that pushes them into the building or onto you. A sting victim whose lips or tongue puff up, or who starts wheezing, is an ambulance case before it is a bee case.",
    "faqs": [
        ("Do the causeway toll and beach traffic delay a bee visit to Key Biscayne?",
         "It shapes how the visit is planned, not whether it happens. Calls here get the same 24-hour response guarantee as anywhere else in the county, and anyone being stung is answered first. For a colony that is calm, a weekday slot keeps the trip simple and avoids the higher night and weekend emergency rate."),
        ("Our condo board wants insurance papers before any contractor works on the building. Can you provide them?",
         "Yes. We are licensed and insured, and the COI can be addressed to your association and sent to the manager ahead of the visit. Photos and an itemized invoice can follow the job so the board can close it out in its own records."),
        ("We just built a raised house. How did bees get underneath it so fast?",
         "A raised floor leaves a dry, sheltered void, and a single vent, conduit gap or open joint is enough for scouts to claim it. A crew finds the comb with thermal imaging, removes it, and our contractors close the entry so the space stays sealed."),
        ("There is a swarm on our dock. Is that different from bees in a wall?",
         "Usually yes. Bees clustered on a piling or rail are in transit, with honey in their stomachs but no comb built, and the cluster tends to break up once a new home is chosen. If it moves into a dock box, a boat or the cap of a seawall, it starts building, and that is when you want it removed before comb and honey spread."),
        ("Will the bees be killed?",
         "No. The colony is removed live, kept together and taken off the island to a beekeeper, the same way it is handled on [[city:fisher-island|Fisher Island]] or in [[city:coconut-grove|Coconut Grove]]. We do not exterminate honey bees, and the quote you get before the work starts is free."),
    ],
    "services": [
        ("condos-high-rises", "Beach towers and mid-rise associations where the comb sits in a shared chase, ceiling or roof."),
        ("waterfront-boats", "Bayfront seawalls, docks, lifts and boats on the Hurricane Harbor side."),
        ("pool-enclosures", "Pool pads, heater cabinets and screened enclosures on the larger single-family lots."),
        ("trees-palms", "Palms and old yard trees left from the island's coconut era."),
        ("utility-boxes", "Meter, valve and irrigation boxes along the swales west of Crandon Boulevard."),
        ("repairs", "Stucco, stem wall, soffit and roof repairs by our own licensed contractors after the comb comes out."),
    ],
    "nearby": ["miami", "fisher-island", "coconut-grove", "miami-beach"],
    "close": ("Get the island visit on the calendar",
              "Describe the spot, and a single free quote covers the crossing, the removal and the patch afterward."),
    "card": "Island village reached only by the Rickenbacker Causeway, with beach condominium towers, raised single-family houses and bayfront seawalls between two large parks.",
    "facts": [
        "Key Biscayne was incorporated as a village on June 18, 1991 (source: https://www.keybiscayne.fl.gov/uniquely_kb/about/history_of_the_village_of_key_biscayne.php)",
        "The village occupies the center 1.25 square miles of a barrier island (source: https://www.keybiscayne.fl.gov/uniquely_kb/about/history_of_the_village_of_key_biscayne.php)",
        "About 7,207 residential units: 1,296 single-family homes and 5,911 multi-family units (source: https://www.keybiscayne.fl.gov/uniquely_kb/about/history_of_the_village_of_key_biscayne.php)",
        "Village Green is 9.5 acres with multi-use fields and a half-mile jogging course (source: https://www.keybiscayne.fl.gov/uniquely_kb/about/history_of_the_village_of_key_biscayne.php)",
        "2020 census population 14,809 (source: https://en.wikipedia.org/wiki/Key_Biscayne,_Florida)",
        "Village bordered by Crandon Park on the north and Bill Baggs Cape Florida State Park on the south (source: https://en.wikipedia.org/wiki/Key_Biscayne,_Florida)",
        "The Rickenbacker Causeway opened in 1947 and is the only ingress and egress for Key Biscayne; southbound toll by SunPass, none northbound (source: https://en.wikipedia.org/wiki/Rickenbacker_Causeway)",
        "Causeway connects Miami to Virginia Key and Key Biscayne; Virginia Key is in the City of Miami; Bear Cut is at the north end of Key Biscayne (source: https://en.wikipedia.org/wiki/Virginia_Key)",
        "Crandon Park is 808 acres on the northern part of Key Biscayne with a marina, nature center and beach; Crandon Boulevard runs through it from the causeway (source: https://en.wikipedia.org/wiki/Crandon_Park)",
        "Bill Baggs Cape Florida State Park occupies about the southern third of the island; Hurricane Andrew in 1992 destroyed invasive Australian pines, allowing restoration of native hammock and mangrove (source: https://en.wikipedia.org/wiki/Bill_Baggs_Cape_Florida_State_Park)",
        "Cape Florida Light was constructed in 1825 (source: https://en.wikipedia.org/wiki/Cape_Florida_Light)",
        "Island was the largest coconut plantation in the continental United States in the first half of the 20th century; Mackle Construction homes offered from 1951 (source: https://en.wikipedia.org/wiki/Key_Biscayne,_Florida)",
        "Most higher-density condominium buildings are on the beach; medium-density multifamily between Ocean Drive and Crandon Boulevard; Holiday Colony single-family neighborhood; waterfront single-family lots tend to exceed 15,000 sq ft (source: Village Master Plan, https://files.keybiscayne.fl.gov/Documents/Services/Building%20Zoning%20and%20Planning/Resources/Studies%20and%20Reports/VKB_MasterPlan_1995_Amended12-9-08.pdf)",
        "Crandon Boulevard is the only external access route; retail mostly on its west side, multifamily on the east; Harbor Drive and West Mashta Drive are collectors; Fernwood Road parallels Crandon (source: Village Master Plan PDF above)",
        "Entire village in the 100-year floodplain; elevation 4 to 6.5 ft; base flood elevation 7 to 11 ft; new construction first floor elevated (source: Village Master Plan PDF above)",
        "Almost all bayfront lots have seawalls; mangrove wetlands near Calusa Park in Crandon Park; 3,260 units in structures of 50+ units in 1990; smaller Mackle houses being replaced by larger houses (source: Village Master Plan PDF above)",
        "Village Hall at 88 West McIntyre Street (source: https://www.keybiscayne.fl.gov/)",
        "Many condominium units are seasonal (source: Village Master Plan PDF above)",
    ],
}
