# -*- coding: utf-8 -*-
"""Miami Lakes page copy."""

CITY = {
    "key": "miami-lakes",
    "title": "Bees in Miami Lakes: Shade Trees, Lakes and Gates",
    "desc": "Colony in a Miami Lakes shade oak, lakeside wall or eave? Live removal, guard-post entry planned ahead, own repair crews and a quote that costs nothing.",
    "h1": "Miami Lakes Bee Removal for a Town Built Around Water and Oaks",
    "kicker": "Town of Miami Lakes",
    "lede": "A town planned around curving lakes and shaded streets gives honey bees water, flowers and old trees all within a short flight. If a colony has moved into your house or yard, we take it out alive and close up the gap.",
    "quick": "A colony living in a Miami Lakes house, shade tree or shop goes to a beekeeper alive, together with its comb. The crew finds the colony (thermal imaging helps when it is hidden in a wall or ceiling), lifts out the comb, seals the gap and cleans up the honey. A colony you can reach from the yard is usually a $300 to $400 job, while comb buried in a wall or roof that has to be cut open and rebuilt can reach the thousands. Your 2 a.m. call reaches a person, and a 24-hour response guarantee covers it.",
    "alarm": "Bees chasing someone across the yard or pouring out of a wall? Get to a car or a closed room quickly and shut it. Scrape stingers off with a card edge. Lips swelling, a tight throat or wheezing means 911 first. After that, call us and say someone was stung, so your call is handled ahead of routine ones.",
    "glance": [
        ("Incorporated", "December 2000, the 31st municipality in Miami-Dade"),
        ("Developed by", "Sengra, now the Graham Companies, on Graham dairy land from 1962"),
        ("Lakes", "23 lakes woven through the master plan"),
        ("Area", "6.51 square miles, about 0.85 of it water"),
        ("Residents", "30,467 at the 2020 census"),
    ],
    "opening": "Miami Lakes began as pasture. The Graham family ran one of Florida's largest dairies on this land before their company started building homes here in 1962, following a master plan by landscape architect Lester Collins built around curving, tree-shaded roads, neighborhood parks and curving lakes. The town incorporated in December 2000, sits between [[city:hialeah|Hialeah]] and [[city:miami-gardens|Miami Gardens]], and today counts 23 lakes inside its limits.\n\nThat design is exactly what a honey bee colony looks for. Open water sits a short flight from almost every yard, the streets are lined with mature shade trees, and the earliest houses have been through more than sixty hurricane seasons of sun and wind at their eaves, vents and roof edges. Scouts from a swarm that leaves a hollow trunk by one lake can be checking your soffit by the next morning. This page covers where colonies tend to settle in a town built this way, how the guard districts affect a visit, and what to do about bees that are only stopping by the water for a drink.",
    "hotspots_h": "Where a colony settles in a planned lake town",
    "hotspots": [
        ("Hollow shade trees", "The Town favors shade-giving canopy trees over palms in residential swales, and many have grown for decades. A broken limb or old pruning wound can open into a hollow trunk with plenty of room for comb, often at a height you only notice when the traffic is steady."),
        ("Soffits and eaves", "On houses built in the early phases of the master plan, soffit vents have had plenty of time to loosen and fascia boards to pull away. A finger-width gap under the roofline is enough for a scout to report back, and the colony builds in the dark space beyond it. See [[svc:soffits-eaves|eave and soffit colonies]]."),
        ("Lakefront back walls", "Yards that run down to a lake get steady bee traffic from foragers collecting water. When that traffic starts going in and out of one crack in a wall, a weep hole or a pipe opening instead of the shoreline, a colony has likely moved inside."),
        ("Meter and irrigation boxes", "Irrigated lawns depend on buried valve boxes, which stay dark, dry inside and close to water. Lift a lid without looking first and you may meet a full colony on the underside."),
        ("Storefronts and offices", "The Main Street town center mixes shops, offices and services within walking distance of homes. Sign cabinets, parapet gaps and rooftop equipment housings on commercial buildings give a swarm a sheltered cavity above foot traffic."),
    ],
    "streets_h": "Notes on the guard and lake districts",
    "streets": [
        ("Miami Lakes Section 1", "One of the four sections where guard service is paid for through a Town special taxing district. Put our crew on your guest list as soon as you book, which saves a wait with the guard while the colony keeps working."),
        ("Loch Lomond", "Also a guard service district, so plan entry the same way. If the colony is in a tree on a shared strip rather than your own lot, ask your association who signs off before the work starts."),
        ("Royal Oaks Section 1 and Royal Oaks East", "Each of these is listed by the Town as its own guard district, so tell us which one you live in when you book. Royal Oaks Park, with its community center, is a separate Town property if bees turn up there."),
        ("Lake Patricia", "Here the Town runs a lake maintenance district instead of guard service. Homes along the water see foragers working the shoreline all day, which is normal. A tight stream into one gap on the house is the sign that matters."),
        ("Lake Hilda", "The second of the two Town lake maintenance districts. Lakeside lots here face the same question as Lake Patricia: bees drinking at the edge are visitors, while bees vanishing into an eave or block cell are tenants."),
        ("Main Street", "Town Hall has a Main Street address, and the town center around it mixes shops and offices along walkable streets. For a commercial unit, the property manager or landlord usually needs to approve the work and may ask for proof of insurance first."),
    ],
    "body": [
        ("A colony in a shade tree you want to keep", "Miami Lakes takes its canopy seriously. Removing or relocating a protected tree, or doing work that may effectively destroy one, takes a Town tree permit, and the Town follows the ANSI A300 pruning standard.\n\nThat matters when bees move into a hollow oak or other shade tree. Cutting the tree down is rarely the right answer and may not be allowed. Usually the crew works through the knothole or wound the bees already use, widening it only as far as the comb requires so the wood can callus over, and the hollow is then treated so new swarms are less drawn to the scent of old comb. If a tree is coming down anyway for safety reasons, sort out the permit first and call before the saw starts, because a cut through a live colony puts angry bees in the air across the whole street. Our [[svc:trees-palms|tree and palm colony page]] goes into the methods."),
        ("Bees at the lake are not always a hive", "Honey bees need water as much as nectar. Water collectors haul it back so house bees can spread it on the comb and fan it to cool the nest, or mix it into honey fed to larvae, and in summer heat a strong colony keeps a steady stream of them flying. With 23 lakes inside the town, almost every yard is on somebody's water route.\n\nSo a line of bees on your dock edge, pool ledge or birdbath is usually a supply run, not a nest. Watch where they fly when they leave. If they head off over the rooftops, leave them be. If they keep vanishing into the same gap in your house, a palm boot or a valve box, a colony is close by and will keep growing. Our field note on [[guide:scout-bees|scout bees checking out the house]] explains the difference between a few curious bees and a swarm choosing a home, and [[page:answers|our answers page]] covers the common worries."),
        ("Associations, guard districts and shared ground", "Roughly 2,400 Miami Lakes households sit inside six Town-run special districts that pay for guard service or lake upkeep, and a homeowners association may apply on top of that. Both shape who handles a colony. Bees inside your own walls or roof are yours to deal with. Bees in a common-area tree, an entry wall or a clubhouse are usually the association's or the manager's call.\n\nFor boards and managers we can send a COI before the visit, an itemized invoice and photos afterward, and a written scope if the board needs to vote on it. Our [[svc:hoa-commercial|HOA and property manager page]] lays out how those jobs run, and [[page:cost|the cost page]] explains what moves a price from a simple pickup to a rebuild."),
    ],
    "band": ("Comb in the oak, the eave or the wall?", "A phone snapshot of the gap, taken from a safe distance, is often enough for a rough read on the job before anyone drives out."),
    "visit_h": "How a Miami Lakes visit runs",
    "visit": [
        ("Clear the gate", "If you live in one of the guard districts, add our crew to your visitor list before we leave so the truck is waved through instead of idling with the guard."),
        ("Find the colony", "Bees landing at the opening show the crew where to start. A thermal camera then shows the warm mass of comb behind stucco, drywall or bark, so the cut is made once, in the right place."),
        ("Take it out alive", "The crew opens the cavity, cuts out the comb, collects the bees and boxes them for a beekeeper. Honey and wax come out too, so nothing is left to rot or attract pests."),
        ("Close it up", "The patch, the stucco and the paint are handled by our own licensed tradespeople rather than a subcontractor you have never met. That work is warrantied, so a fresh colony knocking at the same repaired opening is ours to come back and handle."),
    ],
    "faqs": [
        ("Who is responsible for a colony in the oak on my swale, me or the Town?", "It depends on who owns and maintains that tree, so check with the Town or your association before anyone cuts it. Removing or badly damaging a protected tree needs a Town permit. We can usually take the colony out alive without felling the tree, which avoids the question entirely."),
        ("I live in a guarded section. Can you still get in at night?", "Yes, as long as the guard has our visit. Someone answers the phone 24/7. Expect an emergency at midnight, or on a weekend, to be billed above a Tuesday afternoon visit. Call the guard or add us to your pass list while we are on the way so the crew is not held up at the entrance."),
        ("There are bees all over my dock and pool edge. Do I have a hive?", "Not necessarily. Bees fly to water to cool their colony, and with lakes behind so many yards that traffic is common. Follow where they go when they leave. If they disappear into a gap on your house, a box or a tree, call and we will come and check."),
        ("Our association needs paperwork before a vendor sets foot on common ground. What can you send?", "We provide a COI showing we are licensed and insured, plus a written description of the work. After the job you can have photos and an itemized invoice for the board's records. Send the manager's details with your request and we will route the paperwork there."),
        ("Bees are humming in the wall beside my kids' room. Do they get exterminated?", "No. Live removal is the only method used, and the bees end up in a beekeeper's boxes. We seal the room side first if bees are leaking indoors, then open the wall from whichever side does the least damage and rebuild it afterward."),
    ],
    "services": [
        ("trees-palms", "Hollow shade trees along the swales and lakes, taken out alive without cutting the tree."),
        ("soffits-eaves", "Older rooflines where vents and fascia have loosened over the decades."),
        ("walls", "Colonies inside block or frame walls, often on the lake-facing side of a house."),
        ("utility-boxes", "Sprinkler valve and meter boxes buried in well-watered lawns."),
        ("hoa-commercial", "Guard-district associations, lake districts and Main Street landlords who need paperwork."),
        ("repairs", "Rebuilding the wall, eave or roof edge once the comb is out."),
    ],
    "nearby": ["hialeah", "miami-gardens", "hialeah-gardens"],
    "close": ("Which lake, which section, which wall?", "Fill in the quote form with your street and a photo, and mention any guest pass so entry is sorted before the crew arrives."),
    "card": "A 1960s planned town of shade trees and 23 lakes, where colonies favor hollow oaks, aging eaves and guarded sections need entry planned.",
    "facts": [
        "Miami Lakes incorporated in December 2000 as the 31st municipality in Miami-Dade County (source: https://www.miamilakes-fl.gov/our-community/history/)",
        "Developed beginning in 1962 by Sengra (later the Graham Companies) on land formerly owned by state senator Ernest 'Cap' Graham, whose family operated a dairy farm there (source: https://en.wikipedia.org/wiki/Miami_Lakes,_Florida)",
        "Graham's dairy farm became one of the largest in Florida; the family later developed Miami Lakes from their land (source: https://en.wikipedia.org/wiki/Ernest_R._Graham_(politician))",
        "Lester Collins created the master plan; the town has 23 lakes and tree-lined streets (source: https://www.miamilakes-fl.gov/our-community/history/)",
        "Landscape architect Lester Collins's plan emphasized curving tree-shaded roadways, numerous curving lakes and neighborhood parks; Main Street is the town center, with shopping within walking distance in the original development (source: https://en.wikipedia.org/wiki/Miami_Lakes,_Florida)",
        "Total area 6.51 sq mi, 5.66 land and 0.85 water; 2020 population 30,467; bordered by Hialeah to the south and west and Miami Gardens to the east (source: https://en.wikipedia.org/wiki/Miami_Lakes,_Florida)",
        "Special taxing districts: guard service in Miami Lakes Section 1, Loch Lomond, Royal Oaks Section 1 and Royal Oaks East; lake maintenance in Lake Hilda and Lake Patricia; six districts serve about 2,400 households (source: https://www.miamilakes-fl.gov/departments/std/)",
        "Town tree permit required to remove or relocate a protected tree or perform work that may effectively destroy one; Town follows ANSI A300 pruning standards; palms give less shade than canopy trees and are less suited to residential swale plantings (source: https://www.miamilakes-fl.gov/trees-landscaping/)",
        "Town Hall is at 6601 Main Street (source: https://www.miamilakes-fl.gov/)",
        "Royal Oaks Park has a community center (source: https://www.miamilakes-fl.gov/our-community/parks-trails/)",
        "Hialeah Gardens is bordered to the north and east by Hialeah, so it is near but does not touch Miami Lakes (source: https://en.wikipedia.org/wiki/Hialeah_Gardens,_Florida)",
    ],
}
