# -*- coding: utf-8 -*-
"""Miami Beach page copy."""

CITY = {
    "key": "miami-beach",
    "title": "Miami Beach Bees: Deco Walls, Island Homes, Condo Roofs",
    "desc": "Bees in a Miami Beach condo, a Deco stucco wall or an island estate? Live removal, relocation to beekeepers, our own repairs, and phones answered 24/7.",
    "h1": "Deco stucco, tile roofs and bay islands: bee removal in Miami Beach",
    "kicker": "Barrier islands on Biscayne Bay",
    "lede": "Honey bees in Miami Beach end up in stucco, tile and tower roofs rather than hollow trees. Here is how a live removal works around historic district rules, guard gates, causeways and condo boards.",
    "quick": "Fourteen local historic districts cover much of Miami Beach, so on a stucco building the patch after a bee job matters as much as the removal. A beekeeper takes the living colony, every scrap of comb is cut away, and then a matching stucco finish is the job of our own licensed contractors and painters, not a subcontractor. A ground-level hive usually runs $300 to $400; one inside a wall or tower roof that needs repairs costs more. The quote is free, and the phones are answered 24/7, so text a photo of the gap with the address.",
    "glance": [
        ("Chartered", "Town in 1915, city in 1917"),
        ("Setting", "Natural and man-made barrier islands between the Atlantic and Biscayne Bay"),
        ("Average elevation", "About 4.4 feet above sea level"),
        ("National Register", "Art Deco district listed in 1979"),
        ("Local historic districts", "14, overseen by the Historic Preservation Board and planning staff"),
    ],
    "opening": "By area, most of Miami Beach is water. The land is spread across natural barrier islands and the islands that were dredged up out of Biscayne Bay in the 1920s, and it is densely built. A honey bee swarm scouting for a home here does not find many hollow trees. It finds buildings: the dry spaces behind parapets on 1930s apartment houses, the channels under clay barrel tile, the soffits of bayfront mansions and the equipment corners on top of oceanfront towers.\n\nThat shapes the job more than the bees do. A colony behind a Deco facade sits inside a building covered by the city's preservation rules, so the patch afterward has to fit. A colony on Palm Island sits past a guard gate at the end of a causeway. A colony at a condo comes with a board, a manager and a request for proof of insurance before anyone climbs a ladder. The removal itself is the same humane method used across [[page:county|Miami-Dade]]: the bees come out alive, go to a beekeeper, and the opening gets sealed. What follows covers the parts that are particular to this city.",
    "hotspots_h": "Parapets, tile and towers: the usual Miami Beach cavities",
    "hotspots": [
        ("Behind Deco parapets", "Art Deco apartment buildings in the Flamingo/Lummus neighborhood of South Beach often have flat roofs edged by low parapet walls. A cracked cap or a loose drain scupper opens a shaded, dry cavity, and comb can run along the inside of the wall out of sight. See [[svc:roofs|flat roof hives]]."),
        ("Under clay barrel tile", "Mediterranean Revival houses from the 1920s carry curved clay tile with open ends at the eave. A swarm that slips into one of those channels can build on the roof deck underneath and show almost nothing from the sidewalk except a steady line of bees. A storm that lifts tiles can expose it; see [[guide:after-a-storm|colonies exposed after a storm]]."),
        ("Mansion soffits on Hibiscus Island", "The big houses on the bay islands have long eaves and deep soffits, and one missing vent screen is enough of a doorway. Comb in a soffit can usually be reached from a ladder or lift without opening the roof, which keeps [[svc:soffits-eaves|eave removals]] simpler."),
        ("Tower roofs and mechanical rooms", "The oceanfront condo and hotel towers have rooftop equipment enclosures, pipe chases and louvered vents. Bees working out of those spaces can drift down onto balconies and pool decks, so the building usually wants the colony gone quickly and quietly."),
        ("Bay island moorings", "Bayfront lots on the dredged islands can come with a private dock, a deck locker and a boat under a cover that sits idle for weeks. That is plenty of time for a swarm to move into a hull compartment. Our [[svc:waterfront-boats|dock and boat removals]] cover this."),
    ],
    "streets_h": "Notes by neighborhood and island",
    "streets": [
        ("South Beach and the Art Deco district", "The National Register district runs from Sixth Street up to the Collins Canal and Dade Boulevard, between the ocean and Alton Road. It holds hundreds of hotels and apartment buildings put up between 1923 and 1943, so stucco, color and trim on a repair should match what is already there."),
        ("Star, Palm and Hibiscus Islands", "Three man-made islands finished in 1922 and reached from the MacArthur Causeway. Palm Island's entrance has a guard gate, so the crew needs to be on the visitor list before it pulls up. Hibiscus mixes mansions with converted apartments and condos."),
        ("The Venetian Islands", "Four belong to Miami Beach: San Marino, Di Lido, Rivo Alto and Belle Isle. Biscayne Island and San Marco are part of the City of [[city:miami|Miami]]. All sit along the Venetian Causeway, built in 1925 as a series of drawbridges, so a bridge opening can hold up the drive."),
        ("La Gorce Island and the Sunset Islands", "Both are residential islands from the dredging era. La Gorce Island was built in 1924 and is run by a homeowners association, so expect the association to want to know who is coming and when."),
        ("Mid-Beach: Bayshore, Nautilus and the oceanfront", "Mid-Beach takes in the Bayshore and Nautilus neighborhoods plus an oceanfront strip of big resort hotels and condo towers. On the tower side, plan around loading docks, freight elevators and a security desk."),
        ("North Beach", "From around 63rd Street up to 87th Terrace, taking in Normandy Isle, Biscayne Point and North Shore. This is where the city keeps a large collection of Miami Modern (MiMo) buildings. Directly north is [[city:surfside|Surfside]]."),
    ],
    "body": [
        ("Historic district buildings: the patch has to fit", "Miami Beach has 14 local historic districts, and every building inside one is held to the city's appropriateness criteria for alterations, no matter how it is classified. That sounds heavy for a bee job. In practice, the planning department's own FAQ lists repairs, exterior paint and facade restoration among the work its staff can approve without sending it to the full board.\n\nSo the removal is rarely the sticking point. Closing the wall is. The stucco texture, paint and trim need to come back looking as they did, so the building still reads as part of its district. Our own licensed contractors and painters do that work, and we can write up exactly what was opened and how it was closed, with photos, for you or your manager to hand to planning staff if a sign-off is needed. More on [[svc:repairs|repairs after removal]] and [[svc:walls|hives inside block walls]]."),
        ("Condo boards, managers and the paperwork that comes first", "Much of Miami Beach lives in buildings with an association. Before anyone works on a roof, a garage or a balcony, the manager will typically ask for a COI naming the association, a time window and a plan for keeping residents clear of the work. We are licensed and insured and can send that COI ahead of the visit, then coordinate through the manager so owners are not fielding calls.\n\nIf bees are on a pool deck or a balcony at this moment, lead with that. Anyone being stung is handled before any paperwork. Managers handling a tower can start with [[svc:condos-high-rises|our high-rise page]], and boards juggling several buildings with [[svc:hoa-commercial|the association and property manager page]]."),
        ("Across the water, on a 24-hour clock", "Every part of this city is reached by a causeway or by the bridges between islands. That does not stretch the 24-hour response guarantee, and the phones are staffed 24/7. What helps the crew is detail: gate or guardhouse instructions, whether the Venetian Causeway drawbridges are your route in, and whether the bees are inside the house or out by the dock.\n\nAfter-hours and Saturday or Sunday emergency work is priced higher than a Tuesday morning, so calm bees and nobody at risk usually means it pays to wait. The [[svc:emergency|24-hour emergency page]] explains when it is worth calling right away.\n\nIf the unit or house is closed up for part of the year, a swarm has time to settle before anyone notices. The colony can still come out with you away, as long as someone lets the crew in; see [[guide:second-home|bees at a seasonal home]]."),
    ],
    "band": ("A colony on the parapet or over the pool deck?", "Send a picture from the sidewalk or the balcony and say which island or street you are on; we will size up the job from there."),
    "visit_h": "How a visit runs in Miami Beach",
    "visit": [
        ("Access sorted before the drive", "Tell us the address, any guard gate or front desk, and where a truck can stand. On the gated islands, ask the guard to add the crew to the day's visitor list."),
        ("Find the comb before cutting", "Any stucco cut here has to be matched later, so the crew scans first. Heat from the brood shows up on thermal imaging through a wall, parapet or soffit, which lets the crew limit the cut to the stretch where the comb hangs. See [[guide:thermal-imaging|what thermal imaging shows]]."),
        ("Bees out alive, comb out completely", "The crew vacuums the bees gently into a box, cuts out every piece of comb and honey, and drives the colony to a beekeeper. Leftover honey would draw new bees, so none stays behind."),
        ("Close it, finish it, stand behind it", "From the street, the facade should look untouched once the crew leaves, which means rebuilding the stucco, tile or trim to match. The workmanship carries a warranty: a colony that moves back into a sealed spot means a return trip from us. Ask, and the before-and-after pictures and a line-by-line bill come to your inbox."),
    ],
    "alarm": "Anyone getting stung on a balcony or pool deck should head inside right away, with the sliding doors shut behind them. Call 911 if anyone has swelling around the face or throat or is struggling to breathe. Keep pets indoors too. Then call us, and tell us someone was stung so that call goes first.",
    "faqs": [
        ("My building is in the Art Deco district. Does repairing the wall after removal need city approval?", "Alterations in local historic districts are measured against the city's appropriateness criteria, though the planning department says repairs, exterior paint and facade restoration can usually be cleared by staff. Our written scope lists each cut and each patch, which gives staff something concrete to look at."),
        ("Can your crew get onto Palm Island or into a guarded building?", "Yes, with your help. Put the crew on the guard gate's visitor list or let the front desk know to expect us, and send any parking or freight elevator rules ahead of time. That way nobody loses an hour at the gate."),
        ("A few bees keep poking around a vent on our balcony. Is that already a hive?", "Not necessarily. A handful of bees inspecting a gap may be scouts choosing a site for a swarm. A steady line carrying pollen in means comb is being built inside. Our guide to [[guide:scout-bees|scout bees]] explains the difference, and [[guide:why-bees-come-back|why bees come back]] covers spots that keep drawing them."),
        ("Does a crowded hotel or tower change whether the colony is kept alive?", "No. Every removal is live, at a hotel, a tower or a crowded block alike. The colony is boxed, the comb is cut out, and the bees go to a beekeeper through our [[svc:relocation|relocation]] arrangement instead of being destroyed."),
        ("What will this run for a house on one of the islands?", "If the colony is in a meter box or a palm at ground level, plan on roughly $300 to $400. Inside a tile roof, a soffit or a wall that our contractors have to open and rebuild, the bill can reach the thousands. Quotes cost nothing, and the [[page:cost|cost page]] explains what moves the number."),
    ],
    "services": [
        ("condos-high-rises", "For the oceanfront towers and island condo buildings, with a COI and work coordinated through the manager."),
        ("roofs", "Flat roofs behind Deco parapets and clay barrel tile on Mediterranean Revival homes."),
        ("walls", "Colonies inside stucco walls, where the patch has to match a historic facade."),
        ("waterfront-boats", "Docks, deck lockers and covered boats on the bay islands."),
        ("trees-palms", "Palms and landscape trees on the larger island lots, out by the seawall or the pool."),
        ("repairs", "Historic facades rebuilt to match by our licensed contractors, roofers and painters wherever a hive meant opening a wall or roof."),
    ],
    "nearby": ["surfside", "fisher-island", "miami", "bal-harbour", "bay-harbor-islands"],
    "close": ("Tell us which island and which building", "Gate codes, front desk rules and the building name help the crew most; with those and a photo or the quote form, a visit is booked inside the 24-hour response window."),
    "card": "Barrier islands and bay islands: bees in Deco parapets, barrel tile, mansion soffits and condo tower roofs, with repairs matched to historic stucco.",
    "facts": [
        "Town of Miami Beach chartered March 26, 1915; became a city in 1917 (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "Miami Beach sits on natural and human-made barrier islands between the Atlantic Ocean and Biscayne Bay; 18.7 sq mi total, of which 11.7 sq mi (about 62 percent) is water; city averages about 4.4 ft above sea level (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "Star, Palm and Hibiscus Islands, the Sunset Islands and much of Normandy Isle were created by dredging Biscayne Bay in the 1920s (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "Art Deco Historic District listed on the National Register in 1979; hotels, apartments and other structures built 1923-1943; Mediterranean, Streamline Moderne and Art Deco styles (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "Miami Beach Architectural District bounded by the Atlantic Ocean, Sixth Street, Alton Road, and the Collins Canal and Dade Boulevard; listed May 14, 1979 (source: https://en.wikipedia.org/wiki/Miami_Beach_Architectural_District)",
        "Neighborhood groupings: South Beach; Mid-Beach with Oceanfront, Bayshore and Nautilus; North Beach with Biscayne Point, Isle of Normandy, La Gorce and North Shore; large MiMo collection in North Beach (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "North Beach roughly bounded by 63rd Street and Indian Creek Drive to the south and 87th Terrace to the north (source: https://en.wikipedia.org/wiki/North_Beach_(Miami_Beach))",
        "Mid-Beach has two subdistricts, Bayshore and Nautilus; its oceanfront includes large hotels and condo towers such as the Fontainebleau and the Blue and Green Diamond (source: https://en.wikipedia.org/wiki/Mid-Beach)",
        "Flamingo/Lummus neighborhood of South Beach has Art Deco and Mediterranean Revival apartment buildings from the 1920s and 1930s (source: https://en.wikipedia.org/wiki/South_Beach)",
        "Venetian Islands: San Marino, Di Lido, Rivo Alto and Belle Isle are in Miami Beach; Biscayne Island and San Marco are in the City of Miami; the original wooden causeway was replaced in 1925 by a series of arch drawbridges and renamed the Venetian Causeway (source: https://en.wikipedia.org/wiki/Venetian_Islands,_Florida)",
        "Star Island completed 1922 by dredging, reached via the MacArthur Causeway (source: https://en.wikipedia.org/wiki/Star_Island_(Florida))",
        "Palm Island reached via the MacArthur Causeway; dredging completed 1922; a fountain and guard gate mark the entrance (source: https://en.wikipedia.org/wiki/Palm_Island_(Miami_Beach))",
        "Hibiscus Island completed 1922, reached via the MacArthur Causeway, home to several mansions plus converted apartments and condominiums (source: https://en.wikipedia.org/wiki/Hibiscus_Island)",
        "La Gorce Island built 1924 within Miami Beach; the La Gorce Homeowners Association has governed it since 1946 (source: https://en.wikipedia.org/wiki/La_Gorce_Island)",
        "City has 14 local historic districts; all buildings in them are reviewed under Certificate of Appropriateness criteria; repairs, exterior paint and facade restoration may be approved by staff (source: https://www.miamibeachfl.gov/city-hall/planning/planning-faqs/)",
        "Surfside is bordered on the south by the North Beach neighborhood of Miami Beach and on the north by Bal Harbour (source: https://en.wikipedia.org/wiki/Surfside,_Florida)",
        "Fisher Island's northern shoreline faces Government Cut, which separates it from South Beach; it is a census-designated place that has not incorporated (source: https://en.wikipedia.org/wiki/Fisher_Island,_Florida)",
    ],
}
