# -*- coding: utf-8 -*-
"""North Miami page copy."""

CITY = {
    "key": "north-miami",
    "title": "North Miami at 100: Bees in Older Homes and Canals",
    "desc": "Postwar houses, canal lots and the guarded Sans Souci streets each give honey bees a way in. Where North Miami colonies settle and what a live removal costs.",
    "h1": "Postwar soffits, block cores and canal lots: North Miami bee colonies",
    "kicker": "North Dade, Biscayne Bay side",
    "lede": "North Miami turned one hundred in 2026, and plenty of its houses are old enough to have settled, cracked and opened up. Honey bees notice those openings long before an owner does.",
    "quick": "Much of North Miami went up in the post-1945 boom, so colonies here tend to hide inside soffits, attic vents and hollow block walls. A steady line of bees at one gap, hour after hour, means comb behind it. Keep kids and pets away, and leave that gap open and unsprayed; sealed-in bees can come indoors. Call or text a picture. We cut into the cavity, hand the whole colony and its wax to a beekeeper, then close the wall. Low, reachable jobs run about $300 to $400; high walls, roofs and repairs cost more.",
    "alarm": "Anyone getting stung should get inside a closed room or a car first, because running in the open keeps the bees chasing. Skip the tweezers; drag stingers off the skin with a fingernail or card edge. Dial 911 if lips or tongue swell, breathing gets hard, or the person has a bee allergy. Then phone us. A stinging emergency jumps to the front of the line, day or night.",
    "glance": [
        ("Incorporated", "February 5, 1926, first named the Town of Miami Shores"),
        ("Became a city", "May 27, 1953, under a new charter"),
        ("Population", "60,191 at the 2020 census"),
        ("Land and water", "Bay and canal cover just over 15% of the city's 10.05 sq mi"),
        ("Early name", "Arch Creek, after a natural limestone bridge that fell in 1973"),
    ],
    "opening": "Before it had a town charter, this stretch of north Dade was known as Arch Creek, named for a forty-foot limestone bridge over the water. The bridge collapsed in 1973, but water still shapes the city: the bayfront on one side and the Biscayne Canal, dug in 1924, cutting through. For a colony, that canal is a supply line. Bees haul water home daily to cool the brood and thin stored honey, so foragers set up regular trips to pool edges, birdbaths, canal banks and dripping hose bibs.\n\nThe other half of the picture is housing. After 1945, returning veterans and young families poured in, and by 1951 North Miami was counted among the fastest-growing towns in the country. Houses from that boom are now around seventy years old, and seventy years of sun, roof work, rewiring and new AC lines leave small gaps in soffits, block walls and attic vents. A scout bee can squeeze through a gap narrower than a pencil and decide your house is worth a look.",
    "hotspots_h": "Where colonies settle on North Miami property",
    "hotspots": [
        ("Soffits on postwar houses", "Wood or vented soffits from the city's postwar building wave often have loose panels or rotted corners. Behind them is a dry, shaded box that holds a steady temperature, close to ideal for comb. The tell is a tight knot of bees coming and going where a panel has pulled away."),
        ("Hollow cores in block walls", "Inside a concrete block wall are vertical hollow cores, one stacked over the next. A missing grout joint, an old pipe hole or a gap around a hose bib lets bees into one core, and the comb then grows up and down inside it. A low hum through the drywall can be the first sign, before any bees turn up indoors."),
        ("Meter, valve and sprinkler boxes", "Ground boxes for water meters, irrigation valves and backflow devices are in almost every front yard. Shaded, damp and seldom checked, they let a colony grow quietly until a meter reader or sprinkler tech pops the cover."),
        ("Palms and old shade trees", "Mature yards in the older sections hold palms with dead frond bases and hardwoods with hollow limbs. Either can hold a hive, and tree jobs need care so the tree survives the removal."),
        ("Docks, seawalls and boat storage", "Along the bay and the canal banks, dock boxes, covered boat lifts and storage under decks give bees shelter a few steps from fresh water. Those spots are tight to work, so access gets planned before the visit."),
        ("Sheds and detached garages", "Tool sheds and garage attics on deep older lots go untouched for long stretches. Colonies move into the rafters or wall gaps, and the first sign is often bees at a vent."),
    ],
    "streets_h": "Notes on North Miami neighborhoods",
    "streets": [
        ("Sans Souci", "Entry here runs past a guardhouse paid for through a Miami-Dade special taxing district. Tell the guard we are coming, or send us the visitor process, so a van and ladder are not stuck at the gate while bees keep flying."),
        ("Keystone Point", "Listed with Amber Creek East among the city's neighborhoods. Where a lot touches water, we check docks and seawall gaps as well as the house, and we agree on parking before arrival so neighbors are not blocked."),
        ("Central North Miami", "The downtown side of the city, where the Museum of Contemporary Art sits on NE 125th Street. For a shop or office here, we look at flat roofs, parapet walls and sign cavities, and a landlord who wants our insurance certificate on file before work starts can have one."),
        ("Alhambra Heights", "Another name on the neighborhood list. On a house here, expect us to check soffits, block walls, ground boxes and any tree cavities in the yard, since each one can hide a colony."),
        ("Golden Glades East", "Another section on the city's neighborhood list. On any lot with a shed or detached garage, we inspect the outbuilding along with the house, since a colony there can go unnoticed for a long time."),
    ],
    "body": [
        ("Old seams, new gaps: why these houses attract colonies", "A Mediterranean-style city hall went up in 1928, and the William Jennings Bryan school followed the same year. The big wave came after 1945, when veterans and their young families arrived in large numbers. Then came additions, enclosed porches, new roofs and modern AC equipment bolted onto old walls.\n\nEach of those layers can leave a seam where two materials meet. Honey bees look for a dry cavity with one small, defensible entrance, and a seam behind stucco or a gap where a new line passes through an old wall fits that description well. That is why a colony can show up on a house that has never had bees before. Nothing changed for you, but the right gap finally met the right swarm.\n\nIf you are not sure whether you have a colony or just a passing cluster, our guide to [[guide:scout-bees|scout bees checking out a house]] explains the difference, and our page on [[svc:swarms|swarm pickup]] covers the ball of bees that rests on a shrub or mailbox for a few hours before moving on. Hidden comb that nobody can see is easier to map with [[guide:thermal-imaging|a thermal camera]]."),
        ("Water on every side of the map", "Roughly fifteen percent of North Miami is water. The city fronts Biscayne Bay, and the Biscayne Canal was dug in 1924 to drain the land. A colony needs water every day, and foragers will drink from anything reliable, including canal banks, pool steps and fountains.\n\nBees at your pool do not always mean a hive on your property. Foragers can fly a mile or more. Still, when the crowd at the water holds steady for days and a flight line leads to a crack nearby, the nest is likely close. On waterfront lots we also check docks and seawall gaps, covered on our page for [[svc:waterfront-boats|docks, seawalls and boats]], and the pump housings and screen frames covered in [[svc:pool-enclosures|pool enclosures and equipment]]."),
        ("The campus, the museum and the park", "Three large properties in and around North Miami are run by bigger institutions. Florida International University's Biscayne Bay Campus covers about 200 acres on the bay, next to Oleta River State Park. The Museum of Contemporary Art is at 770 NE 125th Street. Arch Creek Park, a hammock and archaeological site of about nine acres, is run by Miami-Dade County Parks.\n\nIf you see bees on those grounds, report it to that property's own staff, since they control the land. If the colony is in your building, your condo or your business, that is where we come in. For associations and offices we can provide certificates of insurance, and our [[svc:hoa-commercial|HOA and commercial]] page explains how we work with managers. Neighbors have their own pages: [[city:north-miami-beach|North Miami Beach]] to the north and [[city:sunny-isles-beach|Sunny Isles Beach]] to the east. [[city:miami-shores|Miami Shores]] lies just south of the village of Biscayne Park, with the [[city:miami|City of Miami]] beyond it, and [[city:aventura|Aventura]] is another North Dade page. The full list is on our [[page:county|Miami-Dade service map]]."),
        ("Buying, selling or renting an older North Miami house", "On a house from the postwar years, a home inspection can turn up old comb stains, a sealed-over hive or live bees in a wall. If that happens during a sale, our guide to [[guide:home-sale-inspection|bees found during a home inspection]] walks through what buyers and sellers usually need. Tenants and landlords sharing one house can use [[guide:renters-and-landlords|our guide to renting with bees]] to sort out who calls whom.\n\nAn empty wall cavity still holding wax is unfinished work. Leftover comb and honey pull in new swarms and can attract pests, so the full job includes taking out every piece of comb and then sealing the entry. Our page on [[svc:honeycomb-cleanup|comb and honey cleanup]] explains that step, and [[guide:why-bees-come-back|what draws bees back to a sealed wall]] explains what goes wrong when it is skipped."),
    ],
    "band": ("Bees going into the wall right now?", "Snap the gap from a few steps back and text it over. We'll say what it likely is and how a live removal would go."),
    "visit_h": "How a North Miami visit runs",
    "visit": [
        ("Gate and parking", "If you live behind the Sans Souci guardhouse or another gated entry, give the guard our name. On narrow residential streets we park so the driveway and neighbors stay clear."),
        ("Trace the comb with a thermal camera", "The flight path tells us where to aim. A thermal scan then shows how far the comb spreads behind stucco, block or soffit, so nothing is opened blind."),
        ("Remove it alive", "We open the cavity, take the bees and every piece of comb, and keep the colony together for a beekeeper. Nothing is sprayed to kill them."),
        ("Close the wall, patch the finish", "Once the cavity is empty, the hole is closed and the finish patched by the licensed tradespeople we employ: contractors, roofers and painters. If you need paperwork, the job comes with pictures and a line-by-line invoice on request."),
    ],
    "faqs": [
        ("My North Miami house was built in the 1950s. Why are bees showing up now?", "Age opens gaps slowly. A soffit panel loosens, a grout joint wears, or an old pipe hole loses its seal. Bees only need one opening into a dry cavity. When a swarm happens to pass while that gap is open, scouts can find it, and the colony may move in within a day or two."),
        ("Bees are drinking at my pool next to the canal. Do I have a hive?", "Not always. Foragers will travel a long way for steady water, and the canal side of a yard is a natural stop. If the numbers stay high for a week, follow them with your eyes. Bees heading straight to a vent, a roof edge or a gap in stucco are pointing at home."),
        ("I live in Sans Souci. Do I have to tell the guardhouse you're coming?", "Yes, it helps a lot. Give the guard our name, or send us the visitor steps when you book. That keeps the truck and equipment moving straight to your house instead of waiting at the gate."),
        ("Is a North Miami colony exterminated or relocated?", "Relocated, always. Nothing gets exterminated here. A beekeeper takes the colony, wax and all, once it is out of your wall, and we clean and close the empty space behind it. Exterminating a hive in a wall also leaves rotting comb and honey behind, which brings new problems."),
        ("What does a removal from a block wall usually cost?", "A low hive in an easy-to-reach wall usually falls around $300 to $400. When the comb sits high, spans several block cores or needs a roofer afterward, the bill climbs, sometimes into the thousands. Quotes are free, and after-hours or weekend emergency calls carry a higher rate than a regular weekday booking."),
        ("A colony turned up again where your crew closed the wall. Is that covered?", "Our workmanship carries a warranty. If a new colony turns up in that same sealed spot, phone us and a crew heads back out to fix it. A comeback can point to a second gap nearby or wax left in the cavity, which is why every scrap of comb comes out the first time."),
    ],
    "services": [
        ("walls", "Hollow block cells and stucco seams on postwar houses are a common place for comb."),
        ("soffits-eaves", "Aging soffit panels on older homes give bees a dry, shaded cavity under the roof."),
        ("utility-boxes", "Meter and irrigation boxes sit in nearly every yard and go unopened for months."),
        ("trees-palms", "Mature yards in older neighborhoods hold palms and hollow limbs that suit a colony."),
        ("waterfront-boats", "Bay and canal lots have docks, lifts and seawall gaps right beside water."),
        ("repairs", "Our own crews close and patch the opening once the colony is out."),
    ],
    "nearby": ["north-miami-beach", "sunny-isles-beach", "miami-shores"],
    "close": ("Point us to the busy gap", "A texted photo or the quote form is enough to start. From there the plan works around your gate, yard and walls."),
    "card": "A century-old bayfront city with postwar homes, canal lots and a guarded enclave, where loose soffits and block walls give colonies a way in.",
    "facts": [
        "North Miami was incorporated as a town on February 5, 1926, first named the Town of Miami Shores, renamed Town of North Miami in 1931 (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "Became the City of North Miami under a new charter on May 27, 1953 (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "2020 census population 60,191; total area 10.05 square miles, 15.32 percent water; the city lies on Biscayne Bay (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "Area originally known as Arch Creek, after a natural limestone bridge spanning about 40 feet; Biscayne Canal dug in 1924 for drainage (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "The Arch Creek natural bridge collapsed in 1973; Arch Creek Park is about 9.4 acres with a hammock and is an archaeological site (source: https://en.wikipedia.org/wiki/Arch_Creek,_Florida)",
        "Arch Creek Park is a Miami-Dade County park of about 9 acres, an archaeological site and a bird and wildlife sanctuary (source: https://www.miamidade.gov/parks/arch-creek.asp)",
        "Spanish-Mediterranean city hall built 1928; William Jennings Bryan school built 1928; after 1945 an influx of veterans and young families brought a great growth period, and by 1951 North Miami was reported as one of the fastest-growing towns in the US (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "Neighborhoods listed include Central, Alhambra Heights, Keystone Point/Amber Creek East, San Souci and Golden Glades East (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "The Museum of Contemporary Art is at 770 NE 125th Street in North Miami; it operates in downtown North Miami (source: https://en.wikipedia.org/wiki/Museum_of_Contemporary_Art,_North_Miami)",
        "FIU Biscayne Bay Campus is in North Miami, a 200-acre waterfront campus on Biscayne Bay adjacent to Oleta River State Park (source: https://en.wikipedia.org/wiki/Florida_International_University)",
        "The Sans Souci Security Guard Special Taxing District was created by Miami-Dade County Ordinance 90-128 in 1990 and has a guardhouse (source: https://play.champds.com/ATT/northmiamifl/2018-10/e022e603b524a90e14ce3480e0b308281671bd4c.pdf)",
        "The City of North Miami is celebrating its centennial, 'We Are 100' (source: https://www.northmiamifl.gov/)",
        "North Miami's neighbors include North Miami Beach to the north and Sunny Isles Beach to the east (source: https://en.wikipedia.org/wiki/North_Miami,_Florida)",
        "Biscayne Park is a village bordered to the north by North Miami and to the south by Miami Shores (source: https://en.wikipedia.org/wiki/Biscayne_Park,_Florida)",
    ],
}
