# -*- coding: utf-8 -*-
"""Surfside page copy."""

CITY = {
    "key": "surfside",
    "title": "Bee Removal in Surfside: Collins Condos to Dickens Avenue",
    "desc": "Honey bees in a Surfside condo, storefront or house west of Harding Avenue? Live removal, sealed entry points, COIs for boards and 24/7 phones.",
    "h1": "Bee removal in Surfside, from oceanfront towers to the author-named streets",
    "kicker": "Town of Surfside, ocean to creek",
    "lede": "Surfside fits condo towers, a two-block shopping street and a grid of houses and duplexes into roughly half a square mile. Here is where honey bees find a way in on those blocks, and how a live removal works here.",
    "quick": "On Surfside's oceanfront towers and Harding Avenue storefronts, a bee job starts with the building manager, not the ladder: our COI goes over first and roof or balcony access is booked. Houses and duplexes west of Harding just need the owner's go-ahead. In both cases a beekeeper takes the living colony and our own licensed tradespeople close the gap. Expect roughly $300 to $400 for a job you can reach from the ground; [[page:cost|the price climbs]] when a roof, wall or high balcony has to be opened and rebuilt.",
    "glance": [
        ("Incorporated", "May 18, 1935, by Surf Club members resisting annexation"),
        ("Town limits", "87th Terrace to 96th Street, Atlantic to the Indian Creek waterway"),
        ("Land area", "About 0.56 square miles"),
        ("Shoreline", "Roughly one mile of public Atlantic beach"),
        ("Residents", "5,689 at the 2020 census"),
    ],
    "opening": "Surfside, wedged between [[city:miami-beach|Miami Beach]] and [[city:bal-harbour|Bal Harbour]], is a small town with three very different kinds of building stacked side by side. On the ocean side of Collins Avenue stand multistory condominiums and hotels. One block west, Harding Avenue holds the town's commercial strip from 94th to 96th Street. West of Harding and south of 95th Street, the residential grid of single-family homes, duplexes and small apartment buildings runs down to the town line at 87th Street.\n\nThat mix matters to a honey bee scout looking for a dry, dark cavity. Many older buildings here date from the 1940s through the 1960s, built in Streamline Moderne and Miami Modern styles with flat roofs, parapets and concrete block walls. Newer glass towers have fewer cracks but plenty of mechanical voids. University of Florida entomologists note that African-derived honey bees, which are found in Florida, nest in much smaller spaces than European bees and have turned up in water meter boxes and cement blocks. In a town this compact, a colony is rarely far from a neighbor's door.",
    "hotspots_h": "Where colonies settle on Surfside buildings",
    "hotspots": [
        ("Flat roofs and parapet caps", "Mid-century apartments and small hotels along Collins and Harding often have flat roofs edged by parapets. Where the cap flashing lifts or a scupper rusts open, bees can move into the hollow wall below and build comb out of sight of the street."),
        ("Hollow concrete block walls", "One gap at a pipe, a hose bib or a cracked stucco joint is enough for a swarm to reach the hollow cores of [[svc:walls|concrete block walls]] on the mid-century apartments and houses here. From there the comb can climb several courses before anyone on the sidewalk spots the traffic."),
        ("Meter and valve boxes", "The [[svc:utility-boxes|meter and valve boxes]] set in the ground in front of homes and duplexes on the grid are the kind of small cavity African-derived bees will take. Watch the lid edge for a minute before reaching down; bees walking in and out of that seam mean comb below, so leave it shut."),
        ("Condo mechanical spaces", "On the towers by the beach, colonies can settle in rooftop equipment enclosures, chases that carry pipes and ducts, and the soffit space under balconies. These spots need roof or swing-stage access and a word with management first."),
        ("Eaves on the single-family streets", "Houses west of Harding Avenue have eaves, soffit vents and fascia boards where a loose panel leaves a dry pocket. Salt air from the ocean side can loosen screens and sealant faster than inland."),
    ],
    "streets_h": "Notes for each part of town",
    "streets": [
        ("Collins Avenue oceanfront", "Condominiums and hotels line the beach side of Collins. Expect to coordinate through the manager or front desk, send our COI ahead of the visit, and plan roof or balcony access around residents and guests."),
        ("Harding Avenue business district", "Shops and restaurants between 94th and 96th Streets share walls and awnings. A colony in one storefront can affect the unit next door, so we plan the opening and the cleanup with every tenant who shares the wall."),
        ("Collins Avenue Historic District", "Nine buildings on the west side of Collins and the east side of Harding, between 90th and 91st Streets, were recognized in 2016 for Streamline Moderne and Mid-Century Modern design. Repairs here should match the original finish, so we photograph every opening before closing it."),
        ("The author-named residential grid", "West of Harding, streets carry the names of British and American writers such as Irving, Hawthorne, Emerson, Byron and Dickens. Homes and duplexes sit close together, so we warn neighbors before the comb comes out of a wall."),
        ("Lots on the Indian Creek side", "The town's western edge reaches the Indian Creek waterway. Yards that face [[city:bay-harbor-islands|Bay Harbor Islands]] across the water can hide colonies in [[svc:waterfront-boats|dock boxes, seawall cavities and boat covers]], which we reach from the land side whenever possible."),
    ],
    "body": [
        ("Why half a square mile has so many openings", "Surfside has seen a wave of new development. The town's own history notes that many small apartments and hotels from the 1940s to the 1960s have been razed for new construction, while others still stand beside brand-new towers. That leaves a patchwork: aging stucco and block on one lot, fresh curtain wall on the next, and construction work that can disturb a hidden colony enough that it abandons the cavity and moves into another one nearby.\n\nEach type fails differently. Older buildings crack at joints, roof edges and around wall-unit air conditioners. Newer ones are tight on the outside but carry hollow chases, roof mechanical rooms and decorative cladding with gaps behind it. On every one of them, the goal is the same: find the comb, take the colony out alive through the smallest practical opening, then close the cavity so the scent that draws bees back is gone. Our [[guide:why-bees-come-back|notes on bees returning to the same spot]] explain why skipping that last step tends to fail."),
        ("Working with condo boards and managers", "A colony in a condo tower is usually the association's job, but the call can start with any resident who sees bees on a balcony. Ahead of the visit the manager gets our COI, we settle on a window for roof or elevator access, and say exactly which units or common areas are affected. [[guide:thermal-imaging|Thermal imaging]] lets us locate the comb behind a wall or ceiling before anything is cut, which keeps the opening small and the board's repair bill shorter.\n\nPatching is handled by licensed roofers, painters and contractors on our own crew. The workmanship carries a warranty, and we head back out if bees reappear at a gap we closed. Ask, and the manager receives a photo set and a line-by-line invoice to close out the work order. Boards weighing a tower job can read how [[svc:condos-high-rises|high-rise removals]] are staged and what [[svc:hoa-commercial|property managers]] usually need on paper."),
        ("A town where many homes sit vacant part of the year", "At the 2020 census, 37.4 percent of Surfside's housing units were counted as vacant, a figure that includes seasonal homes. An empty apartment or house gives scouts weeks of quiet to choose a cavity, and a colony can be well established by the time an owner returns or a neighbor reports the traffic.\n\nWhile you are away, a manager or neighbor can text us a picture of where the bees go in, and we can arrange entry through the building or a key holder. For owners who split the year, the [[guide:second-home|seasonal-home field guide]] lists the corners a caretaker should glance at on each walk-through, and [[guide:scout-bees|the one on scout bees]] explains the short window when a few curious bees can still be discouraged before a swarm moves in."),
    ],
    "band": ("Comb behind Surfside stucco or a parapet?", "A picture of the gap plus a word on whether it is a condo, shop or house is enough for a first read."),
    "visit_h": "How a removal runs in Surfside",
    "visit": [
        ("Start with a photo", "One phone shot of the gap, plus a line saying house, shop or condo unit, lets us plan the visit. That tells us which ladders, lifts and paperwork to bring."),
        ("Clear it with the building", "For condos and shops we contact management, email the COI and confirm roof, elevator or loading area access, plus where the truck can park on a tight block."),
        ("Find the comb and remove it", "On a tight Surfside lot every cut should be small, so a thermal camera maps the warm comb behind the stucco or ceiling first. Bees and comb then leave alive through that single opening, bound for a beekeeper."),
        ("Close the cavity and clean up", "Our own crew cleans out honey and wax, seals the gap and restores the stucco, roofing or paint, with photos of each step if you want them."),
    ],
    "alarm": "Anyone taking stings should move away fast and get behind a closed door, whether that is a lobby, a shop or a parked car. Swelling lips or throat, labored breathing, or dozens of stings on one person all mean a 911 call. Leave the bees alone, with no hose or spray, keep kids and pets back, and [[svc:emergency|ring us at any hour]]; a person being stung jumps to the front of the line.",
    "faqs": [
        ("There is a colony behind the soffit under my condo balcony. Who should make the call?", "Tell the manager first, since walls, roofs and balcony soffits are often common elements. Either you or the association can call us; the insurance paperwork goes to the building and access is arranged so the work is approved before anyone opens a wall."),
        ("I am out of town for the season. Can this be handled before I get back?", "Yes. A neighbor, caretaker or the front desk can send us photos and let our crew in. Ask for photos and a line-by-line invoice and you will have a record of the removal and the patch from wherever you are."),
        ("Will the stucco on my house west of Harding have to be opened?", "If the comb is inside a block wall, a section usually has to come out to remove it whole. Thermal imaging keeps that section as small as possible, and our own contractors and painters patch and finish it afterward."),
        ("Our building is in the Collins Avenue Historic District. Does that change anything?", "It can affect how exterior repairs are finished. We photograph the original surface before opening it and aim to match materials and color, and we can share the photos with your board or any reviewer who needs them."),
        ("Could these be African-derived bees?", "They might be. African-derived honey bees live wild in Florida, and nobody can sort them from gentler stock by looking. Treat every colony as defensive, keep your distance, and leave the removal to a protected crew."),
    ],
    "services": [
        ("condos-high-rises", "Towers on the ocean side of Collins Avenue, with roof and balcony access planned through management."),
        ("walls", "Concrete block and stucco walls on mid-century apartments and on houses in the residential grid."),
        ("roofs", "Lifted parapet caps and rusted scuppers on mid-century low-rises between Collins and Harding."),
        ("utility-boxes", "Water meter and valve boxes in front of homes and duplexes west of Harding Avenue."),
        ("waterfront-boats", "Docks, seawalls and boat covers on lots facing the Indian Creek waterway."),
    ],
    "nearby": ["bal-harbour", "miami-beach", "bay-harbor-islands"],
    "close": ("Ocean side or creek side, one call starts it", "Call any hour or send [[page:quote|the quote form]]; a reply reaches you inside the 24-hour response guarantee, and a stinging emergency goes first."),
    "card": "A compact beach town where bees find gaps in mid-century block walls, flat roofs, condo mechanical spaces and front-yard meter boxes.",
    "facts": [
        "Surfside incorporated May 18, 1935, when 35 Surf Club members organized to avoid annexation by Miami Beach (source: https://en.wikipedia.org/wiki/Surfside,_Florida; https://www.townofsurfsidefl.gov/residents/about-the-town-of-surfside)",
        "Town limits run from 87th Terrace to 96th Street, between Miami Beach to the south and Bal Harbour to the north; about a mile of public beach (source: https://www.townofsurfsidefl.gov/residents/about-the-town-of-surfside)",
        "Surfside is carved from Altos del Mar plats 4, 5 and 6, stretching from the Atlantic Ocean to the Indian Creek waterway between 87th and 96th Streets, with one mile of beach (source: https://www.townofsurfsidefl.gov/departments-services/visit-surfside/visit-surfside-blog/visit-surfside/2023/10/19/surfside's-history)",
        "Land area 0.558 square miles; total 0.564 square miles; 2020 census population 5,689; 3,675 housing units, 37.4% vacant (source: https://en.wikipedia.org/wiki/Surfside,_Florida)",
        "Business district on Harding Avenue, parallel to and immediately west of Collins Avenue from 94th to 96th Streets; residential base south of 95th Street and west of Harding Avenue to 87th Street (source: town history page above)",
        "Housing mix includes single-family homes, duplexes, apartment buildings and condominiums; multistory condominiums sit adjacent to Surfside Beach (source: town history page above; https://en.wikipedia.org/wiki/Surfside,_Florida)",
        "Many apartments and small hotels in Streamline Moderne or Miami Modern styles from the 1940s through the 1960s have been razed for new development (source: town history page above)",
        "In 2016, with support from the town, the county Historic Preservation Board created the Collins Avenue Historic District: nine buildings on the west side of Collins and east side of Harding between 90th and 91st Streets, Streamline Moderne or Mid-Century Modern (source: town history page above)",
        "Streets west of Harding Avenue are named for American and British literary figures including Irving, Hawthorne, Emerson, Byron and Dickens; avenues run alphabetically east to west (source: town history page above; https://en.wikipedia.org/wiki/Surfside,_Florida)",
        "Bay Harbor Islands lies west of Surfside and Bal Harbour across Indian Creek; Bal Harbour borders Surfside on the north and Miami Beach on the south (source: https://en.wikipedia.org/wiki/Bay_Harbor_Islands,_Florida; https://en.wikipedia.org/wiki/Surfside,_Florida)",
        "African honey bees are found in Florida, nest in much smaller volumes than European honey bees (including water meter boxes, cement blocks and house eaves), and cannot easily be told apart from European bees by sight (source: https://ask.ifas.ufl.edu/publication/IN790)",
    ],
}
