# -*- coding: utf-8 -*-
"""Pool enclosures and pool equipment removal page copy."""

SERVICE = {
    "slug": "pool-enclosures",
    "title": "Screen Enclosure and Pool Pad Hives, Taken Out Alive",
    "desc": "Bees inside a pool cage beam, heater cabinet or pump cover? Live removal across Miami-Dade, then the screen, caps and housings are closed back up.",
    "h1": "Bees in Your Pool Cage or Pool Equipment, Miami-Dade",
    "kicker": "Screen enclosures and equipment pads",
    "lede": "A pool cage is mostly hollow aluminum, and the pad beside it is a row of warm, dry boxes. Both suit a honey bee colony better than you would expect.",
    "quick": "If bees keep slipping into a gap in a screen enclosure frame, a gutter end or a pool heater cabinet, a colony has probably moved inside. Stop swimming near that corner, leave the pump and heater off, and do not spray anything that can wash into the water. Removal is live: the colony leaves in a ventilated box, its comb comes out of the beam or housing, and the hole gets a cap. A phone photo of the entry point is the quickest way to start.",
    "alarm": "Bees pouring out of the cage frame or the equipment pad and stinging? Get everyone out of the pool and indoors, close the sliding door behind you and keep pets in. Do not try to hose them off. Call us; stung people get answered first, any hour.",
    "card": "Colonies in hollow screen enclosure beams, gutter ends, pump and filter covers, heater cabinets and pool cover reels, removed alive and sealed shut.",
    "seeing_h": "Signs on the frame, the deck and the pad",
    "seeing": [
        "A steady line of bees walking in and out of one small hole near the top of an aluminum post or beam.",
        "Bees gathering at the open end of the gutter where the enclosure roof meets the house fascia.",
        "A hum or a crowd of bees around the heater cabinet louvers, the timer box or the plastic cover over the pump and filter.",
        "Sticky amber streaks on a white frame member below a joint, or a sweet, fermented smell beside the equipment pad.",
        "Bees clustering on the screen panels at dusk instead of flying off, all on the same side of the cage.",
    ],
    "behind": "A screen enclosure is built from aluminum extrusions, and many of its posts, beams and gutters are hollow inside. A missing end cap, a drilled hole left from an old fastener or a split seam is enough of a door for scout bees. Inside, the colony builds comb along the inside walls of the tube where rain cannot reach it. The equipment pad offers the same thing in a different shape: a pump cover, a heater cabinet or a cover reel box is a dry, shaded space with a narrow entrance. University of Florida entomologists report that Africanized bees settle for far less room than European colonies, so a beam that looks too narrow for a hive can still hold one.",
    "body": [
        ("Why the pool cage itself is the problem", "Bees landing on the water to drink is a different situation, and on its own it does not mean a hive is close. This page is about bees living in the structure. Look up first. A colony in a pool cage usually shows as traffic at one point on the frame, often near a joint, a cap or the gutter end. Comb inside a closed aluminum member stays out of sight, so the only proof is the bees themselves and sometimes honey seeping from a seam. Thermal imaging helps here, because a live colony is a warm patch inside a beam that should read the same temperature end to end. For how the camera picks that spot out of bare metal, see the [[guide:thermal-imaging|thermal imaging guide]]. Finding the exact section matters, since the beam is opened only there and not along its whole length."),
        ("Pumps, heaters, skimmers and cover reels", "The equipment pad is where people get stung by surprise, because the job of checking chlorine or cleaning a filter basket puts your hands right next to the colony. Bees move into pump and filter covers, the cabinet around a pool heater, timer and control boxes, and the housing at the end of an automatic cover. A skimmer lid on a pool that has sat unused can shelter bees too. University of Florida entomologists note that Africanized bees are agitated by vibration from power equipment, so do not switch the pump on to see what happens, and do not pressure-wash the deck nearby. Shut the equipment off at the breaker if you can do it without walking past the entrance. Bees in the in-ground [[svc:utility-boxes|water meter or valve boxes]] next to the pad are handled the same way."),
        ("Your enclosure may be your pool barrier", "Under the Florida Building Code, a standard screen enclosure can serve as part or all of the required barrier around a residential pool, and Florida law expects every new home pool to have a barrier or another approved safety feature. That makes a cut screen panel or a removed door more than a cosmetic gap. If a panel has to come out to reach a colony, it goes back in the same visit or the opening is closed off before anyone leaves, and you should keep small children away from the pool area until it is. A beam that has to be opened is closed with a proper cap or patch, not tape. County product approval for screen enclosures checks the frame, fasteners and anchorage against the loads set in the Florida Building Code, so the aluminum itself is not something to drill into casually."),
    ],
    "band": ("That hole in the beam is now their front door", "A close photo of the post, gutter end or heater cabinet helps narrow down where the comb may be before anyone climbs a ladder."),
    "takeout_h": "From flight line to fresh end cap, step by step",
    "takeout": [
        ("Find the colony", "We trace the flight line to one entry point, then scan the beam or housing with a thermal camera to find where the comb sits inside so only that section gets opened."),
        ("Cut power, clear the deck", "Power to the pump, heater and lights on the pad is turned off at the breaker, the pool area is cleared, and the doors to the house stay shut."),
        ("Open at the right spot", "An end cap comes off, a screen panel is unsplined, or a cover or cabinet door is removed. On a beam, a small access cut is made only where the colony is."),
        ("Collect the bees alive", "Inside the opened tube, comb is sliced off the aluminum walls while bees ride a gentle vacuum into a ventilated carrier. Then the colony leaves with a beekeeper to be rehomed, not killed."),
        ("Clean the cavity out", "Leftover honey and wax are scraped out of the beam or housing, because the smell draws new scouts back to the same hollow."),
    ],
    "putback": "Your cage should shut as tightly after the visit as it did before. The access cut gets a patch, broken or missing end caps are swapped for new ones, old fastener holes are filled, and any panel that came out is re-splined and pulled taut. On the pad, each housing and cover returns to its own spot. Bigger repairs, such as a damaged gutter run or several new panels, are done by our own licensed contractors. That sealing work is warrantied: should bees start working the patched beam or replaced cap again, we return and deal with it. The [[svc:repairs|repairs after removal]] page covers that work in more detail.",
    "price": "A colony you can reach while standing on the deck, such as one in a filter cover or at the bottom of a post, falls in the range of about $300 to $400. Comb up in the roof beams, a gutter that must be cut, or a long stretch of new screen pushes the bill higher, into the thousands once repairs pile up. Expect an after-hours or Saturday and Sunday surcharge. Quoting costs you nothing; the [[page:cost|cost page]] breaks down the pricing.",
    "price_factors": [
        "Height of the colony in the cage roof, and the reach needed to work there.",
        "Whether a beam or gutter has to be cut open rather than reached through an end cap.",
        "How many screen panels come out and have to be re-splined.",
        "Size of the comb mass packed inside the tube or cabinet.",
        "Emergency timing at night or on a weekend visit.",
    ],
    "miami_h": "Pool cages and pads around the county",
    "miami": [
        ("pinecrest", "[[city:pinecrest|Pinecrest]] grew around ranch houses on one-acre lots in the 1950s and 1960s, with heavy landscaping. On a big lot the equipment pad can sit far from the back door, where a colony can go unnoticed."),
        ("homestead", "Hurricane Andrew came ashore near [[city:homestead|Homestead]] in 1992, and most damaged homes there were repaired or rebuilt within about two years. Even a cage built to wind-load rules can lose caps and screens in a storm, opening hollow beams to scouts. See [[guide:after-a-storm|bees after a storm]]."),
        ("miami-lakes", "[[city:miami-lakes|Miami Lakes]] was laid out from 1962 around curving lakes. When a cage sits between the house and the water, the only dry route to the colony and the pad may be through the house."),
        ("doral", "[[city:doral|Doral]] grew from the 1962 country club into neighborhoods like Doral Park and Doral Estates. Shared pools in a community mean an equipment room, a fence and a manager to coordinate with, so see [[svc:hoa-commercial|HOA and property manager removal]]."),
    ],
    "faqs": [
        ("Can we keep using the pool while bees live in the cage?", "Not near the colony. Splashing, pool toys and a running pump all bring guards out, and nobody outruns bees while treading water. If the colony is at the far end of a large enclosure and the bees ignore you, short trips across the deck are one thing, but swimming should wait until the colony is out."),
        ("Bees are inside my pool heater. Can I run it?", "Leave it off and switch it off at the breaker if you can get there safely. Heat, fans and vibration upset the colony, and comb built against wiring or controls is a problem for the heater too. Once the bees and comb are out, have the heater checked by your pool or gas service before it runs again."),
        ("Why not spray into the beam and be done?", "Whatever you spray into the frame can run down into the pool, and the dead colony stays behind. Honey and wax left inside a hollow beam rot and drip, and the scent pulls new scouts to the same hole. Our [[guide:why-bees-come-back|guide on why bees come back]] explains why the cavity has to be emptied and closed."),
        ("Will removing a screen panel break my pool barrier?", "Only for as long as it is out. A screen enclosure can count as the pool barrier under the Florida Building Code, so panels and doors are put back or the gap is blocked before the visit ends. Keep children away from the pool area while the work is underway."),
        ("Our condo pool has bees in the equipment room. What do you need from us?", "Access to the room, a contact who can shut off power to the pumps, and any rules the board sets for contractors. Our licensed, insured crew can have a COI made out to the association before the date is set. A swarm hanging on the fence is simpler; see [[svc:swarms|swarm pickup]]."),
    ],
    "related": ["utility-boxes", "soffits-eaves", "honeycomb-cleanup", "repairs", "hoa-commercial"],
    "close": ("Which post or beam are they using?", "Point to the spot in a call or the quote form. Pool calls get the same 24-hour response guarantee, and the line is staffed at every hour."),
    "facts": [
        "Africanized honey bees nest in a much smaller volume than European honey bees and have been found in water meter boxes, cement blocks and house eaves; they are agitated by vibration from power equipment and lawnmowers; they have been found in Florida (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "Miami-Dade Product Control checklist #0465 for screen enclosure approval requires calculations showing the product, including footing and anchorage, can withstand the forces set in the Florida Building Code, with frame stresses, foundation support and fastener loading checked against a design pressure per chapter 20; fabricators identify each structural member (extrusion) under the NOA (source: https://www.miamidade.gov/building/library/checklists/screen-enclosures.pdf)",
        "Florida Building Code R4501.17.1.11: standard screen enclosures meeting R4501.17 may be used as part or all of the pool barrier; barrier top at least 48 inches above grade (source: https://www.miamidade.gov/permits/library/presentations/pool-barriers.pdf)",
        "Florida Statute 515.27 requires a new residential pool to have at least one safety feature: a barrier, an approved safety cover, exit alarms, self-closing doors or a pool alarm (source: https://www.flsenate.gov/Laws/Statutes/2024/515.27)",
        "Hurricane Andrew made landfall just northeast of Homestead on August 24, 1992; nearly two years after Andrew, about 70% of damaged or destroyed Homestead homes had been repaired or rebuilt (source: https://en.wikipedia.org/wiki/Hurricane_Andrew)",
        "Pinecrest developed in the 1950s and 1960s with ranch-style houses on 1-acre lots and a lushly landscaped residential character; incorporated 1996 (source: https://en.wikipedia.org/wiki/Pinecrest,_Florida)",
        "Miami Lakes was built by Sengra (now the Graham Companies) beginning in 1962 with numerous curving lakes; incorporated as a town in 2000 (source: https://en.wikipedia.org/wiki/Miami_Lakes,_Florida)",
        "Doral Country Club opened in 1962; residential neighborhoods such as Doral Estates and Doral Park developed later; the city incorporated in 2003 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
    ],
}
