# -*- coding: utf-8 -*-
"""Pool enclosures and pool equipment removal page copy."""

SERVICE = {
    "slug": "pool-enclosures",
    "title": "Bees in a Pool Cage, Pump or Heater? Live Removal",
    "desc": "Bees inside a pool cage beam, heater cabinet or pump cover? Live removal across Miami-Dade, then the screen, caps and housings are closed back up.",
    "h1": "Bees in Your Pool Cage or Pool Equipment, Miami-Dade",
    "kicker": "Screen enclosures and equipment pads",
    "lede": "A pool cage is mostly hollow aluminum, and the pad beside it is a row of warm, dry boxes. Both suit a honey bee colony better than you would expect.",
    "quick": "If bees keep slipping into a gap in a screen enclosure frame, a gutter end or a pool heater cabinet, a colony has probably moved inside. Stop swimming near that corner, leave the pump and heater off, and do not spray anything that can wash into the water. The bees are taken out alive, the comb is cut out of the beam or housing, and the opening is capped and the screen closed. Text us a photo of the spot and we can tell you what it looks like.",
    "alarm": "Bees pouring out of the cage frame or the equipment pad and stinging? Get everyone out of the pool and indoors, close the sliding door behind you and keep pets in. Do not try to hose them off. Call us; stung people get answered first, any hour.",
    "card": "Colonies in hollow screen enclosure beams, gutter ends, pump and filter covers, heater cabinets and pool cover reels, removed alive and sealed shut.",
    "seeing_h": "What you might be noticing around the pool",
    "seeing": [
        "A steady line of bees walking in and out of one small hole near the top of an aluminum post or beam.",
        "Bees gathering at the open end of the gutter where the enclosure roof meets the house fascia.",
        "A hum or a crowd of bees around the heater cabinet louvers, the timer box or the plastic cover over the pump and filter.",
        "Honey or dark wax stains running down a white frame member, or a sweet smell next to the equipment pad.",
        "Bees clustering on the screen panels at dusk instead of flying off, all on the same side of the cage.",
    ],
    "behind": "A screen enclosure is built from aluminum extrusions, and many of its posts, beams and gutters are hollow inside. A missing end cap, a drilled hole left from an old fastener or a split seam is enough of a door for scout bees. Inside, the colony builds comb along the inside walls of the tube where rain cannot reach it. The equipment pad offers the same thing in a different shape: a pump cover, a heater cabinet or a cover reel box is a dry, shaded space with a narrow entrance. Africanized honey bees, now found in Florida, nest in much smaller spaces than European bees, so a beam that looks too skinny to hold a hive can still hold one.",
    "body": [
        ("Why the pool cage itself is the problem", "Bees landing on the water to drink is a different situation, and on its own it does not mean a hive is close. This page is about bees living in the structure. Look up first. A colony in a pool cage usually shows as traffic at one point on the frame, often near a joint, a cap or the gutter end. Comb inside a closed aluminum member stays out of sight, so the only proof is the bees themselves and sometimes honey seeping from a seam. Thermal imaging helps here, because a live colony is a warm patch inside a beam that should read the same temperature end to end. Our [[guide:thermal-imaging|thermal imaging guide]] explains what that warm patch looks like. Finding the exact section matters, since the beam is opened only there and not along its whole length."),
        ("Pumps, heaters, skimmers and cover reels", "The equipment pad is where people get stung by surprise, because the job of checking chlorine or cleaning a filter basket puts your hands right next to the colony. Bees move into pump and filter covers, the cabinet around a pool heater, timer and control boxes, and the housing at the end of an automatic cover. A skimmer lid on a pool that has sat unused can shelter bees too. University of Florida entomologists note that Africanized bees are agitated by vibration from power equipment, so do not switch the pump on to see what happens, and do not pressure-wash the deck nearby. Shut the equipment off at the breaker if you can do it without walking past the entrance. Bees in the in-ground [[svc:utility-boxes|water meter or valve boxes]] next to the pad are handled the same way."),
        ("Your enclosure may be your pool barrier", "Under the Florida Building Code, a standard screen enclosure can serve as part or all of the required barrier around a residential pool, and Florida law expects every new home pool to have a barrier or another approved safety feature. That makes a cut screen panel or a removed door more than a cosmetic gap. If a panel has to come out to reach a colony, it goes back in the same visit or the opening is closed off before anyone leaves, and you should keep small children away from the pool area until it is. A beam that has to be opened is closed with a proper cap or patch, not tape. Enclosures sold in the county carry a product approval reviewed for wind loads, so the frame itself is not something to drill into casually."),
    ],
    "band": ("A colony in the frame will not leave", "Text us a photo of the beam or the equipment pad and we will tell you what we see and what the job involves."),
    "takeout_h": "How bees come out of a pool cage or pad",
    "takeout": [
        ("Find the colony", "We trace the flight line to one entry point, then scan the beam or housing with a thermal camera to find where the comb sits inside so only that section gets opened."),
        ("Make the area safe", "Power to the pump, heater and lights on the pad is turned off at the breaker, the pool area is cleared, and the doors to the house stay shut."),
        ("Open at the right spot", "An end cap comes off, a screen panel is unsplined, or a cover or cabinet door is removed. On a beam, a small access cut is made only where the colony is."),
        ("Collect the bees alive", "Bees are drawn into a ventilated box with gentle suction, the comb is cut out in pieces, and the colony goes to a beekeeper to be rehomed."),
        ("Clean the cavity out", "Leftover honey and wax are scraped out of the beam or housing, because the smell draws new scouts back to the same hollow."),
    ],
    "putback": "Once the cavity is clean, the access cut is patched, missing or broken end caps are replaced, open fastener holes are filled, and any panel that came out is respined and tensioned so the cage closes as it did before. Housings and covers on the pad go back on and the equipment is ready to restart. Bigger repairs, such as a damaged gutter run or several new panels, are done by our own licensed contractors. If bees return to a spot we sealed, we come back out. The [[svc:repairs|repairs after removal]] page covers that work in more detail.",
    "price": "A colony in a pump cover, a heater cabinet or a low post you can reach from the deck is a ground-level job, usually about $300 to $400. A colony high in the roof beams, or one that means cutting into a gutter or replacing a run of screen, costs more and can reach the thousands when repairs are involved. Calls at night or on weekends cost more than a weekday visit. The quote is free, and the [[page:cost|cost page]] explains how jobs are priced.",
    "price_factors": [
        "How high the colony sits in the frame and whether a ladder or lift is needed.",
        "Whether a beam or gutter has to be cut open rather than reached through an end cap.",
        "How many screen panels come out and have to be respined.",
        "How much comb is inside and how long the colony has been there.",
        "Night or weekend emergency timing.",
    ],
    "miami_h": "Where pool cage colonies come up in Miami-Dade",
    "miami": [
        ("pinecrest", "[[city:pinecrest|Pinecrest]] grew around ranch houses on one-acre lots in the 1950s and 1960s, with heavy landscaping. On a big lot the equipment pad can sit far from the back door, where a colony goes unchecked for weeks."),
        ("homestead", "Hurricane Andrew came ashore near [[city:homestead|Homestead]] in 1992 and much of the city was rebuilt. Enclosures put up since then were built to wind-load rules, and a storm can still tear caps and screens loose. See [[guide:after-a-storm|bees after a storm]]."),
        ("miami-lakes", "[[city:miami-lakes|Miami Lakes]] was laid out from 1962 around curving lakes, with homes backing onto the water. When a cage sits on the lake side, the only safe route to the colony may be through the house."),
        ("doral", "[[city:doral|Doral]] grew from the 1962 country club into neighborhoods like Doral Park and Doral Estates. Shared pools in a community mean an equipment room, a fence and a manager to coordinate with, so see [[svc:hoa-commercial|HOA and property manager removal]]."),
    ],
    "faqs": [
        ("Can we keep using the pool while bees live in the cage?", "Not near the colony. Splashing, pool toys and a running pump all bring guards out, and a swimmer cannot get away quickly. If the colony is at the far end of a large enclosure and the bees ignore you, short trips across the deck are one thing, but swimming should wait until the colony is out."),
        ("Bees are inside my pool heater. Can I run it?", "Leave it off and switch it off at the breaker if you can get there safely. Heat, fans and vibration upset the colony, and comb built against wiring or controls is a problem for the heater too. Once the bees and comb are out, have the heater checked by your pool or gas service before it runs again."),
        ("Why not spray into the beam and be done?", "Whatever you spray into the frame can run down into the pool, and the dead colony stays behind. Honey and wax left inside a hollow beam rot and drip, and the scent pulls new scouts to the same hole. Our [[guide:why-bees-come-back|guide on why bees come back]] explains why the cavity has to be emptied and closed."),
        ("Will removing a screen panel break my pool barrier?", "Only for as long as it is out. A screen enclosure can count as the pool barrier under the Florida Building Code, so panels and doors are put back or the gap is blocked before the visit ends. Keep children away from the pool area while the work is underway."),
        ("Our condo pool has bees in the equipment room. What do you need from us?", "Access to the room, a contact who can shut off power to the pumps, and any rules the board sets for contractors. We are licensed and insured and can send a certificate of insurance to the manager ahead of the visit. A swarm hanging on the fence is simpler; see [[svc:swarms|swarm pickup]]."),
    ],
    "related": ["utility-boxes", "soffits-eaves", "honeycomb-cleanup", "repairs", "hoa-commercial"],
    "close": ("Get the bees out of the frame", "Call or send the quote form with where the bees go in. Phones are answered day and night, and the response guarantee is 24 hours."),
    "facts": [
        "Africanized honey bees nest in a much smaller volume than European honey bees and have been found in water meter boxes, cement blocks and house eaves; they are agitated by vibration from power equipment and lawnmowers; they have been found in Florida (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "Miami-Dade Product Control checklist for screen enclosure approval requires calculations for a design pressure per chapter 20 of the Florida Building Code, including frame stresses, fasteners, foundation and anchorage; fabricators identify each structural member (extrusion) under the NOA (source: https://www.miamidade.gov/building/library/checklists/screen-enclosures.pdf)",
        "Florida Building Code R4501.17.1.11: standard screen enclosures meeting R4501.17 may be used as part or all of the pool barrier; barrier top at least 48 inches above grade (source: https://www.miamidade.gov/permits/library/presentations/pool-barriers.pdf)",
        "Florida Statute 515.27 requires a new residential pool to have at least one safety feature: a barrier, an approved safety cover, exit alarms, self-closing doors or a pool alarm (source: https://www.flsenate.gov/Laws/Statutes/2024/515.27)",
        "Miami-Dade is in the High-Velocity Hurricane Zone of the Florida Building Code (source: https://en.wikipedia.org/wiki/Florida_Building_Code)",
        "Hurricane Andrew made landfall just northeast of Homestead on August 24, 1992; about 70% of damaged or destroyed Homestead homes were repaired or rebuilt within about two years (source: https://en.wikipedia.org/wiki/Hurricane_Andrew)",
        "Pinecrest developed in the 1950s and 1960s with ranch-style houses on 1-acre lots and a lushly landscaped residential character; incorporated 1996 (source: https://en.wikipedia.org/wiki/Pinecrest,_Florida)",
        "Miami Lakes was built by Sengra (now the Graham Companies) beginning in 1962 with numerous curving lakes; incorporated as a town in 2000 (source: https://en.wikipedia.org/wiki/Miami_Lakes,_Florida)",
        "Doral Country Club opened in 1962; residential neighborhoods such as Doral Estates and Doral Park developed later; the city incorporated in 2003 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
    ],
}
