# -*- coding: utf-8 -*-
"""Colony relocation to beekeepers page copy."""

SERVICE = {
    "slug": "relocation",
    "title": "Bee Relocation in Miami-Dade: Wall to Beekeeper",
    "desc": "Bee relocation in Miami-Dade, step by step: how a captured colony is framed, boxed, driven off at dusk and handed to a beekeeper instead of poisoned.",
    "h1": "Bee Relocation in Miami-Dade: What Happens After the Colony Leaves Your House",
    "kicker": "After the capture",
    "lede": "Getting bees out of a soffit is only half the job. The other half is the drive, the hand-off and the new hive box, and that half decides whether the colony lives.",
    "quick": "Relocation means the colony comes out alive, comb and all, and moves to a beekeeper's apiary far enough from your property that the foragers cannot find their way back. Nothing is sprayed. Young brood rides in wooden frames beside its nurse bees, the queen stays with her daughters, and the lid goes on for transport only after the field bees have come home. Florida's agriculture department tells homeowners to ask any removal company where the bees will end up. Ask us that question, and you will get a plain answer: a beekeeper's yard.",
    "alarm": "Someone under attack needs walls or a car door between them and the bees, so move indoors and close up; skip the pool, since bees hover over the water until you surface. Flick each stinger off sideways with a card edge. Dial 911 for a swollen throat, wheezing or dozens of stings. Our phones come next, and a sting victim jumps every other call in the queue.",
    "card": "What happens to a colony after it leaves your walls: careful packing, an evening drive to a beekeeper and a new hive box, never a can of poison.",
    "seeing_h": "Why you are reading about relocation",
    "seeing": [
        "A pest company quoted you a spray treatment, and you would rather the bees end up alive somewhere useful than dead inside your wall.",
        "A swarm is hanging in a clump on a branch or a fence post, and you want to know whether someone can simply carry it away.",
        "Your condo board or HOA wants it in writing that a removal sends live colonies to a beekeeper and not into a trash bag.",
        "Bees were killed in this spot before, and now a fresh colony has moved into the cavity where the old comb was left.",
        "You keep wondering what actually becomes of the bees once the truck pulls out of your driveway.",
    ],
    "behind": "A honey bee colony is one working unit: a single queen, thousands of workers and a nest of wax comb holding eggs, larvae, pollen and honey. It survives a move only if those parts travel together and land somewhere with space, forage and a person to manage it. Spraying sidesteps that by killing the colony in place, yet the comb stays behind. Unguarded honey draws robber bees from other hives, the scent invites the next swarm into the same hollow, and dead brood rots against your drywall. Relocation takes the whole nest out, which removes the attraction along with the insects, and it keeps a productive colony at work making honey or pollinating crops. The scent trail is covered in our field guide piece on [[guide:why-bees-come-back|repeat colonies]].",
    "body": [
        ("From the cavity to the hive box",
         "With the wall or soffit opened, the nest is taken apart one wax panel at a time. Brood comb, the cells holding capped or growing young, is the colony's future, so it is trimmed to size and held inside empty wooden frames with rubber bands or string. Those frames go into the hive box in roughly the order they hung in the wall, since bees keep brood at the center of the nest and stores at the edges. Heavy honey comb is too soft to frame, so it is packed separately in sealed containers as part of [[svc:honeycomb-cleanup|comb and honey cleanup]]. Loose bees are gathered with a low-suction bee vacuum that drops them into a screened chamber without crushing them. The queen matters most. If she is spotted, she is caged and set in the box; if not, workers fanning at the box entrance with their tails raised are a fair sign she made it inside."),
        ("Why the box waits for dark",
         "Foragers spend the day in the field, and any still out when the box is closed will return to an empty hole. So the box stays beside the original entrance until evening, when nearly every field bee has flown home and settled. Then the entrance is screened shut and the box is strapped down for the drive. Distance matters as much as timing. A worker memorizes the landmarks around her home, and a colony shifted only a few hundred yards loses its older bees back to your house. Taking it miles away forces every forager to reorient and learn the new site. Heat is the other risk. A closed box in a parked vehicle on a Miami afternoon can cook brood, which is one more reason the move happens in the cooler hours with ventilation screens in place."),
        ("Life in the beekeeper's yard",
         "At the apiary the box goes onto a stand, the screen comes off and the colony gets a few days to calm down. The beekeeper then checks that the queen is laying, feeds the colony if its stores were lost in the move, and watches for small hive beetles and varroa mites, which hit a stressed colony hardest. Any colony in South Florida could carry African genetics, and the state agriculture department notes that only a genetic test can tell African and European bees apart. UF/IFAS extension material describes beekeepers in African bee areas requeening with European queens, and the colony's temper shifts over the following weeks as her daughters replace the old workers. Whatever the keeper decides, the bees are now managed instead of living unchecked inside a building, as they did in your [[svc:walls|block or frame wall]]."),
        ("What Florida law says about relocation",
         "Florida treats bees as both a pest and part of agriculture, and the state rule that separates the two is specific. Under Rule 5E-14.151 of the Florida Administrative Code, removing and relocating bees from a structure, lawn or ornamental planting for honey production or crop pollination is not pest control when a beekeeper registered with the state does it. Removing bees to get rid of them as pests is pest control, and the agriculture department reserves eradication for pest control firms holding a state license. That split hands you a useful question for any company you call: where are the bees going? A clear answer names a beekeeper. If nobody can tell you, assume the plan is poison, and keep looking."),
    ],
    "band": ("Ask where your bees will live",
             "Phone or send a picture of where the bees fly in, and you will learn how they leave and whose apiary takes them."),
    "takeout_h": "How a relocation job runs",
    "takeout": [
        ("Find the whole nest",
         "A thermal camera reads the heat a living nest gives off, which lets the cut land over the comb itself instead of at the doorway the bees use. See [[guide:thermal-imaging|what thermal imaging shows]]."),
        ("Open up and frame comb",
         "The cavity is opened, brood comb is cut and fitted into frames, and honey comb is packed separately in sealed containers so it cannot drip into the wall or the box."),
        ("Gather the bees and queen",
         "A gentle bee vacuum collects loose workers into a screened chamber, and the queen is caged whenever she can be found so the colony stays in one piece."),
        ("Wait, screen, drive",
         "The box sits by the old entrance until foragers come home in the evening, then it is screened, strapped down and driven out to the beekeeper's apiary."),
        ("Close the empty cavity",
         "Leftover wax is scraped out, the hollow is cleaned and the entry is sealed so the lingering scent does not pull a new swarm into the same space."),
    ],
    "putback": "Moving the colony is wasted effort if the hollow stays open, because a cleaned-out wall still smells like a home to the next scout bees. After the comb comes out, the space is scraped to bare surfaces and honey residue is wiped away. The entry gap is closed, and any stucco, soffit, drywall or tile removed to reach the nest is rebuilt by licensed tradespeople on our own crew, including roofers and painters, as part of [[svc:repairs|repairs after removal]]. A warranty stands behind that workmanship, so a colony settling again where we closed things up earns you a return trip. Ask for pictures and an itemized bill, and both come with the job.",
    "price": "A ground-level relocation, such as a swarm on a shrub or a colony in a meter box, generally lands around $300 to $400. Colonies built deep inside a wall, roof or ceiling cost more, sometimes into the thousands, because the price then covers opening the structure, saving the comb and repairing what was opened. Night and weekend emergency visits run higher than weekday appointments. The quote is free, and the invoice is itemized, so you can see which part pays for the bees' move and which part pays for your building. Ranges for other jobs sit on the [[page:cost|pricing overview]].",
    "price_factors": [
        "How far into the structure the comb runs, and how much must be opened to reach all of it",
        "Whether a ladder, lift or roof access is needed to reach the entrance safely",
        "Colony size and the weight of honey comb that has to be hauled out",
        "Repairs to stucco, tile, soffit or drywall once the nest is gone",
        "Emergency timing, since an after-dark or Saturday and Sunday callout is billed above a weekday slot",
    ],
    "miami_h": "Where relocation comes up around the county",
    "miami": [
        ("miami-beach",
         "Miami Beach sits on barrier islands between Biscayne Bay and the Atlantic, packed with Art Deco buildings and high-rise condos. A condo lot or a tight courtyard is no place to keep a hive box, so a colony captured there usually leaves over a causeway to the mainland."),
        ("redland",
         "Zoning in this unincorporated farm district keeps each house on five acres or more, among avocado groves and orchid and plant nurseries. Boxing a colony and trucking it off avoids putting insecticide anywhere near a grower's stock."),
        ("homestead",
         "Homestead, incorporated in 1913, sits between Biscayne and Everglades national parks with farmland at its edges. Relocating a colony from a house there keeps insecticide out of yards that sit close to working fields."),
        ("kendall",
         "Kendall is an unincorporated area that turned from pine rockland, fields and groves into suburbs from the 1950s on. A colony taken from one of its yards must go miles away, or the foragers simply return to the hedge next door."),
    ],
    "faqs": [
        ("Will the bees survive being moved to a new place?",
         "A colony moved with its comb, its queen and most of its workers has a good chance, provided the box stays cool on the road. If the queen is lost, the workers can raise a new one from young larvae in the brood comb, which is why brood is framed instead of thrown out. The shakiest stretch is the first week at the apiary, when the beekeeper checks for laying, food stores and pests."),
        ("Why not set the colony down a few yards away, behind the garage?",
         "Because they would be home again by lunch. Bees navigate by landmarks, so a colony shifted a short distance sends its older foragers straight back to the original entrance, where they cluster with nowhere to go. Moving the colony miles away resets their map. It also takes the bees away from a spot where people, pets and lawn equipment pass every day."),
        ("What happens to the honey and wax left from the nest?",
         "Honey-filled panels are sealed in containers and hauled off with the colony instead of being left in your wall to ferment, stain and draw pests. Brood comb travels with the bees in their new frames. Any thin smear of wax left on the framing is scraped away before the cavity is sealed, because that scent is what calls the next swarm."),
        ("Are relocated Miami bees Africanized, and does that change anything?",
         "Nobody can tell by looking. Florida's agriculture department says a genetic test is the only way to separate African from European honey bees, so every colony here deserves caution whatever its mood. That is a good reason to leave a colony in a wall to people with suits and gear, and a reason a [[svc:swarms|swarm on a branch]] should not be poked with a broom either."),
        ("How do I know my bees really went to a beekeeper?",
         "Ask, and expect a specific answer. Florida's rules treat live removal for honey or pollination differently from pest control, and the state agriculture department advises consumers to ask where removed bees are taken. Photos from the job are available if you want them, and the itemized invoice lists the relocation next to any repair work."),
        ("Is relocation safer for kids and pets than spraying?",
         "In one plain way, yes: no pesticide goes into your walls, yard or air. During the work, keep children and animals indoors and away from the opening, because disturbed bees defend their nest. Once the box is closed and gone, the area is ordinary again, with no dead colony left to rot or attract robbing bees from elsewhere. If the bees are aggressive right now, see [[svc:emergency|24-hour emergency removal]]."),
    ],
    "related": ["live-honey-bees", "beehives", "swarms", "honeycomb-cleanup", "repairs"],
    "close": ("Give your bees somewhere to go",
              "Fill in the request below with a picture if you can, and the reply will cover extraction, the destination apiary and repair work."),
    "facts": [
        "Beekeepers hired for live honey bee removal must be registered with the Florida Department of Agriculture and Consumer Services but need not hold a Chapter 482 pest control license; only a licensed pest control company may eradicate a colony; consumers are advised to ask about relocation destinations; genetic testing is required to tell African from European honey bees (source: https://www.fdacs.gov/Consumer-Resources/Consumer-Rights-and-Responsibilities/Pest-Control/Honey-Bee-Removal-or-Eradication-in-Florida)",
        "Rule 5E-14.151, F.A.C., 'Removal and Relocation of Bees from Structures, Lawns or Ornamentals': removal and relocation by a beekeeper registered under s. 586.045 for honey production or pollination is not pest control; removal to eliminate bees as a pest, or by an unregistered person, is pest control (source: https://www.law.cornell.edu/regulations/florida/Fla-Admin-Code-Ann-R-5E-14-151 and https://www.flrules.org/gateway/ruleNo.asp?id=5E-14.151)",
        "Section 586.045, Florida Statutes: each beekeeper having honeybee colonies in the state must apply to the department for certificates of inspection and registration (source: https://www.flsenate.gov/Laws/Statutes/2025/Chapter586/All)",
        "Some beekeepers in areas with African bees requeen African colonies with European queens (source: UF/IFAS EDIS IN790, https://ask.ifas.ufl.edu/publication/IN790)",
        "Miami Beach is on natural and human-made barrier islands between the Atlantic Ocean and Biscayne Bay, linked to the mainland by causeways; it has the Art Deco Historic District and many high-rise condominiums (source: https://en.wikipedia.org/wiki/Miami_Beach,_Florida)",
        "Redland is a historic unincorporated agricultural area with tropical fruit (avocado the largest crop) and a large concentration of ornamental nurseries; agricultural/residential zoning requires a minimum of 5 acres per house (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Homestead was incorporated in 1913, is a city and a major agricultural area, and lies between Biscayne National Park and Everglades National Park (source: https://en.wikipedia.org/wiki/Homestead,_Florida)",
        "Kendall is an unincorporated area and CDP; before suburban development began in the 1950s it was pine rockland interspersed with fields and groves (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
    ],
}
