# -*- coding: utf-8 -*-
"""Sheds, garages and outbuildings removal page copy."""

SERVICE = {
    "slug": "sheds-garages",
    "title": "Shed, Garage and Workshop Colonies Moved Alive, Miami-Dade",
    "desc": "A colony in your shed, detached garage, workshop, outdoor kitchen or a car you rarely drive? We open what holds it, move the bees alive and clean up.",
    "h1": "Bees in Your Shed, Garage or Workshop in Miami-Dade",
    "kicker": "Outbuildings and stored things",
    "lede": "The building you only open once a month is the one a swarm likes best. Here is how a colony gets into a shed, a garage or the things stored inside, and how it comes out alive.",
    "quick": "If bees are coming and going from a shed seam, a garage door header, a parked car or a grill cabinet, a colony has probably built comb inside. Keep the door shut, keep the mower and trimmer away, and do not spray anything. The fix is to unscrew whatever hides the comb, vacuum the bees into a ventilated box and drive them to an apiary. Because a shed or grill can usually be unbolted rather than cut, many of these jobs sit in the $300 to $400 range, with no charge for quoting it.",
    "card": "Colonies inside sheds, detached garages, workshops, outdoor kitchens and the cars, boats or furniture stored in them, opened carefully and moved alive.",
    "seeing_h": "What tends to tip you off",
    "seeing": [
        "Bees streaming into one corner of a metal or resin shed, most often the joint where a roof panel overlaps the wall.",
        "Bees crawling out of the gap above a detached garage door, or along the track and header when the door rolls up.",
        "Bees using the grille, a wheel well or a vent on a car, trailer or boat that has not moved in weeks.",
        "Honey or dark wax stains running down a stored dresser, a cabinet or the base of a shed wall.",
        "Bees circling the grill hood or slipping into the doors under an outdoor kitchen counter.",
        "A loud hum when you open the shed, or bees bumping your face as soon as the string trimmer starts nearby.",
    ],
    "behind": "A honey bee swarm is house hunting for a dark, dry, sheltered hollow with a small entrance it can defend. A closed shed or a garage nobody parks in reads like a giant hollow tree: still air, no foot traffic and plenty of boxes, drawers and double-walled panels to build inside. Once the scouts agree, the whole cluster moves in and starts drawing comb within days. Africanized honey bees are less picky still and will settle in small spaces like old tires, cement blocks and barbecue grills. Every week the door stays shut, the comb grows and so does the honey that will need cleaning.",
    "body": [
        ("When the hive is in what you stored",
         "In an outbuilding, the colony often is not in the building at all. It is inside something you put there. A dresser drawer left a finger-width open, the hollow base of a sofa, a stack of tires, a cooler with a cracked lid, a riding mower's hood, a boxed-up air conditioner or a pile of old pavers can all hold comb. Cars and boats that sit for a season are another favorite: the space behind a grille, an air intake, a trunk seam, a boat console or an RV storage bay.\n\nThis is actually good news for the bill. A drawer can be pulled out and a panel can be unbolted, so nothing structural has to be cut. The bees are vacuumed off gently, each sheet of comb is cut loose and lifted clear, and the item is wiped down so you can keep it. If you are not sure whether the comb is in the walls of a garage or in the things leaning against them, a [[guide:thermal-imaging|thermal camera scan]] usually settles it before anything is opened."),
        ("Outdoor kitchens, grills and summer kitchens",
         "University of Florida entomologists list barbecue grills among the places Africanized honey bees have nested, and a built-in outdoor kitchen is a grill with extra cabinets underneath. The cavities behind the doors, under the burner tray and inside a side burner housing are dark and dry for weeks at a time between parties. The first sign is often bees around the hood vents or a smell of warm wax when the grill heats up.\n\nPlease do not light the grill to drive them out. Heat softens comb, honey runs into the gas valves and the bees get defensive at exactly the moment you are standing over them. The right fix is to shut off the gas, open the cabinet or lift the grill head, take the bees and comb out, and then clean the honey off the hardware so ants and roaches do not follow. If the colony has moved on into a nearby [[svc:utility-boxes|meter or irrigation box]], that box gets checked too."),
        ("Detached garages and block workshops",
         "A garage or workshop built like a small house is a different job from a prefab shed. Bees can slip in where stucco has cracked, where fascia has pulled away or under a loose roof tile, and then the comb may sit inside the hollow cores of the block, in the roof framing or behind the door header. That work overlaps with what we do for [[svc:walls|bees inside block walls]], [[svc:roofs|tile and flat roof hives]] and [[svc:soffits-eaves|soffit and eave colonies]].\n\nWorkshops have one extra hazard: vibration. A table saw, a compressor or a leaf blower running a few feet from a colony can set off a defensive response, especially with Africanized bees. If you work in that space, stop using power tools until the bees are gone. Once the comb is out, our own licensed contractors and roofers close the opening, and any wall or ceiling that had to be opened is put back by the same crew under our [[svc:repairs|repair work]]."),
        ("A note on replacing a prefab shed",
         "Sometimes the shed itself is past saving: rusted panels, a rotted floor, a door that never shuts. If you decide to replace it, Miami-Dade County's permitting office describes a residential utility shed as a single-story, non-habitable detached building for storage only, and for a pre-manufactured shed it asks for the product's current Notice of Acceptance with the permit. Its rules allow one such shed per property, up to 400 square feet. If you live inside a city, village or town, check with its building department as well before you buy.\n\nEither way, get the bees out before the old shed is pulled apart. Prying panels off an occupied shed crushes comb, spills honey across the slab and puts thousands of defensive bees in the air around whoever is holding the pry bar. A clean removal first also tells you where the bees got in, which matters if the new shed goes on the same spot. Honey bees are drawn back to places that smell like an old nest, a pattern explained in our guide on [[guide:why-bees-come-back|why bees come back]]."),
    ],
    "band": ("Shed shut, comb still growing", "Snap the gap the bees use and tell us what is stacked beside it. That is enough to plan the job."),
    "takeout_h": "How an outbuilding removal works",
    "takeout": [
        ("Look before opening",
         "We ask what is stored inside, whether there is power, gas or fuel near the colony, and how close kids, pets and neighbors are. The door stays shut until we are suited up."),
        ("Find the comb",
         "A thermal camera picks up the warm cluster behind a shed panel or a garage wall, so we open only the panel, drawer or housing that holds the hive."),
        ("Open the smallest piece",
         "Screws come out, a panel lifts, a drawer slides free or a grill head is raised. On block garages the opening is cut as small and neat as the comb allows."),
        ("Bees and comb out alive",
         "Workers clinging to the panel or drawer ride a low-suction hose into a box with screened sides. Comb carrying eggs and larvae is tied into empty frames, so brood, queen and colony reach the beekeeper together."),
        ("Clean and close",
         "Honey and wax are scraped and washed off the walls and stored goods, the entrance is sealed, and you get photos of each stage when you ask for them."),
    ],
    "putback": "On a prefab shed, the panel goes back with fresh fasteners and the gaps at the roof seam and door frame are closed with screen or sealant. On a block garage, our licensed contractors patch the block or stucco, our roofers reset tiles or flashing, and our painters match the finish. Sticky residue on shelving and on the slab is a beacon for ants, roaches and the next scouting party, which is why [[svc:honeycomb-cleanup|comb and honey cleanup]] comes with the removal. Our workmanship carries a warranty with a plain promise: a shed seam or garage gap we closed that draws bees again earns a return trip from us.",
    "price": "Outbuildings tend to be the gentler bill, because the colony is low and sits in something that unscrews. When the job is just sliding out a drawer, unbolting a resin panel or raising a grill head without a ladder, expect roughly $300 to $400. Comb threaded through a garage's block wall or roof is another matter: opening and rebuilding it with our contractors and roofers pushes the total into the thousands. Evening and weekend emergencies are billed higher than weekday work. Quoting it costs you nothing, and an itemized invoice is yours if you ask. Our [[page:cost|cost page]] has more.",
    "price_factors": [
        "Whether the comb sits in a removable panel, drawer or grill cabinet, or inside block and roof framing",
        "How big the colony has grown and how much honey has to be cleaned off stored goods",
        "Whether the spot is reachable from the ground or needs a ladder onto a garage roof",
        "Repairs afterward: new shed fasteners and sealant, or block, stucco, roof and paint work",
        "Timing: bees that cannot wait past sundown or until Monday cost more to handle",
    ],
    "miami_h": "Where in Miami-Dade outbuildings matter",
    "miami": [
        ("redland",
         "Redland is an unincorporated farm area where agricultural zoning calls for homes on at least five acres, among avocado groves and ornamental nurseries. Barns, pump houses and equipment sheds can stand a long walk from the house, and nobody may look inside them for weeks. See also our [[svc:nurseries-groves|farm and nursery page]]."),
        ("pinecrest",
         "Pinecrest filled in during the 1950s and 1960s, mostly with ranch homes, each on roughly an acre of land, and the village now carries a Tree City USA designation for its street planting. On lots that size, a backyard storage building or a workshop under the trees can go unopened for long stretches."),
        ("homestead",
         "Homestead, incorporated in 1913, sits in a major farming area, and in 1992 it was among the South Miami-Dade communities hit hardest by Hurricane Andrew. Any shed or barn with a storm-loosened panel or a sprung door offers exactly the gap a swarm looks for. Our [[guide:after-a-storm|after-a-storm guide]] covers colonies exposed by wind."),
        ("doral",
         "Miami International Airport is roughly five miles east of Doral, and that short haul has given the city many importers and exporters for its size. Wherever trucks, trailers and pallets sit idle in a yard, a swarm has places to move in. A yard manager who needs our insurance paperwork on file gets it first."),
    ],
    "alarm": "Mower running and bees pouring out of the shed? Walk off fast, get into the house or a car and shut the door; swatting only draws more. Leave the shed open unless closing it keeps you clear of their flight line. Swelling of the face or a struggle to breathe means dialing 911. Once that is handled, phone us day or night: stinging jumps ahead of every other call, backed by our 24-hour response guarantee. More on [[svc:emergency|emergency removal]].",
    "faqs": [
        ("Can I just leave the shed shut until the bees go away?",
         "Honey bees rarely leave on their own once they have built comb and raised brood. A closed shed only gives the colony more time to grow, and each month adds honey that will need cleaning. If the bees are still just clustered and have not built anything yet, that is a [[svc:swarms|swarm pickup]], which is quicker and simpler."),
        ("Months without driving, and now bees use the grille. Can I start the car?",
         "Do not start it, and do not open the hood. Engine heat and vibration can set off the colony and melt comb into the air intake or wiring. Leave the car where it is, keep people away from the grille, and let us find and lift out the comb first."),
        ("Does the whole shed have to come apart to reach the comb?",
         "Usually not. Most prefab metal and resin sheds are bolted or screwed together, so the panel holding the comb can be taken off and put back. On a block garage, the opening is kept as small as the comb allows and our own contractors close it afterward."),
        ("Can you save the furniture or boxes the bees built in?",
         "Often yes. Comb can be cut away from a drawer or cabinet and the honey washed off sealed wood, plastic and metal. Soft items like a mattress, cardboard boxes or upholstery soaked with honey are usually not worth keeping, and we will tell you honestly which is which."),
        ("Do you need my HOA or property manager to sign off first?",
         "Not to come out and quote it. For an outbuilding on shared land, a rental or a commercial yard, your board or manager can have our certificate of insurance in hand before anyone opens the shed. Landlords and tenants can read our guide on [[guide:renters-and-landlords|who handles bees in a rental]]."),
        ("Why did bees pick the shed and not the house?",
         "Scouts look for the darkest, driest, quietest hollow they can find with a small doorway. A shed that stays shut fits that better than a busy house. Watching for [[guide:scout-bees|scout bees]] near the door is the early warning, and checking it often helps, especially at a [[guide:second-home|seasonal home]]."),
    ],
    "related": ["walls", "roofs", "utility-boxes", "honeycomb-cleanup", "relocation"],
    "close": ("Get the shed back without losing the bees", "A photo of the shed door with the bees' entrance in frame, texted over, gets the plan started, and the quote form works too. Every colony ends up with a beekeeper through our [[svc:relocation|relocation work]], never killed."),
    "facts": [
        "African honey bees nest in smaller volumes than European bees and have been found in water meter boxes, cement blocks, old tires, house eaves, barbecue grills and ground cavities (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "African honey bees are less selective about nest sites than European bees (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "Miami-Dade County permitting describes a residential utility shed as a single-story, non-habitable detached building accessory to the residence and for storage only; one per property, max 400 sq ft; pre-manufactured sheds require the current Notice of Acceptance (source: https://www.miamidade.gov/global/economy/building/permits/shed-aluminum-terrace.page)",
        "Redland is a historic unincorporated community and agricultural area; agricultural zoning requires houses on a minimum of 5 acres; avocados are the largest crop and ornamental nurseries are concentrated there (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Pinecrest developed in the 1950s and 1960s with ranch-style houses on 1-acre lots; incorporated as a village in 1996; planted over 10,000 street trees since 1997 and was named a Tree City USA community (source: https://en.wikipedia.org/wiki/Pinecrest,_Florida)",
        "Homestead was incorporated in 1913, is a major agricultural area, and with neighboring South Miami-Dade communities bore the brunt of Hurricane Andrew on August 24, 1992 (source: https://en.wikipedia.org/wiki/Homestead,_Florida)",
        "Doral is about 5 miles west of Miami International Airport and, for a city its size, has many businesses, especially importers and exporters, because of its proximity to the airport (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
    ],
}
