# -*- coding: utf-8 -*-
"""Palm and tree colonies removal page copy."""

SERVICE = {
    "slug": "trees-palms",
    "title": "Bees in a Palm or Hollow Tree? Out Alive, Tree Kept",
    "desc": "Bees in a palm, live oak, mango or ficus? The colony comes out alive for a beekeeper, the hollow is cleaned and closed, and the tree can stay standing.",
    "h1": "Bees in Palm Trees and Hollow Trunks Across Miami-Dade",
    "kicker": "Palms, oaks and hollow trunks",
    "lede": "A colony tucked into palm boots, a split live oak or an old mango limb can come out alive, and the tree can usually stay where it is if its own health allows.",
    "quick": "A hollow trunk is the home honey bees picked long before houses existed, so a tree colony is bees doing exactly what they evolved to do. On a palm, the comb is usually wedged among old frond bases, which can be peeled back. On an oak, mango or ficus, a small window is cut into the hollow, sized to the comb. Either way the bees go into a box alive and on to a beekeeper, the cavity is scraped and closed, and you keep your tree.",
    "card": "Colonies in palm boots and in hollow oak, mango and ficus trunks, taken out alive, with the cavity closed so the tree can keep standing.",
    "seeing_h": "What you might be noticing out in the yard",
    "seeing": [
        "Steady traffic at a single point on the trunk, usually a knot hole, a crack or an old pruning cut that never sealed over.",
        "Bees crawling in and out between the old leaf bases on a palm, with a low hum you can pick up from the ground below.",
        "A dark, sticky trail running down the bark under an opening, which can be honey or softened wax leaking from comb inside.",
        "Bees chasing the mower or the string trimmer every time it passes the base of one particular tree, and leaving you alone elsewhere.",
        "A trimming crew or arborist who stopped halfway up the trunk, climbed down and told you to call someone about the bees first.",
    ],
    "behind": "Honey bees are cavity nesters. Before chimneys and wall voids, a hollow tree was where a wild colony lived, and a swarm still goes looking for the same thing: a dry, dark space with a narrow way in. A trunk that has rotted out behind an old wound, the pocket left where a big limb broke off, or the layered frond bases on a palm all qualify. The colony hangs sheets of comb from the top of that space and stores honey above the brood. What you see from the lawn is just the entrance; inside the hollow, the brood and honey can be well above or below it. African-derived honey bees are present in Florida and will settle in smaller spaces and defend a wider area around the nest, so a tree beside a pool, a swing set or a driveway deserves attention sooner rather than later.",
    "body": [
        ("Palm boots are not the same job as a hollow oak",
         "The sabal palm, Florida's state tree, holds on to its dead leaf bases for a while after the fronds drop, and they stack up on the trunk in a crisscross pattern people call boots. Each one leaves a pocket against the trunk, and a swarm can build comb right into those pockets, spread across several bases. Because the palm does not need the old boots, they can be pried loose one at a time until the comb is exposed and lifted out. A palm trunk itself is not usually hollow the way an aging hardwood is. Live oaks, mangoes and ficus are different: their colonies sit inside a true cavity, often behind a narrow opening, so the comb has to be reached by cutting a controlled window into the wall of the hollow. Knowing which kind of tree you have tells you a lot about how big the job is before anyone arrives. If the bees are in a structure instead, see [[svc:walls|hives inside a wall]] or [[svc:soffits-eaves|colonies in the eaves]]."),
        ("Before the trimming crew or arborist goes back up",
         "A chainsaw biting into an occupied trunk, or a limb crashing down with comb inside it, sets off the colony's defense all at once, with a worker on a ladder or in a bucket right in the middle of it. The safer order is bees first, saw second. Tell the crew to hold off, keep people and pets away from that tree, and photograph the gap the bees use along with a wide shot from the street, which tells us how high the work is and how a ladder gets in. Once the colony is out and the cavity is closed, the trimmers can finish the canopy. If an arborist has already said the tree must come down, let us know: taking the comb out before the cut keeps the bees alive for relocation. Note too that Florida law lets the owner of a single-family home remove a tree without a local permit when an arborist credentialed by the International Society of Arboriculture, or a Florida licensed landscape architect, documents that it poses an unacceptable risk to people or property. A colony on its own does not make a tree a risk; a rotten, leaning trunk might."),
        ("Saving the tree, and the permit question",
         "Cutting a tree down just to be rid of bees costs you shade and can land you in paperwork. Miami-Dade County requires a tree removal or relocation permit for any tree that is not specifically exempt under the county code, and it counts as a tree anything with a trunk at least three inches across at breast height or an overall height of twelve feet or more. Several municipalities have their own tree ordinances, including [[city:coral-gables|Coral Gables]], [[city:miami|Miami]], [[city:miami-beach|Miami Beach]], [[city:pinecrest|Pinecrest]] and [[city:homestead|Homestead]]. Taking a colony out of a cavity is not taking the tree out, so the tree, its roots and its standing with the permit office stay as they were. Storm damage changes the picture: weeping figs (Ficus benjamina) are considered a high risk for failing in hurricane winds, and a snapped limb can lay open comb nobody knew was there. If that happens, read [[guide:after-a-storm|what to do when a storm opens up a hive]] before going near it."),
    ],
    "band": ("Bees in the trunk and a crew on the calendar?",
             "A quick picture of the trunk sent by text helps us plan the bees' exit around the trimmers' return date."),
    "takeout_h": "Getting the bees out without felling the tree",
    "takeout": [
        ("Scan the trunk for warm brood",
         "Brood runs warm, so scanning the trunk with [[guide:thermal-imaging|thermal imaging]] marks where the nest sits behind bark or boots and how small an opening will do."),
        ("Clear the area",
         "Children, pets and neighbors are kept well back, the mower stays parked, and we suit up and use a little smoke before anyone touches the bark."),
        ("Open only what is needed",
         "On a palm, old leaf bases are pried loose one by one. On an oak, mango or ficus, a window is cut into the hollow wall, no larger than the comb requires."),
        ("Move bees and comb together",
         "Once the brood comb is cut out and framed, low suction draws the clinging bees into an airy carrier, queen included whenever she can be found, and the colony is driven to a beekeeper."),
        ("Scrape and close the cavity",
         "Leftover wax and honey are scraped out, and the opening is covered with screen or a fitted panel so the scent of the old nest cannot pull in the next swarm."),
    ],
    "putback": "With a tree there is no stucco to patch or tile to relay, so the putback is all about the cavity. Every scrap of comb and honey we can reach comes out, because what stays behind ferments, draws ants and wax moths, and advertises a ready-made home to the next set of scouts. The hollow is then closed with hardware cloth or a fitted cover that lets the wood breathe. On palms, loose boots near the old nest are cleared off. If the hollow looks like a structural problem for the tree, we will tell you plainly so an arborist can judge it. Should a new colony settle in a cavity we closed, that falls under our workmanship warranty and we return to deal with it.",
    "price": "Comb within arm's reach, say in the lower boots of a palm or a waist-high hollow in a mango, generally lands around $300 to $400. Height, the length of comb running through the hollow and the amount of cutting needed all push it up, and complex jobs that include repairs reach into the thousands. Quoting costs you nothing. Emergency work after dark or on weekends is priced above weekday work. For how other kinds of jobs compare, see [[page:cost|what removal costs]].",
    "price_factors": [
        "How high the entrance sits, and whether a tall ladder or a lift is needed to reach it safely",
        "How far the comb extends inside the hollow, measured with thermal imaging before any cutting starts",
        "Whether it is a palm with loose boots, a solid hardwood trunk or a ficus with fused stems",
        "An urgent visit on a Saturday, Sunday or late evening, which carries a premium over weekday work",
    ],
    "miami_h": "Miami-Dade places where big trees and swarms meet",
    "miami": [
        ("redland",
         "This unincorporated farm area grows mango, avocado, lychee and other tropical fruit alongside many ornamental nurseries, so aging fruit trees, which can develop hollow limbs, stand near people working the rows. See [[svc:nurseries-groves|groves and nurseries]]."),
        ("pinecrest",
         "Ranch houses on one-acre lots went up here in the 1950s and 1960s, and the village has planted over 10,000 street trees from 1997 onward, so mature canopy stands close to houses, pools and play sets."),
        ("coconut-grove",
         "This City of Miami neighborhood is known for heavy, hammock-style vegetation, and residents count it among the greenest parts of the city. Big old trees bring cavities with them."),
        ("coral-gables",
         "The city has its own tree ordinance apart from the county's, so check with the city before any tree comes down. Removing only the colony leaves the tree, and that question, alone."),
    ],
    "alarm": "A person being stung matters more than any tree. Get them inside a house or a car, away from the tree, and call 911 for trouble breathing, swelling around the face or throat, or a large number of stings. Do not spray, hose or strike the trunk. Then call: someone picks up day or night, and a sting victim goes to the front of the line.",
    "faqs": [
        ("My palm has bees in its old frond bases. Does it have to be cut down?",
         "Usually not, when the comb sits among the old frond bases. Those dead bases are removed in turn to uncover the comb, the bees are boxed alive, and the bare section of trunk is cleaned. The palm loses nothing it was still using. If comb has worked into the crown itself, we will look at it with you and explain the options before anything is cut."),
        ("Will the tree survive if you cut an opening into the trunk?",
         "A tree that already has a hollow has been living with that cavity, and the window we cut is sized to the comb rather than to our convenience. That said, nobody can promise the future of a tree that is already in decline. If the hollow looks large or the trunk looks weak, we will say so, and a visit from an arborist is the right next step."),
        ("Our tree trimmers hit bees halfway through the job. What should we do now?",
         "Have the crew stop and come down, keep everyone away from that tree, and leave the bees undisturbed. Send us a photo of where they are coming out and a wider shot of the tree. After that, the crew can come back and finish the job with no bees in the way."),
        ("Is there county paperwork for pulling a colony from a trunk?",
         "Removing a colony is not removing a tree, so the county's tree removal permit does not come into it on its own. If you also plan to take the tree down, check first: the county requires a permit for non-exempt trees, and municipalities such as Coral Gables, Miami and Pinecrest have their own tree rules."),
        ("Couldn't someone just spray poison into the hollow?",
         "Killing the bees leaves the comb, honey and dead brood inside the trunk, where they rot, draw pests and leave the scent of an established nest for future scouts to find. We do live, humane removal only, and the bees are handed to a beekeeper. See [[svc:relocation|where relocated colonies go]] and [[guide:why-bees-come-back|why bees return to the same spot]]."),
        ("Bees are draped over a limb with no comb showing. Does that count as a nest?",
         "No. A bare cluster dangling from a limb, without wax under it, is a swarm in transit, waiting on its scouts to settle on a new address, and it can leave of its own accord. Comb appearing on the branch, or a cluster hanging over a door or a pool, is the point to have it collected. Our page on [[svc:swarms|swarm pickup]] explains the difference."),
    ],
    "related": ["swarms", "nurseries-groves", "relocation", "honeycomb-cleanup", "live-honey-bees"],
    "close": ("Colony out of the trunk, tree left standing",
              "Phone us, or attach a picture of the trunk to the quote form, and we will work out how the bees leave while the tree stays put."),
    "facts": [
        "Sabal palmetto is the official state tree of Florida; when leaves die the leaf bases persist for a while, creating a spiky basketweave effect (source: https://en.wikipedia.org/wiki/Sabal_palmetto)",
        "Live oak (Quercus virginiana) has a native range that covers all of mainland Florida (source: https://en.wikipedia.org/wiki/Quercus_virginiana)",
        "Ficus benjamina (weeping fig) is considered a high risk for succumbing to storm gale winds in hurricane-prone areas (source: https://en.wikipedia.org/wiki/Ficus_benjamina)",
        "Swarming western honey bees seek a new nest site such as a hollow tree trunk (source: https://en.wikipedia.org/wiki/Western_honey_bee)",
        "African honey bees have been found in Florida; they nest in smaller volumes than European bees, including hanging from tree limbs, and defend a larger radius around the nest (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "Miami-Dade County requires a tree removal/relocation permit for any tree not specifically exempt; a tree is a woody plant with a trunk DBH of at least 3 inches or overall height of 12 feet or more; Section 24-49 of the county code (source: https://www.miamidade.gov/global/permit.page?Mduid_permit=per175995275739630)",
        "Municipalities with their own tree ordinances include Coral Gables, Homestead, Miami, Miami Beach, Miami Gardens, Miami Lakes, Miami Springs, North Miami, North Miami Beach, Pinecrest and South Miami (source: https://www.miamidade.gov/global/permit.page?Mduid_permit=per175995275739630)",
        "Florida Statute 163.045: local governments may not require a permit for removal of a tree on residential property (a single-family detached building on a lot used for single-family residential purposes) when the owner has documentation from an ISA certified arborist or a Florida licensed landscape architect that the tree poses an unacceptable risk to persons or property (source: http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0100-0199/0163/Sections/0163.045.html)",
        "Redland is an unincorporated community and agricultural area of Miami-Dade growing mango, avocado, lychee and other tropical fruit, with a large number of ornamental nurseries (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Pinecrest has planted over 10,000 street trees since 1997; ranch-style houses on 1-acre lots were built there in the 1950s and 1960s; it is a village, incorporated in 1996 (source: https://en.wikipedia.org/wiki/Pinecrest,_Florida)",
        "Coconut Grove, annexed into the City of Miami in 1925, has heavy vegetation characteristic of the hammock, and residents take pride that it is one of Miami's greenest areas (source: https://en.wikipedia.org/wiki/Coconut_Grove)",
    ],
}
