# -*- coding: utf-8 -*-
"""Meter, valve and irrigation box page copy."""

SERVICE = {
    "slug": "utility-boxes",
    "title": "Colonies Under Meter & Valve Lids in Miami-Dade",
    "desc": "A colony under a sprinkler valve, pool pit or meter lid? Learn who owns the box, why lifting it is risky, and how the bees get out alive.",
    "h1": "Bees in a Meter, Valve or Irrigation Box in Miami-Dade",
    "kicker": "Below ground, under a lid",
    "lede": "A plastic or concrete box sunk in the lawn is dark, dry on top and about the size a small colony wants. Below: who owns which box, why the lid is the risky part, and what a removal involves.",
    "quick": "Leave the lid where it is. A colony inside a meter, valve or pool equipment box usually hangs its comb from the underside of that lid, so lifting it tears the nest open in your hands. Figure out who owns the box first: the water meter near the street is the utility's, while irrigation valves, sub-meters and pool pits are usually yours. Then call or text us a photo taken from a few steps back. Every bee leaves by gentle vacuum, still living, bound for a beekeeper's apiary.",
    "card": "Colonies in water meter boxes, sprinkler valve boxes, pool equipment pits and pull boxes, handled without tampering with anyone's equipment.",
    "seeing_h": "What you might be noticing at ground level",
    "seeing": [
        "Bees streaming through the finger hole of a lid in the grass, or squeezing in at a cracked corner.",
        "Someone who reads or services the meter mentioned bees at your box, or backed away from it.",
        "Bees rising around your ankles when you mow or edge along the sidewalk, always near the same spot.",
        "A low hum when you stand over the sprinkler valve box or the pool pump pit, even with the system off.",
        "Dark, sticky staining or wax flakes around the rim of a lid, and ants gathering there.",
    ],
    "behind": "A scout bee judges a cavity by darkness, dryness and size, and a buried box passes on all three. The lid keeps rain off, the walls block wind, and the opening is small enough to guard. Workers build comb downward from the lid, then out along pipes, valve bodies or wiring. Within weeks the box can hold brood, stored honey and thousands of bees. Because the colony sits at foot level beside a walkway or lawn, people walk straight into its flight path. Meter boxes appear by name, next to old tires and cement blocks, in the extension service's list of spots where African honey bees have nested, and those bees defend even a small nest hard. You cannot tell which kind you have by looking, so treat every boxed colony as one that may sting.",
    "body": [
        ("Whose box is it, and why that comes first",
         "Not every lid in your yard is yours. The Miami-Dade Water and Sewer Department notes that the water meter usually sits in the front yard near the street or sidewalk, and that meter belongs to the department. If bees are in that box, report it to the utility before anyone opens it. Florida law makes it a crime to alter or interfere with a utility's meter, pipes or wires, and that applies to the people removing bees too. Our crew will not unbolt, cut or move a utility's meter, valve or cable. Irrigation valve boxes, a separate sub-meter for sprinklers or pool filling, and pool equipment pits are normally on the customer's side, so those can be opened once you say so. Electrical pull boxes vary: the stamp on the lid usually tells you whose they are. If you rent, your landlord may need to approve the work; see [[guide:renters-and-landlords|who handles bees in a rental]]."),
        ("Why the lid is the hard part",
         "In a wall or a roof the comb is hidden behind something you can cut and patch. In a buried box the lid is both the door and the ceiling, and the comb is attached to it. Lift it fast and slabs of brood and honey break off, drop into the box or onto the grass, and the whole colony comes up at once. That is the moment people get stung. A slow, controlled lift with the bees calmed first keeps the comb in one piece so it can be cut free and carried off with the bees. Mud, sand or a sprinkler leak can also make the box wet underneath, so the bottom layer of comb may already be soft and moldy. Our [[page:quote|removal request form]] has room for a note about the lid material and any leaks you've noticed."),
        ("Keeping kids, pets and mowers away until then",
         "A ground-level colony is easy to bump without knowing it. Mark off the area with a chair or a cone a few steps back from the box, and pause the mowing and edging service until the bees are out. Run the sprinkler zone fed by that valve as little as you can, since vibration and water both stir the colony. Keep dogs indoors or on the far side of the yard, because they tend to sniff at the hole. If the box sits by a front walk, use another door for now. These steps cost nothing and they keep the problem confined to the lid. When you are not sure where the bees are actually living, [[guide:thermal-imaging|a thermal camera]] can show whether the colony is in the box itself or in a pipe chase or wall next to it."),
    ],
    "band": ("Bees under a lid in your lawn?", "Call any hour, or text a photo taken from a safe distance, and we'll tell you whose box it is and what comes next."),
    "takeout_h": "Getting the colony up and out of the ground",
    "takeout": [
        ("Confirm ownership", "We check the lid markings and where the box sits, and if it is the utility's, the utility is contacted before anything is touched."),
        ("Calm, then lift", "A light puff of smoke settles the bees at the entrance, and the lid is raised slowly with the comb still attached so it does not tear."),
        ("Vacuum the bees", "A low-suction bee vacuum draws the workers into a ventilated box, so the colony leaves the lid and pipes alive and together."),
        ("Cut out every comb", "Brood and honeycomb are cut from the lid, walls, pipes and valve bodies, then tied into frames so the brood travels with its colony."),
        ("Clean and close", "Wax and honey are scraped and washed out of the box, the gaps are dealt with, and the lid goes back on firmly."),
    ],
    "putback": "Honey left in a box keeps calling scouts back, so the inside is scraped and rinsed down to the plastic or concrete, and spilled comb is lifted out of the soil underneath. Cracked lids and broken corners on your own boxes can be replaced, and gaps where pipes or conduit enter can be filled or screened. Should a box we closed up attract a new colony, let us know: the warranty on our workmanship covers a return trip. The [[guide:why-bees-come-back|guide on returning colonies]] explains how lingering scent pulls new swarms in, and for the residue itself see [[svc:honeycomb-cleanup|comb and honey cleanup]].",
    "price": "Price here follows the dig, not the ladder. One box with a clean lid is simple ground-level work, generally about $300 to $400. Comb that has crept down a conduit, under a pool deck or into a wall, a box or lid that cracks and has to be swapped, or waiting on a utility to clear its equipment all push the total up, sometimes into the thousands once repairs join in. Quotes are free, and photos and an itemized bill are available if you want them. See [[page:cost|how removal pricing works]].",
    "price_factors": [
        "How far the comb has spread past the box into pipes, walls or the soil",
        "Whether the box belongs to a utility and needs its sign-off first",
        "A cracked lid, broken box or loose conduit that needs replacing",
        "Sundays and late nights, when the crew rolls out at the emergency rate",
    ],
    "miami_h": "Where boxed-in colonies turn up around the county",
    "miami": [
        ("pinecrest", "Pinecrest grew up around ranch houses on one-acre lots and is heavily landscaped, which means long irrigation runs and plenty of valve boxes hidden in planting beds."),
        ("redland", "Redland is farm country zoned for five-acre minimums, with groves and ornamental nurseries that depend on irrigation boxes scattered far from the house and easy to forget."),
        ("kendall", "Kendall's subdivisions spread from the 1950s on, and their front yards line up meter boxes along the sidewalk where walkers, kids and mowers pass every day."),
        ("doral", "Doral mixes planned communities with a large business district, so a boxed colony may sit beside an office entrance or a shared lawn as easily as a front yard."),
    ],
    "alarm": "If bees are boiling out of a box and someone is being stung, walk away fast in a straight line and get indoors or into a car. Do not swat or jump into a pool. Once you are safe, get the stingers out by dragging a card edge across the skin. Anyone wheezing, with a puffy face or dozens of stings, needs 911 right away. After that, call us about the colony.",
    "faqs": [
        ("Can I just put the lid back down and pour something in the finger hole?",
         "Please don't. Spraying or flooding a buried box kills the bees, leaves rotting comb and honey that draws ants and new swarms, and may damage the meter or valve. On a utility's box it can also count as interfering with its equipment. Live removal clears the bees and the comb together."),
        ("What if the colony is inside the county's own water meter box?",
         "Report it to the Miami-Dade Water and Sewer Department first, since the meter and its box are theirs. Ask how they want it handled and pass along anything they tell you about access. Until then, keep people back and don't lift the lid yourself."),
        ("Is my irrigation sub-meter box my responsibility?",
         "The water department's guidelines put access, cleanout and broken box or cover replacement on the customer for a sub-meter, so in practice that box is yours to keep clear. Bees in it are something you can schedule directly. See also [[svc:live-honey-bees|live honey bee removal]]."),
        ("Will the bees damage my pool pump or valves?",
         "The bees don't chew through equipment, but comb, honey and wax can gum up valve handles, timers and electrical fittings, and a pump left running shakes the colony up. Shut that equipment off if you can and leave the pit closed. For screen cages and pump areas, see [[svc:pool-enclosures|pool enclosures and equipment]]."),
        ("Our buyer's inspection report mentions bees under a sprinkler valve lid. What should we do?",
         "Get a quote and keep the itemized invoice and photos for the buyer's file. A box job is a small one, and we can note which boxes were opened and cleaned. For closing deadlines and what buyers usually ask for, read [[guide:home-sale-inspection|bees found during a sale]]."),
    ],
    "related": ["pool-enclosures", "emergency", "honeycomb-cleanup", "repairs", "live-honey-bees"],
    "close": ("Photograph the lid, not the bees", "Tell us where the box sits and what is stamped on its lid, and the quote, plan and 24-hour response follow from there."),
    "facts": [
        "African honey bees have been found nesting in water meter boxes, cement blocks, old tires, eaves and cavities in the ground, and nest in smaller volumes than European honey bees (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "African bees may attack an intruder with hundreds of bees versus 10-20 for European bees; UF advises having wild colonies removed from places people frequent (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "WASD: the water meter is typically located in the front yard near the street or sidewalk; leaks inside the meter box are reported to the Communications Center; WASD has a Tampering Unit (source: https://www.miamidade.gov/water/library/brochures/about-water-sewer-department.pdf)",
        "WASD sub-meters are on the customer's service line, not in the same box as the department meter, for outside use such as pools and sprinklers; per Rules and Regulations section 2.06(8) the customer must keep the sub-meter accessible, clean out the box and replace a broken box or cover (source: https://www.miamidade.gov/water/library/guidelines/submeters.pdf)",
        "Florida Statute 812.14 prohibits willfully altering or interfering with a utility's meters, pipes, wires, cables or related equipment; utility includes water, sewer, gas, electricity and telephone providers (source: http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0800-0899/0812/Sections/0812.14.html)",
        "Pinecrest incorporated as a village in 1996; ranch-style houses on one-acre lots in the 1950s-60s gave it a lushly landscaped residential character (source: https://en.wikipedia.org/wiki/Pinecrest,_Florida)",
        "Redland is an unincorporated agricultural area with tropical fruit groves and many ornamental nurseries; zoning requires houses on a minimum of 5 acres (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Kendall is an unincorporated area and census-designated place; it saw rapid suburban expansion from the 1950s (source: https://en.wikipedia.org/wiki/Kendall,_Florida)",
        "Doral incorporated in 2003; planned residential communities from the early 1980s and a large business base of over 10,000 businesses by 2005 (source: https://en.wikipedia.org/wiki/Doral,_Florida)",
    ],
}
