# -*- coding: utf-8 -*-
"""Enjambres de abejas: copia en español."""

SERVICIO = {
    "slug": "enjambres",
    "title": "Enjambre de abejas en Miami: esperar o llamar",
    "desc": "Una bola de abejas en una rama, una cerca o el carro: cuándo se va sola y cuándo hay que recogerla viva en Miami-Dade. Cotización gratis, línea 24/7.",
    "h1": "Enjambre de abejas en Miami: cuándo esperar y cuándo llamar",
    "kicker": "Abejas de paso, no una colmena",
    "lede": "Ese racimo zumbante que apareció de golpe en la rama, la reja o el espejo del carro es una colonia mudándose. Casi siempre sigue viaje; aquí le explicamos cómo saber si se queda.",
    "quick": "Un enjambre posado al aire libre es una colonia en tránsito: la reina vieja y miles de obreras esperan mientras unas pocas exploradoras buscan un hueco donde vivir. Lo normal es que se marche por su cuenta, con frecuencia antes de que caiga la tarde y casi nunca pasados tres días. Llame si las abejas empiezan a entrar por una rendija de la casa, si el racimo cuelga junto a una puerta, una piscina o un paso de niños, o si alguien es alérgico. En esos casos lo recogemos vivo y lo entregamos a un apicultor.",
    "card": "Racimos de abejas en ramas, cercas, balcones o carros: cuándo dejarlos ir y cuándo recogerlos vivos antes de que se metan en la casa.",
    "seeing_h": "Así se reconoce un enjambre",
    "seeing": [
        "Una masa compacta de abejas, del tamaño de un balón o de un racimo de uvas, colgando de una rama, un poste o el borde de un toldo.",
        "Una nube ruidosa que gira en el aire durante unos minutos y luego se condensa en un solo punto, como si alguien hubiera vaciado una bolsa de abejas.",
        "Abejas sueltas que entran y salen de una grieta del alero, de un respiradero o de la tapa de una caja de servicio, revisándola por todos lados.",
        "Un racimo pegado a la cerca de cadena, a la baranda del balcón o a la rueda de un carro estacionado desde la noche anterior.",
        "Movimiento ordenado en la superficie del racimo: algunas abejas parecen bailar y otras despegan en una misma dirección.",
    ],
    "behind": "Enjambrar es la forma en que una colonia de abejas melíferas se reproduce. Cuando la colmena original se llena, la reina vieja sale con una buena parte de las obreras y deja atrás a una reina nueva. El grupo que se va no tiene panal, ni cría, ni miel almacenada que proteger, y por eso suele estar más tranquilo que una colonia establecida. Se detiene cerca, se agrupa alrededor de la reina y envía entre veinte y cincuenta exploradoras a revisar cavidades. Ellas regresan y, con la danza del meneo, indican dónde queda el sitio que encontraron. Cuando la mayoría coincide en un lugar, todo el racimo despega hacia allí. El problema aparece si el elegido es su pared, su techo o su contador de agua.",
    "body": [
        ("Qué buscan las exploradoras en una casa de Miami-Dade", "Una colonia necesita un espacio seco, oscuro y protegido, con una entrada pequeña. Los estudios sobre enjambres hablan de un volumen mínimo cercano a 15 litros y una preferencia por unos 40, más o menos lo que cabe en el hueco entre dos montantes de una pared, en la cámara de un sofito o bajo un tramo de tejas. Por eso las exploradoras recorren aleros, rejillas de ventilación sin malla, cajas eléctricas, tubos de cerca abiertos y huecos en bloques de concreto.\n\nLas abejas africanizadas, presentes en Florida, se conforman con cavidades aún más chicas: tapas de contador, bloques huecos, gomas viejas o parrillas que llevan meses sin usarse. Si ve que un puñado de abejas inspecciona con insistencia una de estas aberturas mientras el racimo sigue colgado cerca, es la señal de que esa casa está en la lista. Ese es el momento más barato para actuar, antes de que haya panal adentro. Si ya lo hay, lea [[es:svc-abejas-en-paredes|abejas dentro de paredes]] o [[es:svc-contador-de-agua|abejas en el contador de agua]]."),
        ("Por qué no conviene rociarlo, mojarlo ni espantarlo", "Un racimo tranquilo puede volverse peligroso en segundos si lo provocan. La manguera, el insecticida de supermercado, el humo improvisado o un palo para tumbarlo dispersan a miles de abejas en todas direcciones, y las que caen al suelo o quedan heridas liberan feromona de alarma que pone en guardia al resto. Además, un enjambre espantado no desaparece: busca el refugio más cercano, que muchas veces es el alero o la ventana de la propia casa.\n\nTampoco tiene sentido exterminarlo. Una colonia en tránsito es justo lo que un apicultor quiere recibir: sin panal que cortar, se recoge entera en una caja y empieza de nuevo en un colmenar. Nuestro trabajo es siempre así, en vivo y sin matar abejas; los detalles de cómo se reubican están en [[es:svc-remocion-sin-matarlas|remoción de abejas sin matarlas]]."),
        ("Esperar un día o llamar ya: una regla práctica", "Si el racimo está alto en un árbol, lejos de puertas y caminos, y nadie en la casa es alérgico, lo razonable suele ser mantener a la familia y a las mascotas lejos y observar. La mayoría de los enjambres despegan en cuestión de horas y es raro que alguno siga en el mismo punto pasados tres días.\n\nLlame sin esperar si ocurre cualquiera de estas cosas: las abejas empiezan a entrar en una grieta de la casa, el racimo está sobre una entrada, la piscina, el carro que necesita usar o el patio de juegos, alguien ya recibió picaduras, o el grupo lleva más de un par de días en el mismo lugar y empieza a verse cera. En un balcón de edificio, también conviene avisar a la administración, que suele pedir la constancia de seguro antes de dejarnos subir."),
    ],
    "band": ("¿Un racimo de abejas en su propiedad ahora mismo?", "Mándenos una foto por texto con el lugar exacto donde cuelga; la línea contesta a cualquier hora y la cotización no cuesta nada."),
    "takeout_h": "Cómo se recoge un enjambre vivo",
    "takeout": [
        ("Ubicar el racimo y la reina", "Revisamos dónde está posado el grupo y si alguna abeja ya está entrando en una rendija. Cuando hay dudas sobre una pared o un alero, la cámara térmica muestra si dentro ya se formó una colonia."),
        ("Caja ventilada debajo del racimo", "Colocamos una caja de transporte justo debajo y, con un movimiento seco de la rama o con un cepillo suave, la mayor parte del enjambre cae adentro junto con la reina."),
        ("Esperar a las rezagadas", "Dejamos la caja abierta un rato cerca del punto original. Las abejas que quedaron volando siguen el olor de la reina y entran solas, sin necesidad de rociar nada."),
        ("Revisar y cerrar las entradas", "Antes de irnos miramos aleros, respiraderos y cajas cercanas. Si las exploradoras marcaron una abertura, la sellamos para que el siguiente enjambre no la encuentre tan fácil."),
        ("Entrega a un apicultor", "La caja cerrada viaja al colmenar de un apicultor que recibe la colonia viva. Si quiere, le enviamos fotos del proceso y una factura con el detalle de cada partida."),
    ],
    "putback": "Cuando el enjambre solo estaba de paso, casi no queda nada que reparar: limpiamos las abejas muertas o la cera que haya quedado en la rama o la cerca. Si ya había empezado a entrar en la casa, sellamos la abertura y, si hubo que abrir tejas, sofito o drywall, el arreglo queda en manos de gente de la casa: techadores, pintores y contratistas, cada uno con su licencia. Lo que sellamos queda respaldado por nuestra garantía de trabajo: si las abejas regresan a ese mismo punto, volvemos sin discusión.",
    "price": "Recoger un enjambre al aire libre y a poca altura es de los trabajos más sencillos, y a nivel del suelo suele rondar entre $300 y $400. El precio sube cuando el racimo cuelga alto, cuando hay que trabajar desde un balcón de varios pisos o cuando la colonia ya se metió en una pared o un techo y hace falta abrir y reparar; esos casos complejos pueden llegar a miles de dólares. Un sábado o a medianoche la tarifa es mayor que un martes en horario normal. Vea [[es:precios|precios]] para más detalle.",
    "price_factors": [
        "Altura del racimo y si se alcanza con escalera, con extensión o solo desde un balcón alto.",
        "Si las abejas siguen afuera o ya entraron en una pared, un techo o una caja de servicio.",
        "Cuánto hay que abrir, sellar y reparar después de sacar la colonia.",
        "Horario de la visita: noche, fin de semana o un día de semana normal.",
    ],
    "zonas_h": "Dónde aparecen enjambres en Miami-Dade",
    "zonas": [
        ("hialeah", "Con más de diez mil habitantes por milla cuadrada, en Hialeah un enjambre en la cerca rara vez está lejos de la puerta de un vecino. Allí recogerlo pronto evita picaduras en el pasillo y en la acera."),
        ("doral", "Buena parte de los parques empresariales del condado están en Doral. Un racimo sobre un letrero, una rampa de carga o un carro del estacionamiento se coordina con la administración del almacén."),
        ("miami", "Entre las torres de Brickell y el resto de la ciudad, los enjambres a veces se posan en barandas de balcón o en jardineras de terraza, donde hay que trabajar con permiso del edificio."),
        ("homestead", "Hacia el sur, junto a los viveros y huertos de frutas tropicales de la Redland, abundan las abejas; los racimos aparecen en cercas, cobertizos y troncos de patio."),
    ],
    "alarm": "Si el enjambre se alborotó y las abejas persiguen a alguien, aléjese corriendo, cúbrase nariz, boca y ojos subiéndose la camisa, y refúgiese en un carro o un cuarto cerrado; no se quede quieto manoteando. Ante hinchazón de la cara o la garganta, mareo o dificultad para respirar, llame al 911 primero. Después llámenos: la línea está atendida las 24 horas y las emergencias con picaduras pasan delante. Más en [[es:svc-emergencias|emergencias con abejas]].",
    "faqs": [
        ("¿Un enjambre de abejas pica más que una colmena?", "En general menos. Un grupo en tránsito no tiene panal, cría ni miel que defender, así que mientras nadie lo moleste suele ignorar a la gente. Eso cambia si alguien lo golpea, lo moja o lo rocía, y con abejas africanizadas la reacción puede ser más fuerte y extenderse más lejos."),
        ("El racimo lleva tres días en mi árbol, ¿qué significa?", "Que algo no salió como se espera. Puede que las exploradoras no se pongan de acuerdo o que el grupo haya empezado a construir panal allí mismo, al aire libre. Pasado ese plazo conviene que lo veamos: una colonia que se instala crece rápido y se vuelve más defensiva."),
        ("¿Puedo manejar el carro con abejas pegadas?", "Mejor no moverlo. Arrancar sacude el racimo y lo dispersa en la calle, y algunas abejas pueden quedar dentro del capó o del maletero. Si necesita el carro con urgencia, avísenos al llamar; recogemos el enjambre donde está estacionado."),
        ("¿Por qué siguen llegando abejas al mismo lugar de la casa?", "Una cavidad que alguna vez tuvo colonia conserva el olor de la cera y la feromona, y eso atrae a nuevas exploradoras. Hay que limpiar bien el hueco y sellarlo. Si ya tiene panal adentro, lea [[es:svc-panales-y-colmenas|quitar panales y colmenas]] o pida una [[es:solicitar|cotización gratis]]."),
        ("¿El apicultor de verdad se queda con las abejas?", "Sí. El enjambre se entrega vivo a apicultores que lo instalan en una colmena de su colmenar, donde sigue polinizando y produciendo miel. Ninguna colonia que recogemos termina fumigada; su destino es una caja de madera en un colmenar, nunca un bote de basura."),
    ],
    "relacionados": ["abejas-en-paredes", "contador-de-agua", "remocion-sin-matarlas", "emergencias"],
    "close": ("Que el enjambre siga su camino, lejos de su casa", "Cuéntenos dónde cuelga y desde cuándo; le decimos si conviene esperar o recogerlo, con cotización gratis en cualquier punto de Miami-Dade."),
    "facts": [
        "Enjambrar es la reproducción de la colonia: la reina vieja sale con parte de las obreras; es sobre todo un fenómeno de primavera (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "El enjambre se agrupa cerca del nido original alrededor de la reina y envía de 20 a 50 exploradoras; normalmente se va en pocas horas y es inusual que permanezca más de tres días en la parada intermedia (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "Las exploradoras comunican sitios con la danza del meneo; la decisión se toma cuando cerca del 80% coincide o hay quórum de 20-30 exploradoras en un sitio (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "Un buen sitio de nido tiene un mínimo de unos 15 litros, preferiblemente unos 40, con entrada pequeña (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "Los enjambres son menos defensivos porque no tienen cría que defender y su interés es encontrar un nuevo nido (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "Las abejas africanizadas enjambran con más frecuencia, viven más a menudo en cavidades en el suelo y defienden una zona de alarma más amplia; se extienden por Florida (source: https://en.wikipedia.org/wiki/Africanized_bee)",
        "Las abejas africanas anidan en volúmenes más pequeños: cajas de contador de agua, bloques de cemento, gomas viejas, aleros y parrillas; ante un ataque hay que correr, cubrir cabeza y vías respiratorias con la camisa y buscar un vehículo o estructura cerrada (source: https://ask.ifas.ufl.edu/publication/IN790)",
        "Hialeah tiene una densidad de unos 10,338 habitantes por milla cuadrada (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Doral contiene 14 de los más de 30 parques empresariales de Miami-Dade (source: https://www.cityofdoral.com/About/Doral-Facts)",
        "Brickell es el barrio más denso de Miami, con torres de gran altura (source: https://en.wikipedia.org/wiki/Brickell)",
        "La Redland, zona agrícola no incorporada al noroeste de Homestead, cultiva frutas tropicales y viveros ornamentales (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
    ],
}
