# -*- coding: utf-8 -*-
"""Remoción de abejas sin matarlas: copia en español."""

SERVICIO = {
    "slug": "remocion-sin-matarlas",
    "title": "Remoción de abejas sin matarlas, con cría y sin veneno",
    "desc": "Rescate de abejas en Miami-Dade: la colonia sale viva, con su cría y su panal, y se entrega a un apicultor. Sin veneno y con cotización gratis.",
    "h1": "Rescate de abejas vivas en Miami-Dade, sin veneno",
    "kicker": "Remoción en vivo, cero pesticidas",
    "lede": "Una colonia de abejas melíferas vale más viva que muerta, para usted y para el apicultor que la recibe. Aquí explicamos cómo se rescata entera y por qué el insecticida termina costando más.",
    "quick": "Sí, se puede. Las abejas adultas, la reina y los panales con cría salen juntos del muro, del alero o de la caja de servicio donde se hayan instalado, se acomodan en una caja de colmena y viajan a manos de un apicultor. No se usa ningún pesticida. Después se raspa la cera restante, se limpia la cavidad y se cierra la entrada. Hay alguien al teléfono a cualquier hora, cualquier día, y le aseguramos una respuesta antes de que pasen 24 horas; si alguien ya sufrió picaduras, su caso pasa al frente.",
    "seeing_h": "Cuándo conviene pedir un rescate y no una fumigación",
    "seeing": [
        "Una fila constante de abejas entra y sale por la misma rendija de un muro, del plafón del alero o de una teja, sobre todo a media mañana y por la tarde.",
        "Al apoyar la oreja en la pared de yeso se escucha un zumbido grave y parejo, y la pared se siente tibia en un punto concreto.",
        "Una bola de abejas cuelga de una rama, una cerca o el buzón: es un enjambre de paso que todavía se puede recoger completo.",
        "Alguien ya roció veneno, aparecieron abejas muertas en el piso y, días después, las vivas siguen entrando por el mismo hueco.",
        "Hay manchas oscuras o pegajosas en el techo o la pared, señal de panal con miel detrás que se está ablandando.",
    ],
    "behind": "Dentro de la cavidad la colonia funciona como un solo organismo. La reina pone huevos en las celdas del panal y las obreras alimentan a las larvas hasta que, unas tres semanas después, nace una abeja nueva. Ese conjunto de huevos, larvas y pupas se llama cría, y es lo que mantiene a la colonia unida a su sitio: las abejas rara vez abandonan a su cría. Por eso el rescate funciona cuando se lleva todo junto. Si solo se aspiran las abejas visibles, las que quedan regresan a cuidar los panales; si se rocía insecticida, la cría muere en sus celdas, la cera queda envenenada y nadie puede aprovechar esa colonia. Trasladar abejas, reina y cría en la misma caja le da a la colonia lo que necesita para seguir viviendo en un colmenar.",
    "body": [
        ("Qué pasa cuando se fumiga una colmena dentro de la casa", "El insecticida acaba con las obreras que toca, pero el panal sigue en su lugar. Sin obreras que ventilen la cavidad, la cera y la miel se recalientan; la cera de abeja se derrite entre 62 y 64 °C, y en un ático o una pared que recibe sol de tarde eso se acerca más de lo que parece. La miel escurre por dentro del muro, deja aureolas en el acabado, y ese aroma dulce invita a hormigas, cucarachas y ratones.\n\nLuego llegan las plagas propias de la colmena. Las orugas de Galleria mellonella, la polilla mayor de la cera, perforan galerías forradas de seda en los panales abandonados, y las del pequeño escarabajo de la colmena fermentan la miel hasta dejarla espumosa y con olor a naranja podrida. Por si fuera poco, las abejas que estaban fuera cuando se aplicó el producto vuelven, encuentran la entrada y siguen allí. Muchas veces el resultado final es abrir la pared de todas formas, solo que ahora para sacar un panal muerto y apestoso en lugar de una colonia sana. Para ver qué implica abrir un muro, consulte [[es:svc-abejas-en-paredes|abejas dentro de paredes]]."),
        ("Por qué la cría viaja con las abejas", "Una colonia sin cría queda huérfana de futuro: las abejas adultas viven pocas semanas en temporada activa y, si no nacen otras, la colonia se apaga. Por eso, al abrir la cavidad, cada panal con cría se corta con cuidado y se sujeta en marcos de madera con ligas o cordel, igual que una página que se vuelve a encuadernar. Esos marcos entran en una caja de colmena estándar, y las abejas adultas, que siguen el olor de su reina y de su cría, se van metiendo en la caja por su cuenta.\n\nLos panales que solo tienen miel no se pueden aprovechar de la misma manera, porque pesan, gotean y atraen saqueo; se retiran por completo para que no queden dentro de su casa. Terminado el trabajo, la caja se cierra y viaja hasta el colmenar de un apicultor, donde la colonia continúa su vida. Si lo que usted tiene es un enjambre todavía colgado, sin panal, el procedimiento es más sencillo; lo contamos en [[es:svc-enjambres|enjambres de abejas]]."),
        ("Un enjambre posado no es una amenaza", "Ver miles de abejas sobre una rama asusta, pero un enjambre en tránsito suele ser manso. No tiene cría ni miel que defender, y su único interés es esperar a que las exploradoras encuentren una cavidad nueva. Ese descanso normalmente dura menos de tres días. Si en ese tiempo nadie lo molesta, es el momento ideal para recogerlo vivo y entero, antes de que escoja su pared o su techo como hogar definitivo.\n\nLo que no conviene es rociarlo con la manguera, echarle insecticida de lata o golpear la rama. Eso solo dispersa a las abejas, las pone a la defensiva y las empuja a meterse en el primer hueco cercano, que a veces es el alero de su propia casa. Mantenga a niños y mascotas lejos, tome una foto desde una distancia segura y envíenosla por texto."),
    ],
    "band": ("Antes de rociar, mándenos una foto", "Una imagen de la entrada y una idea de cuánto tiempo llevan allí nos ayudan a preparar la visita. La cotización, como siempre, es gratis."),
    "takeout_h": "Cómo sale una colonia viva de su propiedad",
    "takeout": [
        ("Ubicación con cámara térmica", "La cámara térmica revela la temperatura de la colonia escondida tras paneles de yeso, estuco o techo. Con esa imagen se dibuja el contorno del panal y se abre solo lo necesario, justo encima."),
        ("Apertura sin químicos", "Se retira el plafón del alero, el panel de yeso o la teja con calma y sin rociar nada. El objetivo es que la colonia siga tranquila y completa mientras el panal queda a la vista."),
        ("La cría, a los marcos", "Cada panal con huevos, larvas y pupas se corta entero y se fija en marcos dentro de la caja de colmena. Si la reina aparece, viaja con ellas."),
        ("Abejas adultas a la caja", "Las obreras se recogen con cuidado y van entrando a la caja siguiendo el olor de la cría. Se espera a que regresen las pecoreadoras antes de cerrar."),
        ("Entrega al apicultor", "La caja cerrada, con abejas, reina y cría juntas, sale de su casa y queda en manos de un apicultor que continuará cuidando esa colonia."),
    ],
    "putback": "El rescate no termina cuando sale la caja. Raspamos cada resto de cera y miel de la cavidad, porque ese olor es justo lo que guía a un enjambre nuevo hacia el mismo lugar, y limpiamos la superficie. La entrada se sella con material adecuado al sitio. Si hubo que abrir pared, techo o alero, la reparación queda en manos de nuestro propio equipo de contratistas, techadores y pintores, cada uno con su licencia, no de un tercero desconocido. Ese cierre no caduca: cualquier punto sellado por nosotros que vuelva a tener abejas nos trae de nuevo a su propiedad, sin plazo de por medio.",
    "price": "Si la colonia está a ras del piso y se alcanza sin escalera, el rescate cuesta por lo general de $300 a $400. Un panal que llena media pared, que cuelga en un segundo piso o que obliga a rehacer tejas, estuco o paneles de yeso puede llevar la factura hasta los miles de dólares, sobre todo por la reparación. Cotizar no le cuesta nada, y a pedido entregamos fotos del proceso junto con una factura detallada. Vea más en [[es:precios|precios]].",
    "price_factors": [
        "Tamaño de la colonia y cuántos panales hay que cortar y trasladar a los marcos.",
        "Dónde se escondió la colonia: un contador en el césped se trabaja de pie; un hueco bajo el techo de un segundo piso pide andamio o escalera.",
        "Lo que haya que desmontar para llegar al panal y luego reconstruir, desde un panel de yeso (drywall) hasta varias filas de tejas.",
        "Momento de la visita: las urgencias nocturnas y las de sábado o domingo tienen recargo frente a un día laborable.",
    ],
    "zonas_h": "Rescates en distintos rincones de Miami-Dade",
    "zonas": [
        ("homestead", "Junto a [[es:zona-homestead|Homestead]] está Redland, con aguacates, mangos, lichis y viveros que dependen de la polinización. Aquí sacar abejas sin matarlas tiene un sentido muy práctico: cada colonia rescatada sigue polinizando en algún colmenar."),
        ("westchester", "Muchas casas de Westchester nacieron a partir de la urbanización de 1955 y las que siguieron en los años sesenta. Muros y aleros con décadas encima ofrecen rendijas donde una colonia entra sin hacer ruido."),
        ("hialeah", "En una ciudad tan densa como Hialeah, una colonia fumigada en una pared compartida afecta a varios vecinos a la vez. Sacarla viva y completa evita panales podridos al otro lado del muro."),
        ("doral", "Doral reúne muchos parques empresariales, almacenes y centros de distribución. Para esas naves y oficinas enviamos el certificado de seguro (COI) antes de entrar y trabajamos sin fumigar cerca de mercancía ni personal."),
    ],
    "alarm": "Si alguien recibió varias picaduras o las abejas están entrando a la casa, cierre puertas y ventanas, lleve a todos adentro y no rocíe nada: el veneno las altera más. Ante labios o párpados hinchados, o dificultad para respirar, el número es el 911, antes que el nuestro. Después, nuestra línea de [[es:svc-emergencias|emergencias con abejas]] pone su caso al frente de la fila.",
    "faqs": [
        ("¿De verdad las abejas sobreviven a la mudanza?", "Una colonia que viaja con su reina y su cría tiene todo lo que necesita para seguir adelante. Por eso cortamos los panales con cría y los montamos en marcos en vez de dejarlos atrás. El apicultor que la recibe la instala en su colmenar y la cuida desde ahí."),
        ("¿Por qué no fumigar si sale más barato al principio?", "Porque el panal se queda adentro. La miel escurre por la pared, la cera atrae plagas y las abejas que andaban fuera regresan al mismo hueco. A menudo hay que abrir la pared igual, ahora para sacar un panal podrido. El rescate en vivo resuelve el problema de una sola vez."),
        ("Ya rociaron insecticida, ¿todavía pueden ayudar?", "Sí. Si quedan abejas vivas, se intenta rescatar lo que se pueda; la cera y la miel contaminadas no se pueden dar a un apicultor, así que se retiran y se desechan. Después dejamos el hueco limpio y cerrado, para que el olor no guíe hasta allí a otro enjambre."),
        ("¿Qué hacen con la miel que sale de mi pared?", "Los panales de miel se retiran por completo porque, si se quedan, fermentan, gotean y atraen hormigas y otras plagas. Lo importante para su casa es que no quede ni un trozo de cera adentro; más detalles en [[es:svc-panales-y-colmenas|quitar panales y colmenas]]. La cría, en cambio, sí viaja con las abejas hacia el apicultor."),
        ("¿Un rescate en vivo tarda más que una fumigación?", "La visita sí requiere más tiempo en el sitio, porque hay que abrir, cortar panales y esperar a que las pecoreadoras vuelvan a la caja. A cambio, no queda nada muerto adentro. Cuánto dura depende del tamaño de la colonia y de dónde esté; se lo explicamos al cotizar."),
    ],
    "relacionados": ["panales-y-colmenas", "enjambres", "abejas-en-paredes", "emergencias"],
    "close": ("Que sus abejas terminen en un colmenar", "Díganos en qué rincón de la casa están y desde hace cuánto; puede [[es:solicitar|pedir el rescate aquí]], con cotización gratis, en todo Miami-Dade."),
    "card": "Abejas, reina y cría salen juntas en una caja de colmena rumbo a un apicultor. Sin insecticidas, con limpieza de la cera y la entrada sellada.",
    "facts": [
        "La cría de las abejas melíferas son los huevos, larvas y pupas; la reina pone un huevo en cada celda del panal; las larvas reciben jalea real tres días y luego miel diluida y polen; la obrera emerge hacia el día 21 (source: https://en.wikipedia.org/wiki/Brood_(honey_bee))",
        "La cera de abeja se funde entre 62 y 64 °C (144 a 147 °F); las obreras construyen con ella las celdas del panal (source: https://en.wikipedia.org/wiki/Beeswax)",
        "Un enjambre recién salido se posa en un árbol o rama, rara vez más de tres días, mientras las exploradoras buscan una cavidad; los enjambres no suelen ser agresivos porque no tienen cría que defender (source: https://en.wikipedia.org/wiki/Swarming_(honey_bee))",
        "Las larvas de la polilla mayor de la cera (Galleria mellonella) se alimentan de la cera del panal, abren túneles forrados de seda y destruyen panales; la miel se escurre cuando comen los opérculos (source: https://en.wikipedia.org/wiki/Galleria_mellonella)",
        "Las larvas del pequeño escarabajo de la colmena excavan panales con miel, la fermentan y la vuelven espumosa, con olor a naranjas podridas (source: https://en.wikipedia.org/wiki/Small_hive_beetle)",
        "Redland, área agrícola no incorporada al noroeste de Homestead, cultiva aguacates, mangos, lichis y otras frutas tropicales, además de viveros ornamentales (source: https://en.wikipedia.org/wiki/Redland,_Florida)",
        "Una subdivisión de 1955 llamada Westchester inició el desarrollo de la posguerra y dio nombre al área; le siguieron otras en los años sesenta (source: https://www.miamidade.gov/planning/library/reports/nb3-history-of-westchester.pdf)",
        "Hialeah tenía 223,109 habitantes en 2020, con una densidad de unos 10,338 por milla cuadrada (source: https://en.wikipedia.org/wiki/Hialeah,_Florida)",
        "Doral contiene 14 de los más de 30 parques empresariales de Miami-Dade; su uso industrial permite almacenes y centros de distribución (source: https://www.cityofdoral.com/About/Doral-Facts)",
    ],
}
